import type Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import type { ElementType, EquipmentSlot, ItemGrade } from '@mud/shared';

export const STARTING_ROOM_ID = 1;

const DEFAULT_ADMIN_USERNAME = process.env.DEFAULT_ADMIN_USERNAME ?? 'admin';
const DEFAULT_ADMIN_PASSWORD = process.env.DEFAULT_ADMIN_PASSWORD ?? 'admin1234';
const SALT_ROUNDS = 10;

if (!process.env.DEFAULT_ADMIN_PASSWORD) {
  console.warn(
    `[db] DEFAULT_ADMIN_PASSWORD not set; seeding default admin account "${DEFAULT_ADMIN_USERNAME}" with a well-known password. Change it (or set DEFAULT_ADMIN_USERNAME/DEFAULT_ADMIN_PASSWORD) before exposing this server publicly.`,
  );
}

interface RoomSeed {
  id: number;
  name: string;
  description: string;
}

interface ExitSeed {
  roomId: number;
  direction: string;
  targetRoomId: number;
}

interface ItemSeed {
  id: number;
  name: string;
  description: string;
  type: 'weapon' | 'armor' | 'consumable';
  slot: EquipmentSlot | null;
  level: number;
  grade: ItemGrade;
  strengthBonus: number;
  dexterityBonus: number;
  attackPowerBonus: number;
  physicalDefenseBonus: number;
  magicDefenseBonus: number;
  healAmount: number;
  manaAmount: number;
  value: number;
}

interface RoomItemSeed {
  roomId: number;
  itemId: number;
  quantity: number;
}

interface MobTemplateSeed {
  id: number;
  name: string;
  hp: number;
  strength: number;
  dexterity: number;
  physicalDefense: number;
  magicDefense: number;
  element: ElementType;
  damageType: 'physical' | 'magic';
  expReward: number;
  goldReward: number;
  level: number;
}

interface MobSpawnSeed {
  roomId: number;
  mobTemplateId: number;
  respawnSeconds: number;
}

const ROOMS: RoomSeed[] = [
  {
    id: 1,
    name: '마을 광장',
    description:
      '오래된 돌바닥이 깔린 마을 광장이다. 낡은 분수대에서 물이 졸졸 흐르고, 주위로 몇 채의 건물이 늘어서 있다.',
  },
  {
    id: 2,
    name: '여관',
    description: '나무 냄새가 은은하게 풍기는 아늑한 여관이다. 벽난로에서 장작이 타닥타닥 타오른다.',
  },
  {
    id: 3,
    name: '대장간',
    description: '쇠 두드리는 소리가 쩌렁쩌렁 울리는 대장간이다. 화로의 열기가 얼굴을 스친다.',
  },
  {
    id: 4,
    name: '상점',
    description: '온갖 잡화가 어지럽게 쌓여 있는 상점이다. 주인은 어디 갔는지 보이지 않는다.',
  },
  {
    id: 5,
    name: '마을 어귀',
    description: '마을을 벗어나는 길목이다. 저 멀리 숲의 초입이 보인다.',
  },
  {
    id: 6,
    name: '숲 입구',
    description: '커다란 나무들이 하늘을 가리기 시작하는 숲의 입구다.',
  },
  {
    id: 7,
    name: '어두운 숲',
    description: '햇빛이 거의 들지 않는 어두운 숲속이다. 어디선가 부스럭거리는 소리가 들린다.',
  },
  {
    id: 8,
    name: '오래된 다리',
    description: '금방이라도 무너질 듯한 낡은 나무다리가 계곡을 가로지르고 있다.',
  },
  {
    id: 9,
    name: '폐허',
    description: '누가 살았는지 알 수 없는 오래된 건물의 잔해가 남아있다.',
  },
  {
    id: 10,
    name: '미개척지',
    description:
      '황무지 너머, 아직 누구의 깃발도 꽂히지 않은 땅이 펼쳐진다. 이곳에서 새로운 마을을 세우거나(village found), 이미 세워진 마을 목록을 볼(village list) 수 있다.',
  },
];

export const FRONTIER_ROOM_ID = 10;

const EXITS: ExitSeed[] = [
  { roomId: 1, direction: 'north', targetRoomId: 2 },
  { roomId: 2, direction: 'south', targetRoomId: 1 },
  { roomId: 1, direction: 'east', targetRoomId: 3 },
  { roomId: 3, direction: 'west', targetRoomId: 1 },
  { roomId: 1, direction: 'west', targetRoomId: 4 },
  { roomId: 4, direction: 'east', targetRoomId: 1 },
  { roomId: 1, direction: 'south', targetRoomId: 5 },
  { roomId: 5, direction: 'north', targetRoomId: 1 },
  { roomId: 5, direction: 'south', targetRoomId: 6 },
  { roomId: 6, direction: 'north', targetRoomId: 5 },
  { roomId: 6, direction: 'south', targetRoomId: 7 },
  { roomId: 7, direction: 'north', targetRoomId: 6 },
  { roomId: 7, direction: 'east', targetRoomId: 8 },
  { roomId: 8, direction: 'west', targetRoomId: 7 },
  { roomId: 8, direction: 'east', targetRoomId: 9 },
  { roomId: 9, direction: 'west', targetRoomId: 8 },
  { roomId: 9, direction: 'south', targetRoomId: 10 },
  { roomId: 10, direction: 'north', targetRoomId: 9 },
];

const ITEMS: ItemSeed[] = [
  {
    id: 1,
    name: '낡은 검',
    description: '날이 조금 무뎌졌지만 여전히 쓸만한 검이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 1,
    grade: 'low',
    strengthBonus: 3,
    attackPowerBonus: 4,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 2,
    name: '나무 방패',
    description: '투박하지만 튼튼한 나무 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 3,
    name: '체력 물약',
    description: '마시면 체력이 회복되는 붉은 물약이다.',
    type: 'consumable',
    slot: null,
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 10,
    manaAmount: 0,
    value: 5,
  },
  {
    id: 4,
    name: '가죽 모자',
    description: '가볍게 머리를 보호해주는 가죽 모자다.',
    type: 'armor',
    slot: 'hat',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 6,
  },
  {
    id: 5,
    name: '은귀걸이',
    description: '은은하게 빛나는 은귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 6,
    name: '수호의 목걸이',
    description: '마법 기운이 감도는 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 9,
  },
  {
    id: 7,
    name: '가죽 갑옷',
    description: '몸통을 감싸는 튼튼한 가죽 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 1,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 8,
    name: '가죽 각반',
    description: '다리를 보호하는 가죽 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 9,
    name: '가죽 장갑',
    description: '손놀림을 가볍게 해주는 가죽 장갑이다.',
    type: 'armor',
    slot: 'gloves',
    level: 1,
    grade: 'low',
    strengthBonus: 1,
    attackPowerBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 10,
    name: '가죽 신발',
    description: '발걸음을 가볍게 해주는 가죽 신발이다.',
    type: 'armor',
    slot: 'shoes',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 11,
    name: '힘의 반지',
    description: '착용자의 힘을 북돋아주는 반지다.',
    type: 'armor',
    slot: 'ring',
    level: 1,
    grade: 'low',
    strengthBonus: 2,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 12,
  },
  {
    id: 12,
    name: '강철 검',
    description: '단단하게 벼려진 강철 검이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 5,
    grade: 'mid',
    strengthBonus: 5,
    attackPowerBonus: 10,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 40,
  },
  {
    id: 13,
    name: '사슬 갑옷',
    description: '촘촘히 엮은 사슬로 만든 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 14,
    name: '마나 물약',
    description: '푸르게 빛나는 마나 회복 물약이다.',
    type: 'consumable',
    slot: null,
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 20,
    value: 15,
  },
  {
    id: 15,
    name: '강철 방패',
    description: '묵직하지만 방어력이 뛰어난 강철 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 30,
  },
  {
    id: 16,
    name: '미스릴 검',
    description: '가볍고 예리한 미스릴로 벼린 검이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 10,
    grade: 'high',
    strengthBonus: 8,
    attackPowerBonus: 18,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 17,
    name: '기사의 갑옷',
    description: '왕실 기사단이 착용하던 정교한 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 6,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 80,
  },
  {
    id: 18,
    name: '상급 회복 물약',
    description: '진한 붉은빛을 띠는 강력한 회복 물약이다.',
    type: 'consumable',
    slot: null,
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 40,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 19,
    name: '은빛 반지',
    description: '은은한 은빛으로 빛나는 민첩의 반지다.',
    type: 'armor',
    slot: 'ring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 70,
  },
  {
    id: 20,
    name: '용의 발톱',
    description: '고대 용의 발톱으로 벼려낸 무기다.',
    type: 'weapon',
    slot: 'weapon',
    level: 20,
    grade: 'rare',
    strengthBonus: 12,
    attackPowerBonus: 30,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 200,
  },
  {
    id: 21,
    name: '수호자의 방패',
    description: '고대 수호자가 사용하던 견고한 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 10,
    magicDefenseBonus: 5,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  {
    id: 22,
    name: '엘릭서',
    description: '희귀한 재료로 정제한 만능 회복약이다.',
    type: 'consumable',
    slot: null,
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 80,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 23,
    name: '바람의 신발',
    description: '신은 이의 발걸음을 바람처럼 가볍게 만든다.',
    type: 'armor',
    slot: 'shoes',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 160,
  },
  {
    id: 24,
    name: '전설의 대검',
    description: '수많은 영웅담에 등장하는 전설의 대검이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 35,
    grade: 'legend',
    strengthBonus: 20,
    attackPowerBonus: 50,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 500,
  },
  {
    id: 25,
    name: '드래곤 스케일 갑옷',
    description: '용의 비늘로 만든 전설적인 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 15,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 450,
  },
  {
    id: 26,
    name: '천상의 물약',
    description: '하늘의 축복이 담긴 신비로운 물약이다.',
    type: 'consumable',
    slot: null,
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 150,
    manaAmount: 0,
    value: 220,
  },
  {
    id: 27,
    name: '불사조 깃털 목걸이',
    description: '불사조의 깃털로 만든 신비한 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 12,
    healAmount: 0,
    manaAmount: 0,
    value: 400,
  },
  {
    id: 28,
    name: '종말의 검',
    description: '세상의 종말을 부른다는 금단의 무기다.',
    type: 'weapon',
    slot: 'weapon',
    level: 50,
    grade: 'epic',
    strengthBonus: 30,
    attackPowerBonus: 80,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 1200,
  },
  {
    id: 29,
    name: '창세의 방패',
    description: '세상이 시작될 때부터 존재했다는 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 20,
    magicDefenseBonus: 15,
    healAmount: 0,
    manaAmount: 0,
    value: 1100,
  },
  {
    id: 30,
    name: '신들의 축복 물약',
    description: '신들이 직접 축복을 내렸다는 전설의 물약이다.',
    type: 'consumable',
    slot: null,
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 300,
    manaAmount: 0,
    value: 600,
  },
  {
    id: 31,
    name: '무한의 반지',
    description: '착용자에게 무한한 힘을 부여한다는 반지다.',
    type: 'armor',
    slot: 'ring',
    level: 50,
    grade: 'epic',
    strengthBonus: 10,
    attackPowerBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  // --- 중급(mid) 등급 보강: 등급당 10개를 채우기 위한 추가 방어구 ---
  {
    id: 32,
    name: '강철 투구',
    description: '머리를 단단히 보호하는 강철 투구다.',
    type: 'armor',
    slot: 'hat',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 25,
  },
  {
    id: 33,
    name: '흑요석 귀걸이',
    description: '검게 빛나는 흑요석으로 만든 귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 22,
  },
  {
    id: 34,
    name: '마력 목걸이',
    description: '은은한 마력이 흐르는 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 28,
  },
  {
    id: 35,
    name: '강철 각반',
    description: '다리를 감싸는 튼튼한 강철 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  {
    id: 36,
    name: '강철 장갑',
    description: '손아귀 힘을 더해주는 강철 장갑이다.',
    type: 'armor',
    slot: 'gloves',
    level: 5,
    grade: 'mid',
    strengthBonus: 2,
    attackPowerBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 24,
  },
  {
    id: 37,
    name: '은빛 부츠',
    description: '가볍게 반짝이는 은빛 부츠다.',
    type: 'armor',
    slot: 'shoes',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  // --- 상급(high) 등급 보강 ---
  {
    id: 38,
    name: '기사의 방패',
    description: '왕실 기사단의 문양이 새겨진 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 75,
  },
  {
    id: 39,
    name: '기사의 투구',
    description: '왕실 기사단이 착용하던 정교한 투구다.',
    type: 'armor',
    slot: 'hat',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 5,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 65,
  },
  {
    id: 40,
    name: '사파이어 귀걸이',
    description: '푸른 사파이어가 박힌 귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 5,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  {
    id: 41,
    name: '마법사의 목걸이',
    description: '마법 저항력을 높여주는 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 7,
    healAmount: 0,
    manaAmount: 0,
    value: 68,
  },
  {
    id: 42,
    name: '기사의 각반',
    description: '왕실 기사단이 착용하던 견고한 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 62,
  },
  {
    id: 43,
    name: '사냥꾼의 장갑',
    description: '민첩한 손놀림을 위한 사냥꾼의 장갑이다.',
    type: 'armor',
    slot: 'gloves',
    level: 10,
    grade: 'high',
    strengthBonus: 4,
    attackPowerBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  // --- 레어(rare) 등급 보강 ---
  {
    id: 44,
    name: '용비늘 투구',
    description: '용의 비늘 조각으로 만든 투구다.',
    type: 'armor',
    slot: 'hat',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 9,
    magicDefenseBonus: 4,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 45,
    name: '심연의 귀걸이',
    description: '깊은 심연의 기운이 감도는 귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 46,
    name: '대현자의 목걸이',
    description: '대현자가 남겼다는 지혜의 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 14,
    healAmount: 0,
    manaAmount: 0,
    value: 170,
  },
  {
    id: 47,
    name: '수호자의 갑옷',
    description: '고대 수호자가 두르던 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 12,
    magicDefenseBonus: 6,
    healAmount: 0,
    manaAmount: 0,
    value: 190,
  },
  {
    id: 48,
    name: '수호자의 각반',
    description: '고대 수호자가 두르던 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 49,
    name: '폭풍의 반지',
    description: '착용자에게 폭풍의 힘을 불어넣는 반지다.',
    type: 'armor',
    slot: 'ring',
    level: 20,
    grade: 'rare',
    strengthBonus: 6,
    attackPowerBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  // --- 레전드(legend) 등급 보강 ---
  {
    id: 50,
    name: '용의 방패',
    description: '용의 뼈와 비늘로 벼려낸 방패다.',
    type: 'armor',
    slot: 'shield',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 420,
  },
  {
    id: 51,
    name: '용의 투구',
    description: '용의 머리뼈를 본떠 만든 투구다.',
    type: 'armor',
    slot: 'hat',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 16,
    magicDefenseBonus: 8,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 52,
    name: '별빛 귀걸이',
    description: '밤하늘의 별빛을 담은 귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 360,
  },
  {
    id: 53,
    name: '용의 각반',
    description: '용의 가죽으로 만든 튼튼한 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 14,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 54,
    name: '용의 장갑',
    description: '용의 발톱을 엮어 만든 장갑이다.',
    type: 'armor',
    slot: 'gloves',
    level: 35,
    grade: 'legend',
    strengthBonus: 14,
    attackPowerBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 370,
  },
  {
    id: 55,
    name: '질풍의 신발',
    description: '바람보다 빠르게 만들어준다는 신발이다.',
    type: 'armor',
    slot: 'shoes',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 390,
  },
  // --- 에픽(epic) 등급 보강 ---
  {
    id: 56,
    name: '창세의 투구',
    description: '세상이 창조될 때부터 존재했다는 투구다.',
    type: 'armor',
    slot: 'hat',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 25,
    magicDefenseBonus: 18,
    healAmount: 0,
    manaAmount: 0,
    value: 950,
  },
  {
    id: 57,
    name: '태초의 귀걸이',
    description: '태초의 힘이 깃든 귀걸이다.',
    type: 'armor',
    slot: 'earring',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 22,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 58,
    name: '영원의 목걸이',
    description: '영원히 빛바래지 않는다는 목걸이다.',
    type: 'armor',
    slot: 'necklace',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 28,
    healAmount: 0,
    manaAmount: 0,
    value: 980,
  },
  {
    id: 59,
    name: '창세의 갑옷',
    description: '세상이 창조될 때부터 존재했다는 갑옷이다.',
    type: 'armor',
    slot: 'top',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 30,
    magicDefenseBonus: 22,
    healAmount: 0,
    manaAmount: 0,
    value: 1150,
  },
  {
    id: 60,
    name: '창세의 각반',
    description: '세상이 창조될 때부터 존재했다는 각반이다.',
    type: 'armor',
    slot: 'bottom',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 920,
  },
  {
    id: 61,
    name: '파멸의 장갑',
    description: '닿는 모든 것을 파멸로 이끈다는 장갑이다.',
    type: 'armor',
    slot: 'gloves',
    level: 50,
    grade: 'epic',
    strengthBonus: 22,
    attackPowerBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
];

const ROOM_ITEMS: RoomItemSeed[] = [
  { roomId: 3, itemId: 1, quantity: 1 },
  { roomId: 4, itemId: 2, quantity: 1 },
  { roomId: 2, itemId: 3, quantity: 2 },
  { roomId: 4, itemId: 4, quantity: 1 },
  { roomId: 4, itemId: 5, quantity: 1 },
  { roomId: 4, itemId: 6, quantity: 1 },
  { roomId: 4, itemId: 7, quantity: 1 },
  { roomId: 4, itemId: 8, quantity: 1 },
  { roomId: 4, itemId: 9, quantity: 1 },
  { roomId: 4, itemId: 10, quantity: 1 },
  { roomId: 4, itemId: 11, quantity: 1 },
];

const MOB_TEMPLATES: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 8,
    strength: 2,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 15,
    strength: 4,
    dexterity: 2,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    goldReward: 5,
    level: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 10,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    goldReward: 2,
    level: 1,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 5,
    strength: 5,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 14,
    strength: 1,
    dexterity: 1,
    physicalDefense: 2,
    magicDefense: 1,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 7,
    strength: 4,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 12,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 8,
    name: '덩굴괴수',
    hp: 42,
    strength: 9,
    dexterity: 4,
    physicalDefense: 6,
    magicDefense: 2,
    element: 'wood',
    damageType: 'physical',
    expReward: 18,
    goldReward: 8,
    level: 5,
  },
  {
    id: 9,
    name: '불도마뱀',
    hp: 19,
    strength: 21,
    dexterity: 6,
    physicalDefense: 1,
    magicDefense: 2,
    element: 'fire',
    damageType: 'magic',
    expReward: 14,
    goldReward: 8,
    level: 5,
  },
  {
    id: 10,
    name: '바위골렘',
    hp: 60,
    strength: 5,
    dexterity: 4,
    physicalDefense: 7,
    magicDefense: 3,
    element: 'earth',
    damageType: 'physical',
    expReward: 22,
    goldReward: 8,
    level: 5,
  },
  {
    id: 11,
    name: '강철전갈',
    hp: 29,
    strength: 15,
    dexterity: 5,
    physicalDefense: 5,
    magicDefense: 2,
    element: 'metal',
    damageType: 'physical',
    expReward: 17,
    goldReward: 8,
    level: 5,
  },
  {
    id: 12,
    name: '늪지악어',
    hp: 48,
    strength: 10,
    dexterity: 5,
    physicalDefense: 6,
    magicDefense: 1,
    element: 'water',
    damageType: 'physical',
    expReward: 19,
    goldReward: 8,
    level: 5,
  },
  {
    id: 13,
    name: '덩굴괴수',
    hp: 81,
    strength: 17,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 5,
    element: 'wood',
    damageType: 'physical',
    expReward: 36,
    goldReward: 16,
    level: 10,
  },
  {
    id: 14,
    name: '불도마뱀',
    hp: 37,
    strength: 42,
    dexterity: 12,
    physicalDefense: 2,
    magicDefense: 5,
    element: 'fire',
    damageType: 'magic',
    expReward: 30,
    goldReward: 16,
    level: 10,
  },
  {
    id: 15,
    name: '바위골렘',
    hp: 117,
    strength: 10,
    dexterity: 8,
    physicalDefense: 13,
    magicDefense: 6,
    element: 'earth',
    damageType: 'physical',
    expReward: 43,
    goldReward: 16,
    level: 10,
  },
  {
    id: 16,
    name: '강철전갈',
    hp: 57,
    strength: 29,
    dexterity: 10,
    physicalDefense: 9,
    magicDefense: 3,
    element: 'metal',
    damageType: 'physical',
    expReward: 33,
    goldReward: 16,
    level: 10,
  },
  {
    id: 17,
    name: '늪지악어',
    hp: 94,
    strength: 19,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 3,
    element: 'water',
    damageType: 'physical',
    expReward: 38,
    goldReward: 16,
    level: 10,
  },
  {
    id: 18,
    name: '덩굴괴수',
    hp: 121,
    strength: 26,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 7,
    element: 'wood',
    damageType: 'physical',
    expReward: 55,
    goldReward: 24,
    level: 15,
  },
  {
    id: 19,
    name: '불도마뱀',
    hp: 55,
    strength: 62,
    dexterity: 18,
    physicalDefense: 3,
    magicDefense: 7,
    element: 'fire',
    damageType: 'magic',
    expReward: 45,
    goldReward: 24,
    level: 15,
  },
  {
    id: 20,
    name: '바위골렘',
    hp: 174,
    strength: 14,
    dexterity: 11,
    physicalDefense: 20,
    magicDefense: 9,
    element: 'earth',
    damageType: 'physical',
    expReward: 65,
    goldReward: 24,
    level: 15,
  },
  {
    id: 21,
    name: '강철전갈',
    hp: 85,
    strength: 44,
    dexterity: 16,
    physicalDefense: 13,
    magicDefense: 4,
    element: 'metal',
    damageType: 'physical',
    expReward: 49,
    goldReward: 24,
    level: 15,
  },
  {
    id: 22,
    name: '늪지악어',
    hp: 140,
    strength: 28,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 4,
    element: 'water',
    damageType: 'physical',
    expReward: 57,
    goldReward: 24,
    level: 15,
  },
  {
    id: 23,
    name: '덩굴괴수',
    hp: 160,
    strength: 34,
    dexterity: 17,
    physicalDefense: 22,
    magicDefense: 10,
    element: 'wood',
    damageType: 'physical',
    expReward: 73,
    goldReward: 32,
    level: 20,
  },
  {
    id: 24,
    name: '불도마뱀',
    hp: 73,
    strength: 82,
    dexterity: 24,
    physicalDefense: 4,
    magicDefense: 10,
    element: 'fire',
    damageType: 'magic',
    expReward: 60,
    goldReward: 32,
    level: 20,
  },
  {
    id: 25,
    name: '바위골렘',
    hp: 232,
    strength: 19,
    dexterity: 15,
    physicalDefense: 27,
    magicDefense: 11,
    element: 'earth',
    damageType: 'physical',
    expReward: 87,
    goldReward: 32,
    level: 20,
  },
  {
    id: 26,
    name: '강철전갈',
    hp: 113,
    strength: 58,
    dexterity: 21,
    physicalDefense: 18,
    magicDefense: 6,
    element: 'metal',
    damageType: 'physical',
    expReward: 67,
    goldReward: 32,
    level: 20,
  },
  {
    id: 27,
    name: '늪지악어',
    hp: 186,
    strength: 37,
    dexterity: 18,
    physicalDefense: 22,
    magicDefense: 6,
    element: 'water',
    damageType: 'physical',
    expReward: 77,
    goldReward: 32,
    level: 20,
  },
  {
    id: 28,
    name: '덩굴괴수',
    hp: 200,
    strength: 43,
    dexterity: 21,
    physicalDefense: 28,
    magicDefense: 12,
    element: 'wood',
    damageType: 'physical',
    expReward: 92,
    goldReward: 40,
    level: 25,
  },
  {
    id: 29,
    name: '불도마뱀',
    hp: 91,
    strength: 102,
    dexterity: 30,
    physicalDefense: 5,
    magicDefense: 12,
    element: 'fire',
    damageType: 'magic',
    expReward: 75,
    goldReward: 40,
    level: 25,
  },
  {
    id: 30,
    name: '바위골렘',
    hp: 289,
    strength: 24,
    dexterity: 19,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'earth',
    damageType: 'physical',
    expReward: 108,
    goldReward: 40,
    level: 25,
  },
  {
    id: 31,
    name: '강철전갈',
    hp: 141,
    strength: 72,
    dexterity: 26,
    physicalDefense: 22,
    magicDefense: 7,
    element: 'metal',
    damageType: 'physical',
    expReward: 83,
    goldReward: 40,
    level: 25,
  },
  {
    id: 32,
    name: '늪지악어',
    hp: 232,
    strength: 46,
    dexterity: 22,
    physicalDefense: 28,
    magicDefense: 7,
    element: 'water',
    damageType: 'physical',
    expReward: 96,
    goldReward: 40,
    level: 25,
  },
  {
    id: 33,
    name: '덩굴괴수',
    hp: 240,
    strength: 51,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'wood',
    damageType: 'physical',
    expReward: 110,
    goldReward: 48,
    level: 30,
  },
  {
    id: 34,
    name: '불도마뱀',
    hp: 109,
    strength: 123,
    dexterity: 36,
    physicalDefense: 6,
    magicDefense: 14,
    element: 'fire',
    damageType: 'magic',
    expReward: 90,
    goldReward: 48,
    level: 30,
  },
  {
    id: 35,
    name: '바위골렘',
    hp: 346,
    strength: 28,
    dexterity: 22,
    physicalDefense: 40,
    magicDefense: 17,
    element: 'earth',
    damageType: 'physical',
    expReward: 130,
    goldReward: 48,
    level: 30,
  },
  {
    id: 36,
    name: '강철전갈',
    hp: 169,
    strength: 87,
    dexterity: 31,
    physicalDefense: 27,
    magicDefense: 9,
    element: 'metal',
    damageType: 'physical',
    expReward: 101,
    goldReward: 48,
    level: 30,
  },
  {
    id: 37,
    name: '늪지악어',
    hp: 278,
    strength: 56,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 8,
    element: 'water',
    damageType: 'physical',
    expReward: 114,
    goldReward: 48,
    level: 30,
  },
  {
    id: 38,
    name: '덩굴괴수',
    hp: 279,
    strength: 60,
    dexterity: 30,
    physicalDefense: 39,
    magicDefense: 17,
    element: 'wood',
    damageType: 'physical',
    expReward: 129,
    goldReward: 56,
    level: 35,
  },
  {
    id: 39,
    name: '불도마뱀',
    hp: 127,
    strength: 143,
    dexterity: 42,
    physicalDefense: 7,
    magicDefense: 17,
    element: 'fire',
    damageType: 'magic',
    expReward: 105,
    goldReward: 56,
    level: 35,
  },
  {
    id: 40,
    name: '바위골렘',
    hp: 403,
    strength: 33,
    dexterity: 26,
    physicalDefense: 46,
    magicDefense: 20,
    element: 'earth',
    damageType: 'physical',
    expReward: 152,
    goldReward: 56,
    level: 35,
  },
  {
    id: 41,
    name: '강철전갈',
    hp: 197,
    strength: 101,
    dexterity: 36,
    physicalDefense: 31,
    magicDefense: 10,
    element: 'metal',
    damageType: 'physical',
    expReward: 116,
    goldReward: 56,
    level: 35,
  },
  {
    id: 42,
    name: '늪지악어',
    hp: 324,
    strength: 65,
    dexterity: 31,
    physicalDefense: 39,
    magicDefense: 10,
    element: 'water',
    damageType: 'physical',
    expReward: 134,
    goldReward: 56,
    level: 35,
  },
  {
    id: 43,
    name: '덩굴괴수',
    hp: 319,
    strength: 68,
    dexterity: 34,
    physicalDefense: 44,
    magicDefense: 19,
    element: 'wood',
    damageType: 'physical',
    expReward: 146,
    goldReward: 64,
    level: 40,
  },
  {
    id: 44,
    name: '불도마뱀',
    hp: 145,
    strength: 163,
    dexterity: 48,
    physicalDefense: 8,
    magicDefense: 19,
    element: 'fire',
    damageType: 'magic',
    expReward: 120,
    goldReward: 64,
    level: 40,
  },
  {
    id: 45,
    name: '바위골렘',
    hp: 460,
    strength: 38,
    dexterity: 30,
    physicalDefense: 53,
    magicDefense: 23,
    element: 'earth',
    damageType: 'physical',
    expReward: 174,
    goldReward: 64,
    level: 40,
  },
  {
    id: 46,
    name: '강철전갈',
    hp: 225,
    strength: 115,
    dexterity: 41,
    physicalDefense: 35,
    magicDefense: 12,
    element: 'metal',
    damageType: 'physical',
    expReward: 133,
    goldReward: 64,
    level: 40,
  },
  {
    id: 47,
    name: '늪지악어',
    hp: 370,
    strength: 74,
    dexterity: 35,
    physicalDefense: 44,
    magicDefense: 11,
    element: 'water',
    damageType: 'physical',
    expReward: 153,
    goldReward: 64,
    level: 40,
  },
  {
    id: 48,
    name: '덩굴괴수',
    hp: 358,
    strength: 77,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 21,
    element: 'wood',
    damageType: 'physical',
    expReward: 165,
    goldReward: 72,
    level: 45,
  },
  {
    id: 49,
    name: '불도마뱀',
    hp: 163,
    strength: 183,
    dexterity: 54,
    physicalDefense: 9,
    magicDefense: 21,
    element: 'fire',
    damageType: 'magic',
    expReward: 134,
    goldReward: 72,
    level: 45,
  },
  {
    id: 50,
    name: '바위골렘',
    hp: 518,
    strength: 42,
    dexterity: 33,
    physicalDefense: 59,
    magicDefense: 25,
    element: 'earth',
    damageType: 'physical',
    expReward: 194,
    goldReward: 72,
    level: 45,
  },
  {
    id: 51,
    name: '강철전갈',
    hp: 253,
    strength: 129,
    dexterity: 46,
    physicalDefense: 40,
    magicDefense: 13,
    element: 'metal',
    damageType: 'physical',
    expReward: 150,
    goldReward: 72,
    level: 45,
  },
  {
    id: 52,
    name: '늪지악어',
    hp: 416,
    strength: 83,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 12,
    element: 'water',
    damageType: 'physical',
    expReward: 172,
    goldReward: 72,
    level: 45,
  },
  {
    id: 53,
    name: '덩굴괴수',
    hp: 398,
    strength: 85,
    dexterity: 43,
    physicalDefense: 55,
    magicDefense: 24,
    element: 'wood',
    damageType: 'physical',
    expReward: 183,
    goldReward: 80,
    level: 50,
  },
  {
    id: 54,
    name: '불도마뱀',
    hp: 181,
    strength: 204,
    dexterity: 61,
    physicalDefense: 10,
    magicDefense: 24,
    element: 'fire',
    damageType: 'magic',
    expReward: 150,
    goldReward: 80,
    level: 50,
  },
  {
    id: 55,
    name: '바위골렘',
    hp: 575,
    strength: 47,
    dexterity: 37,
    physicalDefense: 66,
    magicDefense: 28,
    element: 'earth',
    damageType: 'physical',
    expReward: 217,
    goldReward: 80,
    level: 50,
  },
  {
    id: 56,
    name: '강철전갈',
    hp: 281,
    strength: 144,
    dexterity: 52,
    physicalDefense: 44,
    magicDefense: 15,
    element: 'metal',
    damageType: 'physical',
    expReward: 167,
    goldReward: 80,
    level: 50,
  },
  {
    id: 57,
    name: '늪지악어',
    hp: 462,
    strength: 92,
    dexterity: 44,
    physicalDefense: 55,
    magicDefense: 14,
    element: 'water',
    damageType: 'physical',
    expReward: 191,
    goldReward: 80,
    level: 50,
  },
];

const MOB_SPAWNS: MobSpawnSeed[] = [
  { roomId: 6, mobTemplateId: 1, respawnSeconds: 20 },
  { roomId: 7, mobTemplateId: 2, respawnSeconds: 30 },
  { roomId: 9, mobTemplateId: 1, respawnSeconds: 20 },
];

export function seed(db: Database.Database): void {
  const existing = db.prepare('SELECT id FROM rooms WHERE id = ?').get(STARTING_ROOM_ID);
  if (existing) return;

  const insertRoom = db.prepare('INSERT INTO rooms (id, name, description) VALUES (?, ?, ?)');
  const insertExit = db.prepare(
    'INSERT INTO room_exits (room_id, direction, target_room_id) VALUES (?, ?, ?)',
  );
  const insertItem = db.prepare(
    `INSERT INTO items (id, name, description, type, slot, level, grade, strength_bonus, dexterity_bonus, attack_power_bonus, physical_defense_bonus, magic_defense_bonus, heal_amount, mana_amount, value)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  );
  const insertRoomItem = db.prepare(
    'INSERT INTO room_items (room_id, item_id, quantity) VALUES (?, ?, ?)',
  );
  const insertMobTemplate = db.prepare(
    `INSERT INTO mob_templates (id, name, hp, strength, dexterity, physical_defense, magic_defense, element, damage_type, exp_reward, gold_reward, level)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  );
  const insertMobSpawn = db.prepare(
    'INSERT INTO mob_spawns (room_id, mob_template_id, respawn_seconds) VALUES (?, ?, ?)',
  );
  const insertAdminAccount = db.prepare(
    'INSERT INTO accounts (username, password_hash, is_builder, is_admin) VALUES (?, ?, 1, 1)',
  );

  const seedTx = db.transaction(() => {
    insertAdminAccount.run(DEFAULT_ADMIN_USERNAME, bcrypt.hashSync(DEFAULT_ADMIN_PASSWORD, SALT_ROUNDS));
    for (const room of ROOMS) insertRoom.run(room.id, room.name, room.description);
    for (const exit of EXITS) insertExit.run(exit.roomId, exit.direction, exit.targetRoomId);
    for (const item of ITEMS) {
      insertItem.run(
        item.id,
        item.name,
        item.description,
        item.type,
        item.slot,
        item.level,
        item.grade,
        item.strengthBonus,
        item.dexterityBonus,
        item.attackPowerBonus,
        item.physicalDefenseBonus,
        item.magicDefenseBonus,
        item.healAmount,
        item.manaAmount,
        item.value,
      );
    }
    for (const roomItem of ROOM_ITEMS) {
      insertRoomItem.run(roomItem.roomId, roomItem.itemId, roomItem.quantity);
    }
    for (const template of MOB_TEMPLATES) {
      insertMobTemplate.run(
        template.id,
        template.name,
        template.hp,
        template.strength,
        template.dexterity,
        template.physicalDefense,
        template.magicDefense,
        template.element,
        template.damageType,
        template.expReward,
        template.goldReward,
        template.level,
      );
    }
    for (const spawn of MOB_SPAWNS) {
      insertMobSpawn.run(spawn.roomId, spawn.mobTemplateId, spawn.respawnSeconds);
    }
  });
  seedTx();
}
