import type Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import type { ElementType, EquipmentSlot, ItemGrade } from '@mud/shared';

export const STARTING_ROOM_ID = 1;

const DEFAULT_ADMIN_USERNAME = process.env.DEFAULT_ADMIN_USERNAME ?? 'admin';
const DEFAULT_ADMIN_PASSWORD = process.env.DEFAULT_ADMIN_PASSWORD ?? 'admin1234';
const SALT_ROUNDS = 10;

if (!process.env.DEFAULT_ADMIN_PASSWORD) {
  console.warn(
    `[db] DEFAULT_ADMIN_PASSWORD not set; seeding default admin account "${DEFAULT_ADMIN_USERNAME}" with a well-known password. Change it (or set DEFAULT_ADMIN_USERNAME/DEFAULT_ADMIN_PASSWORD) before exposing this server publicly.`,
  );
}

interface RoomSeed {
  id: number;
  name: string;
  description: string;
}

interface ExitSeed {
  roomId: number;
  direction: string;
  targetRoomId: number;
}

interface ItemSeed {
  id: number;
  name: string;
  description: string;
  type: 'weapon' | 'armor' | 'consumable';
  slot: EquipmentSlot | null;
  level: number;
  grade: ItemGrade;
  strengthBonus: number;
  dexterityBonus: number;
  attackPowerBonus: number;
  intelligenceBonus: number;
  physicalDefenseBonus: number;
  magicDefenseBonus: number;
  healAmount: number;
  manaAmount: number;
  value: number;
}

interface RoomItemSeed {
  roomId: number;
  itemId: number;
  quantity: number;
}

interface MobTemplateSeed {
  id: number;
  name: string;
  hp: number;
  strength: number;
  dexterity: number;
  physicalDefense: number;
  magicDefense: number;
  element: ElementType;
  damageType: 'physical' | 'magic';
  expReward: number;
  goldReward: number;
  level: number;
}

interface MobSpawnSeed {
  roomId: number;
  mobTemplateId: number;
  respawnSeconds: number;
}

const ROOMS: RoomSeed[] = [
  {
    id: 1,
    name: '마을 광장',
    description:
      '오래된 돌바닥이 깔린 마을 광장이다. 낡은 분수대에서 물이 졸졸 흐르고, 주위로 몇 채의 건물이 늘어서 있다.',
  },
  {
    id: 2,
    name: '여관',
    description: '나무 냄새가 은은하게 풍기는 아늑한 여관이다. 벽난로에서 장작이 타닥타닥 타오른다.',
  },
  {
    id: 3,
    name: '대장간',
    description: '쇠 두드리는 소리가 쩌렁쩌렁 울리는 대장간이다. 화로의 열기가 얼굴을 스친다.',
  },
  {
    id: 4,
    name: '상점',
    description: '온갖 잡화가 어지럽게 쌓여 있는 상점이다. 주인은 어디 갔는지 보이지 않는다.',
  },
  {
    id: 5,
    name: '마을 어귀',
    description: '마을을 벗어나는 길목이다. 저 멀리 숲의 초입이 보인다.',
  },
  {
    id: 6,
    name: '숲 입구',
    description: '커다란 나무들이 하늘을 가리기 시작하는 숲의 입구다.',
  },
  {
    id: 7,
    name: '어두운 숲',
    description: '햇빛이 거의 들지 않는 어두운 숲속이다. 어디선가 부스럭거리는 소리가 들린다.',
  },
  {
    id: 8,
    name: '오래된 다리',
    description: '금방이라도 무너질 듯한 낡은 나무다리가 계곡을 가로지르고 있다.',
  },
  {
    id: 9,
    name: '폐허',
    description: '누가 살았는지 알 수 없는 오래된 건물의 잔해가 남아있다.',
  },
  {
    id: 10,
    name: '미개척지',
    description:
      '황무지 너머, 아직 누구의 깃발도 꽂히지 않은 땅이 펼쳐진다. 이곳에서 새로운 마을을 세우거나(village found), 이미 세워진 마을 목록을 볼(village list) 수 있다.',
  },
];

export const FRONTIER_ROOM_ID = 10;

const EXITS: ExitSeed[] = [
  { roomId: 1, direction: 'north', targetRoomId: 2 },
  { roomId: 2, direction: 'south', targetRoomId: 1 },
  { roomId: 1, direction: 'east', targetRoomId: 3 },
  { roomId: 3, direction: 'west', targetRoomId: 1 },
  { roomId: 1, direction: 'west', targetRoomId: 4 },
  { roomId: 4, direction: 'east', targetRoomId: 1 },
  { roomId: 1, direction: 'south', targetRoomId: 5 },
  { roomId: 5, direction: 'north', targetRoomId: 1 },
  { roomId: 5, direction: 'south', targetRoomId: 6 },
  { roomId: 6, direction: 'north', targetRoomId: 5 },
  { roomId: 6, direction: 'south', targetRoomId: 7 },
  { roomId: 7, direction: 'north', targetRoomId: 6 },
  { roomId: 7, direction: 'east', targetRoomId: 8 },
  { roomId: 8, direction: 'west', targetRoomId: 7 },
  { roomId: 8, direction: 'east', targetRoomId: 9 },
  { roomId: 9, direction: 'west', targetRoomId: 8 },
  { roomId: 9, direction: 'south', targetRoomId: 10 },
  { roomId: 10, direction: 'north', targetRoomId: 9 },
];

export const ITEMS: ItemSeed[] = [
  {
    id: 1,
    name: '낡은 검',
    description: '손잡이 가죽이 해지고 칼날 곳곳에 붉은 녹이 슨 낡은 철검이다. 무딘 회색 날에는 작은 이가 빠진 흠집이 여러 군데 나 있고, 자루 끝엔 색이 바랜 갈색 가죽끈이 느슨하게 감겨 있다. 칼등을 따라 희미하게 남은 대장간 각인이 오랜 세월을 짐작하게 하며, 손에 쥐면 묵직하고 투박한 무게감이 느껴지는 초보자용 무기다. 무광의 어두운 회색 톤이 전체를 감싼다.',
    type: 'weapon',
    slot: 'weapon',
    level: 1,
    grade: 'low',
    strengthBonus: 3,
    attackPowerBonus: 4,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 2,
    name: '나무 방패',
    description: '판자를 덧대어 만든 투박한 원형 나무 방패로, 표면은 옅은 갈색 나무결이 그대로 드러난다. 가장자리를 따라 낡은 철테가 둘러져 있고 중앙에는 간단한 방패 문양이 새겨져 있다. 여러 번의 타격으로 생긴 긁힘과 패임 자국이 곳곳에 남아 있으며, 뒷면 손잡이는 낡은 가죽끈으로 고정되어 있다. 시골 대장간에서 급히 짜맞춘 듯 투박하지만 정겨운 분위기를 풍긴다.',
    type: 'armor',
    slot: 'shield',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 3,
    name: '체력 물약',
    description: '투명한 유리병에 담긴 진한 붉은 액체로, 병 입구는 코르크 마개로 막혀 있고 목 부분에는 붉은 리본이 매듭지어 묶여 있다. 살짝 흔들면 은은하게 반짝이는 작은 입자들이 소용돌이치듯 떠오르며, 병 표면에는 방금 만든 듯 신선한 물방울이 맺혀 있다. 안에서 따뜻한 붉은빛이 은은히 감돌며, 촛불 아래 놓아두면 은은한 붉은 잔광이 주변을 물들인다.',
    type: 'consumable',
    slot: null,
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 10,
    manaAmount: 0,
    value: 5,
  },
  {
    id: 4,
    name: '가죽 모자',
    description: '부드러운 갈색 가죽을 여러 겹 덧대 만든 챙 없는 가죽 모자로, 이마 부분에 작은 놋쇠 버클 장식이 달려 있다. 안감은 짙은 색 천으로 마감되어 있고 표면에는 잔주름과 손때 묻은 사용감이 남아 있다. 튼튼하게 바느질된 이음매가 눈에 띄며, 모험가의 첫 방어구다운 소박하고 투박한 실루엣을 지녔다. 낡았지만 정성껏 손질된 흔적이 곳곳에 배어 있다.',
    type: 'armor',
    slot: 'hat',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 6,
  },
  {
    id: 5,
    name: '은귀걸이',
    description: '가늘게 세공된 은사슬에 작은 초승달 모양 장식이 매달린 귀걸이다. 표면은 은은한 광택이 돌며 달빛을 받으면 옅은 푸른빛을 반사한다. 장식 끝에는 좁쌀만 한 보석 알갱이가 박혀 있어 걸을 때마다 희미하게 짤랑거리고, 사슬 마디마다 아주 작은 별 모양 각인이 새겨져 있다. 소박하지만 세심하게 다듬어진 손끝의 정성이 느껴지는 장신구다.',
    type: 'armor',
    slot: 'earring',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 6,
    name: '수호의 목걸이',
    description: '은사슬 목걸이 중앙에 옅은 청록빛으로 은은히 빛나는 작은 마법석이 박혀 있다. 돌 표면에는 가느다란 룬 문양이 소용돌이 모양으로 새겨져 있고, 은은한 마력의 안개가 돌 주위를 감싸듯 피어오른다. 목걸이 줄은 촘촘하게 엮여 있어 단단하면서도 우아한 인상을 주며 착용자의 목선을 따라 자연스럽게 흘러내려 은은한 마력의 기운을 은근히 드러낸다.',
    type: 'armor',
    slot: 'necklace',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 9,
  },
  {
    id: 7,
    name: '가죽 갑옷',
    description: '무두질한 갈색 가죽을 겹겹이 덧대 만든 상체 갑옷으로, 어깨와 가슴 부분에 두꺼운 가죽판이 덧대어져 있다. 옆구리는 여러 개의 끈으로 조여 몸에 맞추는 구조이며, 표면에는 크고 작은 스크래치와 긁힘 자국이 나 있다. 전체적으로 투박하지만 견고한 초보자용 방어구의 느낌을 풍기며, 어깨선을 따라 실용적인 이중 재봉선이 도드라진다.',
    type: 'armor',
    slot: 'top',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 1,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 8,
    name: '가죽 각반',
    description: '무릎까지 오는 갈색 가죽 각반으로, 다리 바깥쪽에 세로로 긴 가죽 보강대가 덧대어져 있다. 버클 두 개로 종아리에 단단히 고정하며, 가죽 표면에는 걸을 때마다 생긴 자잘한 접힘 주름이 선명하게 보인다. 실용적이고 활동성을 중시한 투박한 디자인이 특징이며, 무릎 아래로 자연스럽게 각이 잡혀 있다.',
    type: 'armor',
    slot: 'bottom',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 9,
    name: '가죽 장갑',
    description: '손등을 덮는 짧은 갈색 가죽 장갑으로, 손가락 마디 부분이 살짝 두툼하게 보강되어 있다. 손목 부분은 가는 가죽 끈으로 조이게 되어 있으며, 표면에는 오래 착용한 흔적인 옅은 얼룩과 손때로 길들여진 은은한 광택이 남아 있다. 손끝 마감이 세밀하게 재봉되어 있어 투박함 속에서도 정교함이 느껴진다.',
    type: 'armor',
    slot: 'gloves',
    level: 1,
    grade: 'low',
    strengthBonus: 1,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 10,
    name: '가죽 신발',
    description: '발등을 감싸는 갈색 가죽 신발로, 밑창은 두꺼운 가죽을 덧대 튼튼하게 마감했다. 발목 부분은 끈으로 교차해 묶게 되어 있고, 표면에는 흙먼지가 묻은 자국과 오랜 걸음걸이로 생긴 자연스러운 주름이 남아 있다. 뒤축은 살짝 닳아 있어 오래 신은 듯한 정겨운 느낌을 주며, 발끝 쪽으로 갈수록 완만하게 둥글다.',
    type: 'armor',
    slot: 'shoes',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 11,
    name: '힘의 반지',
    description: '가는 은반지 위에 작은 붉은 보석이 박혀 있는 소박한 반지다. 반지 안쪽에는 희미하게 빛나는 각인이 새겨져 있어 착용자의 힘을 북돋아준다고 전해진다. 표면은 은은한 광택을 띠며 오래된 대장간에서 손수 만든 듯한 투박한 세공이 돋보이고, 보석 주변에는 미세한 긁힘 자국이 남아 있어 손때 묻은 정겨움이 배어난다.',
    type: 'armor',
    slot: 'ring',
    level: 1,
    grade: 'low',
    strengthBonus: 2,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 12,
  },
  {
    id: 12,
    name: '강철 검',
    description: '잘 벼려진 은회색 강철 검으로, 날이 곧고 예리하게 서 있어 빛을 받으면 매끄럽게 반사된다. 칼자루는 짙은 청색 가죽으로 감싸여 있고, 손잡이 끝에는 작은 철제 장식이 달려 있다. 칼날 근처에 새겨진 가는 덩굴무늬가 은은하게 반짝이며, 낡은 검보다 한층 정교하고 균형 잡힌 인상을 준다. 대장간에서 갓 벼려낸 듯한 청량한 금속 광택이 돋보인다.',
    type: 'weapon',
    slot: 'weapon',
    level: 5,
    grade: 'mid',
    strengthBonus: 5,
    attackPowerBonus: 10,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 40,
  },
  {
    id: 13,
    name: '사슬 갑옷',
    description: '촘촘히 엮인 강철 사슬로 만들어진 상체 갑옷으로, 사슬 고리들이 빼곡히 겹쳐져 은빛으로 반짝인다. 목과 어깨 부분은 부드러운 가죽으로 덧대 마감했으며, 착용하면 몸의 움직임에 따라 사슬이 부드럽게 찰랑거리는 소리를 낸다. 견고하면서도 유연한 인상을 주는 중급 방어구로, 허리춤까지 촘촘히 이어진 고리들이 은은한 파동처럼 빛난다.',
    type: 'armor',
    slot: 'top',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 14,
    name: '마나 물약',
    description: '푸르게 빛나는 액체가 담긴 유리병으로, 병 속에서 작은 마력 입자가 별처럼 반짝이며 떠다닌다. 병 입구는 은색 마개로 밀봉되어 있고, 목 부분에는 파란 리본이 나비 모양으로 묶여 있다. 병을 살짝 흔들면 옅은 청백색 빛이 소용돌이치듯 일렁이며 병 표면까지 은은하게 번지고, 손에 쥐면 서늘하고 상쾌한 냉기가 전해진다.',
    type: 'consumable',
    slot: null,
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 20,
    value: 15,
  },
  {
    id: 15,
    name: '강철 방패',
    description: '두꺼운 강철판을 둥글게 두드려 만든 방패로, 표면 중앙에 볼록한 돌기가 솟아 있다. 가장자리는 이중으로 리벳 처리되어 있으며, 짙은 회색 금속 광택이 묵직한 존재감을 준다. 방패 안쪽에는 팔을 고정하는 두꺼운 가죽 손잡이가 달려 있고, 곳곳에 실전에서 생긴 자잘한 흠집이 남아 있어 노련한 방어구의 풍모가 느껴진다.',
    type: 'armor',
    slot: 'shield',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 30,
  },
  {
    id: 16,
    name: '미스릴 검',
    description: '은백색으로 빛나는 미스릴로 벼려낸 얇고 가벼운 검이다. 칼날은 거의 투명에 가까운 광택을 띠며, 빛을 받으면 무지갯빛으로 은은하게 반사된다. 칼자루에는 정교한 덩굴무늬가 새겨져 있고, 손잡이 끝에는 작은 푸른 보석이 박혀 있어 휘두를 때마다 옅은 빛의 궤적을 남긴다. 손에 쥐면 놀랍도록 가볍고 균형이 완벽하게 잡혀 있다.',
    type: 'weapon',
    slot: 'weapon',
    level: 10,
    grade: 'high',
    strengthBonus: 8,
    attackPowerBonus: 18,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 17,
    name: '기사의 갑옷',
    description: '정교하게 세공된 은빛 판금 갑옷으로, 가슴판 중앙에 왕실 문장이 돋을새김되어 있다. 어깨 부분은 굴곡진 곡선으로 다듬어졌고, 이음새마다 가는 금빛 테두리가 둘러져 있다. 전체적으로 매끈하게 광이 나며 관절 부위마다 정교한 힌지 구조가 드러나 기사단의 위엄이 느껴지는 디자인이다. 갑옷 전체가 은은한 백색 빛을 머금은 듯 청결하다.',
    type: 'armor',
    slot: 'top',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 6,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 80,
  },
  {
    id: 18,
    name: '상급 회복 물약',
    description: '짙은 붉은빛 액체가 소용돌이치듯 담긴 유리병으로, 병 표면에는 작은 십자 문양이 돋을새김되어 있다. 마개는 금색 금속으로 만들어졌고, 병을 기울이면 액체가 걸쭉하게 흘러내리며 은은한 빛의 잔상을 남긴다. 병목에는 성직자의 문양이 새겨진 작은 태그가 매달려 있어 신성한 축복이 담긴 듯한 정갈한 인상을 준다.',
    type: 'consumable',
    slot: null,
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 40,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 19,
    name: '은빛 반지',
    description: '얇은 은빛 밴드에 작은 보석이 촘촘히 박힌 반지다. 반지 표면을 따라 물결무늬가 새겨져 있고, 보석들은 움직일 때마다 옅은 은빛 잔광을 남긴다. 세공이 매우 정교해 착용자의 민첩함을 상징하듯 가벼운 인상을 주며, 반지 안쪽에는 작은 별자리 문양이 숨겨져 있어 손을 뒤집을 때마다 은밀하게 반짝인다.',
    type: 'armor',
    slot: 'ring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 70,
  },
  {
    id: 20,
    name: '용의 발톱',
    description: '검은 비늘로 뒤덮인 용의 발톱을 그대로 벼려낸 곡도다. 날은 짙은 검붉은빛을 띠며 표면에 미세한 균열무늬가 있어 마치 살아있는 듯한 질감을 준다. 손잡이는 용의 힘줄을 꼬아 만들었고, 칼날 밑동에서 옅은 열기가 아지랑이처럼 피어올라 손에 쥐면 뜨거운 기운이 전해진다. 휘두르면 낮은 포효 같은 진동이 손목을 타고 올라온다.',
    type: 'weapon',
    slot: 'weapon',
    level: 20,
    grade: 'rare',
    strengthBonus: 12,
    attackPowerBonus: 30,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 200,
  },
  {
    id: 21,
    name: '수호자의 방패',
    description: '고대 수호자의 문장이 새겨진 육중한 강철 방패로, 표면은 짙은 청동빛으로 산화되어 있다. 가장자리에는 룬 문자가 원을 그리며 새겨져 있고, 방패 중앙의 보석이 은은한 푸른빛을 내뿜는다. 곳곳에 패인 전투의 흔적이 남아 있어 오랜 세월을 버텨온 위엄이 느껴지며, 들고 있으면 묵직한 안정감이 팔 전체에 퍼진다.',
    type: 'armor',
    slot: 'shield',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 10,
    magicDefenseBonus: 5,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  {
    id: 22,
    name: '엘릭서',
    description: '황금빛으로 일렁이는 액체가 담긴 정교한 유리병으로, 병 자체가 나선형으로 꼬여 있고 마개는 작은 보석으로 장식되어 있다. 액체 속에서 빛의 알갱이들이 끊임없이 소용돌이치며 떠오르고, 병 전체가 손에 쥐면 은은한 온기를 발산해 마치 살아 숨쉬는 듯한 느낌을 준다. 희귀한 재료의 향긋한 잔향이 병 주위를 맴돈다.',
    type: 'consumable',
    slot: null,
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 80,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 23,
    name: '바람의 신발',
    description: '가벼운 은빛 가죽으로 만들어진 신발로, 발등 부분에 작은 날개 문양이 새겨져 있다. 밑창 가장자리를 따라 옅은 청록빛 깃털 무늬가 둘러져 있으며, 신발 전체에서 산들바람이 스치는 듯한 가벼운 잔광이 흩날린다. 신는 순간 발걸음이 한결 가벼워지는 듯한 인상을 주며, 걸을 때마다 옅은 바람 소리가 함께한다.',
    type: 'armor',
    slot: 'shoes',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 160,
  },
  {
    id: 24,
    name: '전설의 대검',
    description: '거대하고 육중한 검신에 고대 문자가 빼곡히 새겨진 전설의 대검이다. 칼날은 짙은 강철빛을 띠며 칼등을 따라 붉은 균열 같은 문양이 맥동하듯 흐른다. 손잡이는 검은 가죽과 금속으로 감싸여 있고, 검을 휘두를 때마다 공기를 가르며 희미한 잔상이 뒤따른다. 세워 놓으면 사람 키를 훌쩍 넘는 압도적인 크기를 자랑한다.',
    type: 'weapon',
    slot: 'weapon',
    level: 35,
    grade: 'legend',
    strengthBonus: 20,
    attackPowerBonus: 50,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 500,
  },
  {
    id: 25,
    name: '드래곤 스케일 갑옷',
    description: '용의 비늘을 이어 붙여 만든 갑옷으로, 표면이 짙은 청록빛으로 번들거린다. 비늘 하나하나가 미세하게 겹쳐져 있어 움직일 때마다 물결치듯 반짝이고, 어깨 부분에는 작은 뿔 장식이 솟아 있다. 가슴팍에는 용의 심장을 상징하는 붉은 보석이 박혀 마치 살아있는 용의 가죽을 두른 듯한 위압감을 준다. 갑옷 전체에서 옅은 열기가 감돈다.',
    type: 'armor',
    slot: 'top',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 15,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 450,
  },
  {
    id: 26,
    name: '천상의 물약',
    description: '하늘빛으로 빛나는 액체가 담긴 크리스털 병으로, 병 표면에 새의 깃털 문양이 정교하게 새겨져 있다. 액체 속에서 작은 빛의 깃털들이 둥둥 떠다니며, 병을 감싼 은빛 사슬 장식이 신성한 기운을 더한다. 병뚜껑을 열면 은은한 향과 함께 빛이 새어 나오며, 주위 공기마저 맑아지는 듯한 청량감을 남긴다.',
    type: 'consumable',
    slot: null,
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 150,
    manaAmount: 0,
    value: 220,
  },
  {
    id: 27,
    name: '불사조 깃털 목걸이',
    description: '불사조의 깃털을 엮어 만든 목걸이로, 깃털 끝이 타오르는 듯한 주황빛으로 물들어 있다. 목걸이 줄은 금빛 실로 짜여 있고, 중앙의 깃털이 은은하게 빛나며 열기를 뿜는 듯한 잔상을 남긴다. 착용자가 움직일 때마다 깃털이 살짝 흔들리며 불티가 흩날리는 듯한 착시를 일으키고, 은은한 온기가 목덜미에 감돈다.',
    type: 'armor',
    slot: 'necklace',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 12,
    healAmount: 0,
    manaAmount: 0,
    value: 400,
  },
  {
    id: 28,
    name: '종말의 검',
    description: '칠흑처럼 검은 칼날에 붉은 균열이 번개처럼 뻗어 있는 거대한 검이다. 칼끝에서 옅은 검은 안개가 스며 나오고, 손잡이에는 해골 모양의 장식이 새겨져 있다. 휘두를 때마다 주변 공기가 일그러지는 듯한 압도적인 존재감을 뿜어내며, 검신 전체에서 낮은 울림이 맴돌아 보는 이를 위축시키는 불길한 기운을 풍긴다.',
    type: 'weapon',
    slot: 'weapon',
    level: 50,
    grade: 'epic',
    strengthBonus: 30,
    attackPowerBonus: 80,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 1200,
  },
  {
    id: 29,
    name: '창세의 방패',
    description: '세상의 시작을 목격했다는 전설의 방패로, 표면에 우주를 닮은 짙은 남색과 별빛 같은 반점이 흩뿌려져 있다. 가장자리는 황금빛으로 둘러져 있고, 중앙에는 거대한 눈 모양 문양이 새겨져 은은한 빛을 내뿜는다. 방패를 들면 주위 공간이 미세하게 일그러지는 듯한 신비로움이 감돌며, 별들이 표면 위를 천천히 흐른다.',
    type: 'armor',
    slot: 'shield',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 20,
    magicDefenseBonus: 15,
    healAmount: 0,
    manaAmount: 0,
    value: 1100,
  },
  {
    id: 30,
    name: '신들의 축복 물약',
    description: '황금빛 액체가 성스러운 광채를 내뿜으며 담긴 화려한 유리병이다. 병 전체가 순금으로 세공된 테두리로 감싸여 있고, 마개에는 작은 날개 장식이 달려 있다. 액체 표면 위로 빛의 입자가 끊임없이 솟아오르며, 병을 든 손끝까지 신성한 온기가 스며드는 듯한 기운을 흩뿌려 주위를 은은한 광채로 물들인다.',
    type: 'consumable',
    slot: null,
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 300,
    manaAmount: 0,
    value: 600,
  },
  {
    id: 31,
    name: '무한의 반지',
    description: '끊임없이 색이 변하는 신비로운 보석이 박힌 반지로, 반지 표면에는 무한을 상징하는 뫼비우스 문양이 새겨져 있다. 착용하면 손끝에서 옅은 빛의 소용돌이가 일렁이며, 보석 속에서 은하수처럼 작은 별들이 흐른다. 우주의 힘이 응축된 듯한 압도적인 존재감을 풍기며, 보는 각도에 따라 빛깔이 끊임없이 변화한다.',
    type: 'armor',
    slot: 'ring',
    level: 50,
    grade: 'epic',
    strengthBonus: 10,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  // --- 중급(mid) 등급 보강: 등급당 10개를 채우기 위한 추가 방어구 ---
  {
    id: 32,
    name: '강철 투구',
    description: '강철판을 둥글게 두드려 만든 투구로, 이마 부분에 가로로 긴 홈이 파여 있다. 표면은 은회색 광택을 띠며 관자놀이 부분에 작은 통풍구가 뚫려 있다. 턱끈은 두꺼운 가죽으로 되어 있고, 정수리 부분에는 짧은 술 장식이 달려 단순하지만 견고한 병사용 투구의 느낌을 준다. 표면에는 실전에서 생긴 작은 찍힘 자국이 남아 있다.',
    type: 'armor',
    slot: 'hat',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 25,
  },
  {
    id: 33,
    name: '흑요석 귀걸이',
    description: '매끈하게 연마된 검은 흑요석 조각이 매달린 귀걸이다. 표면은 유리처럼 광택이 흐르며 빛을 받으면 자주빛으로 은은하게 반사된다. 걸이 부분은 가는 은사로 만들어져 있어 검은 보석과 대비되는 우아함을 더하고, 조각 안쪽에는 미세한 기포 무늬가 비쳐 보인다. 어두운 조명 아래서도 은은한 존재감을 드러낸다.',
    type: 'armor',
    slot: 'earring',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 22,
  },
  {
    id: 34,
    name: '마력 목걸이',
    description: '은사슬에 옅은 보랏빛으로 빛나는 마력석이 매달린 목걸이다. 돌 표면에는 소용돌이 형태의 룬이 새겨져 있고, 목걸이를 착용하면 돌 주위로 희미한 안개 같은 마력이 피어오른다. 세공이 정교해 마법사들이 선호할 법한 절제된 디자인을 지녔으며, 사슬 마디마다 옅은 보랏빛 잔광이 스며 있다.',
    type: 'armor',
    slot: 'necklace',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 28,
  },
  {
    id: 35,
    name: '강철 각반',
    description: '정강이를 감싸는 강철판 각반으로, 무릎 부분에 둥근 보호대가 덧대어져 있다. 표면은 은회색으로 빛나며 이음새마다 작은 리벳이 촘촘히 박혀 있다. 다리 옆면에는 세로로 긴 홈이 파여 있어 움직임을 방해하지 않는 실용적인 구조가 돋보이며, 정강이뼈를 따라 매끄러운 곡선을 그린다.',
    type: 'armor',
    slot: 'bottom',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  {
    id: 36,
    name: '강철 장갑',
    description: '손등을 덮는 강철 장갑으로, 손가락 마디마다 얇은 금속판이 겹겹이 이어져 있다. 손목 부분은 가죽 끈으로 조이게 되어 있으며, 표면은 은회색 광택을 띤다. 주먹을 쥐면 금속판들이 자연스럽게 맞물리며 접히는 정교한 관절 구조가 돋보이며, 손끝까지 세밀하게 마감되어 있다.',
    type: 'armor',
    slot: 'gloves',
    level: 5,
    grade: 'mid',
    strengthBonus: 2,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 24,
  },
  {
    id: 37,
    name: '은빛 부츠',
    description: '은빛으로 반짝이는 가죽 부츠로, 발목 부분에 가는 금속 버클이 달려 있다. 밑창 가장자리를 따라 옅은 은색 실선이 둘러져 있고, 걸을 때마다 희미한 은빛 잔광이 발자국을 따라 남는다. 앞코 부분이 살짝 뾰족하게 마감되어 가볍고 날렵한 인상을 주며, 전체적으로 매끈한 은빛 윤기가 흐른다.',
    type: 'armor',
    slot: 'shoes',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  // --- 상급(high) 등급 보강 ---
  {
    id: 38,
    name: '기사의 방패',
    description: '왕실 기사단의 문장이 새겨진 정교한 강철 방패로, 표면은 은빛으로 매끄럽게 광이 난다. 가장자리를 따라 가는 금빛 테두리가 둘러져 있고, 중앙의 문장 부분은 살짝 돋을새김되어 있어 빛을 받으면 입체적으로 도드라진다. 뒷면에는 팔뚝 전체를 감싸는 가죽 벨트가 달려 있어 견고한 착용감을 더한다.',
    type: 'armor',
    slot: 'shield',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 75,
  },
  {
    id: 39,
    name: '기사의 투구',
    description: '왕실 기사단이 착용하던 투구로, 이마 부분에 작은 깃털 장식이 달려 있다. 표면은 은빛으로 매끄럽게 다듬어졌고, 얼굴을 가리는 부분에는 가는 창살무늬가 새겨져 있다. 정수리에서 뒷목까지 이어지는 곡선이 유려하며, 절제되고 기품 있는 디자인이 돋보이는 지휘관급 장비다.',
    type: 'armor',
    slot: 'hat',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 5,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 65,
  },
  {
    id: 40,
    name: '사파이어 귀걸이',
    description: '짙은 푸른빛 사파이어가 박힌 귀걸이로, 보석 주위를 은사가 섬세하게 감싸고 있다. 보석 표면은 매끄럽게 연마되어 빛을 받으면 깊은 청색 광채를 내뿜는다. 걸이 부분에는 작은 별 모양 장식이 함께 달려 있어 걸을 때마다 은은하게 반짝이며, 보석 속에서 옅은 빛줄기가 소용돌이친다.',
    type: 'armor',
    slot: 'earring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 5,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  {
    id: 41,
    name: '마법사의 목걸이',
    description: '은사슬에 옅은 남색 마법석이 매달린 목걸이로, 돌 표면에 정교한 마법진이 새겨져 있다. 착용하면 돌 주위로 옅은 마력의 빛이 원을 그리며 감돌고, 목걸이 줄은 가늘고 촘촘하게 엮여 우아한 느낌을 준다. 돌 안쪽에서 별자리처럼 작은 빛 점이 반짝이며 은은한 지성의 기운을 드러낸다.',
    type: 'armor',
    slot: 'necklace',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 7,
    healAmount: 0,
    manaAmount: 0,
    value: 68,
  },
  {
    id: 42,
    name: '기사의 각반',
    description: '왕실 기사단이 착용하던 견고한 각반으로, 무릎과 정강이 부분이 이중 강철판으로 보강되어 있다. 표면은 은빛으로 광이 나며 가장자리에 가는 금빛 선이 둘러져 있다. 다리 움직임에 맞춰 유연하게 접히는 관절부가 특징이며 발목 부분은 가죽으로 마감되어 있어 기품과 실용성을 동시에 갖췄다.',
    type: 'armor',
    slot: 'bottom',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 62,
  },
  {
    id: 43,
    name: '사냥꾼의 장갑',
    description: '가벼운 갈색 가죽에 강철 조각을 덧댄 사냥꾼용 장갑이다. 손가락 끝부분은 활시위를 다루기 쉽도록 얇게 재단되어 있고, 손등에는 작은 매 문양이 새겨져 있다. 손목 부분은 끈으로 조이게 되어 있으며 전체적으로 실용성과 민첩함을 강조한 디자인이다. 손바닥 부분은 미끄럼 방지 가공이 되어 있다.',
    type: 'armor',
    slot: 'gloves',
    level: 10,
    grade: 'high',
    strengthBonus: 4,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  // --- 레어(rare) 등급 보강 ---
  {
    id: 44,
    name: '용비늘 투구',
    description: '용의 비늘 조각을 이어 붙여 만든 투구로, 이마 부분에 작은 뿔 장식이 솟아 있다. 표면은 짙은 초록빛으로 광택이 흐르며 비늘 무늬가 그대로 살아 있어 마치 용의 머리를 형상화한 듯한 위압감을 준다. 눈가리개 부분에는 가는 틈이 뚫려 있으며, 빛을 받으면 비늘 하나하나가 미세하게 반짝인다.',
    type: 'armor',
    slot: 'hat',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 9,
    magicDefenseBonus: 4,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 45,
    name: '심연의 귀걸이',
    description: '칠흑같이 검은 보석이 매달린 귀걸이로, 보석 표면에서 옅은 보랏빛 안개가 스며 나온다. 걸이 부분은 어두운 금속으로 만들어져 있으며, 보석 안쪽에서 소용돌이치는 듯한 문양이 은은하게 비쳐 보인다. 착용하면 서늘한 기운이 귓가에 감도는 듯하며, 어둠 속에서도 은은히 존재를 드러낸다.',
    type: 'armor',
    slot: 'earring',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 46,
    name: '대현자의 목걸이',
    description: '은사슬에 커다란 지혜의 보석이 매달린 목걸이로, 보석 표면에 고대 문자가 촘촘히 새겨져 있다. 보석 안쪽에서 옅은 남색 빛이 맥동하듯 일렁이며, 목걸이를 착용하면 사색에 잠긴 듯한 신비로운 기운이 감돈다. 줄은 두 겹으로 꼬아 만들어져 있으며 보석의 무게감이 손끝에 묵직하게 전해진다.',
    type: 'armor',
    slot: 'necklace',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 14,
    healAmount: 0,
    manaAmount: 0,
    value: 170,
  },
  {
    id: 47,
    name: '수호자의 갑옷',
    description: '고대 수호자가 두르던 갑옷으로, 표면이 짙은 청동빛으로 산화되어 있다. 가슴판에는 커다란 방패 문양이 돋을새김되어 있고, 이음새마다 룬 문자가 새겨져 있다. 어깨와 팔꿈치 부분은 두툼하게 보강되어 있어 오랜 세월을 견뎌온 묵직하고 위엄 있는 존재감을 풍기며, 표면 곳곳에 청록빛 녹이 배어 있다.',
    type: 'armor',
    slot: 'top',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 12,
    magicDefenseBonus: 6,
    healAmount: 0,
    manaAmount: 0,
    value: 190,
  },
  {
    id: 48,
    name: '수호자의 각반',
    description: '고대 수호자가 두르던 각반으로, 정강이 부분에 두꺼운 청동빛 강판이 덧대어져 있다. 표면에는 방어의 룬 문자가 새겨져 있고, 무릎 보호대 부분이 둥글게 돌출되어 있다. 발목 이음새는 촘촘한 사슬로 마감되어 튼튼하고 신뢰감 있는 인상을 주며, 오랜 풍파를 겪은 듯한 짙은 색조를 띤다.',
    type: 'armor',
    slot: 'bottom',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 49,
    name: '폭풍의 반지',
    description: '짙은 회색 구름무늬가 소용돌이치는 반지로, 표면에서 작은 번개 문양이 번쩍인다. 반지를 착용하면 손끝에서 미세한 정전기 같은 빛이 튀며, 반지 안쪽 테두리를 따라 가는 전류 문양이 흐른다. 폭풍의 힘이 응축된 듯한 역동적인 존재감을 풍기며, 낮게 우르릉거리는 소리가 희미하게 들리는 듯하다.',
    type: 'armor',
    slot: 'ring',
    level: 20,
    grade: 'rare',
    strengthBonus: 6,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  // --- 레전드(legend) 등급 보강 ---
  {
    id: 50,
    name: '용의 방패',
    description: '용의 뼈와 비늘을 엮어 만든 거대한 방패로, 표면이 짙은 청록빛 비늘무늬로 뒤덮여 있다. 방패 가장자리에는 날카로운 뼈 조각이 돌출되어 있고, 중앙에는 용의 눈을 형상화한 붉은 보석이 박혀 있다. 들고 있으면 낮게 울리는 용의 숨결 같은 기운이 느껴지며, 표면 전체가 살아있는 것처럼 미세하게 맥동한다.',
    type: 'armor',
    slot: 'shield',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 420,
  },
  {
    id: 51,
    name: '용의 투구',
    description: '용의 머리뼈를 본떠 만든 투구로, 양옆에 날카로운 뿔이 솟아 있다. 표면은 짙은 청록빛 비늘로 뒤덮여 있고, 눈구멍 부분에서 옅은 붉은 빛이 새어 나온다. 턱뼈 형상의 장식이 관자놀이까지 이어져 있어 착용자를 마치 용처럼 보이게 하는 위압적인 디자인이며, 뿔 끝은 날카롭게 벼려져 있다.',
    type: 'armor',
    slot: 'hat',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 16,
    magicDefenseBonus: 8,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 52,
    name: '별빛 귀걸이',
    description: '밤하늘의 별빛을 담은 귀걸이로, 투명한 보석 속에 작은 별가루가 흩뿌려진 듯한 무늬가 떠 있다. 걸이 부분은 은백색 금속으로 섬세하게 세공되어 있으며, 움직일 때마다 반짝이는 잔광이 흩날린다. 보석 중심에서 옅은 빛줄기가 별똥별처럼 흘러내리며, 밤하늘 아래서 유독 신비롭게 빛난다.',
    type: 'armor',
    slot: 'earring',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 360,
  },
  {
    id: 53,
    name: '용의 각반',
    description: '용의 가죽으로 만든 튼튼한 각반으로, 표면에 짙은 비늘 무늬가 도드라져 있다. 무릎 부분에는 작은 발톱 장식이 달려 있고, 다리 옆선을 따라 옅은 붉은 줄무늬가 맥동하듯 흐른다. 강인하면서도 유연한 움직임을 보장하는 관절 구조를 지녔으며, 만지면 뜨거운 체온이 느껴지는 듯하다.',
    type: 'armor',
    slot: 'bottom',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 14,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 54,
    name: '용의 장갑',
    description: '용의 발톱을 엮어 만든 장갑으로, 손가락 끝에 날카로운 발톱 모양 장식이 달려 있다. 손등은 짙은 비늘무늬 가죽으로 덮여 있으며, 주먹을 쥐면 발톱들이 맞물리듯 정렬되어 위협적인 실루엣을 만든다. 손목 부분에는 붉은 힘줄 문양이 새겨져 있어 마치 살아있는 짐승의 손을 낀 듯한 인상을 준다.',
    type: 'armor',
    slot: 'gloves',
    level: 35,
    grade: 'legend',
    strengthBonus: 14,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 370,
  },
  {
    id: 55,
    name: '질풍의 신발',
    description: '바람보다 빠르다는 전설의 신발로, 발목 부분에 깃털 같은 은빛 장식이 넓게 펼쳐져 있다. 밑창은 거의 투명에 가까운 소재로 만들어졌고, 걸을 때마다 옅은 바람의 잔상이 소용돌이치며 뒤따른다. 뒤꿈치에는 작은 날개 모양 장식이 달려 있으며, 신는 순간 몸이 깃털처럼 가벼워지는 듯하다.',
    type: 'armor',
    slot: 'shoes',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 390,
  },
  // --- 에픽(epic) 등급 보강 ---
  {
    id: 56,
    name: '창세의 투구',
    description: '세상이 창조될 때부터 존재했다는 투구로, 표면에 우주의 별자리를 닮은 무늬가 새겨져 있다. 이마 부분에는 황금빛 뿔이 솟아 있고, 눈구멍에서 은은한 백색 빛이 새어 나온다. 정수리를 따라 흐르는 문양이 은하수처럼 반짝이며 신성하고 압도적인 존재감을 풍기고, 착용자 주위로 옅은 빛무리가 감돈다.',
    type: 'armor',
    slot: 'hat',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 25,
    magicDefenseBonus: 18,
    healAmount: 0,
    manaAmount: 0,
    value: 950,
  },
  {
    id: 57,
    name: '태초의 귀걸이',
    description: '태초의 힘이 깃든 귀걸이로, 투명한 보석 속에서 작은 은하가 소용돌이치듯 빛난다. 걸이 부분은 순금으로 세공되어 있으며, 보석 주위로 옅은 빛의 파동이 끊임없이 퍼져나간다. 가까이 다가서면 시공이 일렁이는 듯한 신비롭고 압도적인 존재감을 풍기며, 태초의 정적을 담은 듯 고요히 빛난다.',
    type: 'armor',
    slot: 'earring',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 22,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 58,
    name: '영원의 목걸이',
    description: '영원히 빛바래지 않는다는 목걸이로, 중앙의 보석이 무지갯빛으로 끊임없이 일렁인다. 목걸이 줄은 순금과 은이 교차하며 엮여 있고, 보석 표면에는 시간을 상징하는 나선 문양이 새겨져 있다. 보석 속 빛이 과거와 미래를 넘나들 듯 천천히 흐르며 시대를 초월한 신비로움을 자아내고, 착용자의 숨결에 맞춰 은은히 맥동한다.',
    type: 'armor',
    slot: 'necklace',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 28,
    healAmount: 0,
    manaAmount: 0,
    value: 980,
  },
  {
    id: 59,
    name: '창세의 갑옷',
    description: '세상이 창조될 때부터 존재했다는 갑옷으로, 표면 전체에 별자리와 은하수 같은 무늬가 흐른다. 가슴판 중앙에는 거대한 황금빛 문장이 새겨져 있고, 갑옷 전체에서 은은한 백색 광채가 뿜어져 나온다. 어깨와 팔 관절마다 정교한 별무늬 장식이 이어져 압도적인 존재감을 드러내며, 갑옷 자락이 별빛처럼 흩날린다.',
    type: 'armor',
    slot: 'top',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 30,
    magicDefenseBonus: 22,
    healAmount: 0,
    manaAmount: 0,
    value: 1150,
  },
  {
    id: 60,
    name: '창세의 각반',
    description: '세상이 창조될 때부터 존재했다는 각반으로, 표면에 별빛처럼 반짝이는 미세한 입자들이 흩뿌려져 있다. 무릎 보호대 부분에는 황금빛 문양이 돋을새김되어 있고, 움직일 때마다 옅은 빛의 잔상이 발걸음을 따라온다. 발목 부분은 은하수처럼 흐르는 무늬로 마감되어 있으며, 걸을 때마다 별가루가 흩날리는 듯하다.',
    type: 'armor',
    slot: 'bottom',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 920,
  },
  {
    id: 61,
    name: '파멸의 장갑',
    description: '닿는 모든 것을 파멸로 이끈다는 장갑으로, 손등 전체가 검붉은 균열무늬로 뒤덮여 있다. 손가락 끝에서는 옅은 검은 안개가 스며 나오고, 주먹을 쥘 때마다 균열 사이로 붉은 빛이 번쩍인다. 손목 부분에는 파멸을 상징하는 뒤틀린 문양이 새겨져 압도적이고 불길한 존재감을 풍기며, 가까이 다가서면 뼈가 시릴 듯한 냉기가 감돈다.',
    type: 'armor',
    slot: 'gloves',
    level: 50,
    grade: 'epic',
    strengthBonus: 22,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 62,
    name: '낡은 지팡이',
    description: '옹이가 그대로 남은 나뭇가지를 다듬어 만든 투박한 지팡이로, 끝부분에 작고 흐릿한 수정 조각이 실로 동여매어 있다. 표면에는 얕은 흠집이 여러 군데 나 있고, 손잡이 부분은 오래 쥐어 반들반들해졌다. 수정에 마력을 흘려보내면 미약하게나마 옅은 빛이 깜빡이는, 초보 마법사용 지팡이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 4,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 63,
    name: '강철 테 지팡이',
    description: '매끄러운 목재 지팡이 끝을 은회색 강철 테가 감싸고 있으며, 그 안에 맑은 푸른 수정이 단단히 고정되어 있다. 강철 테에는 가는 덩굴무늬가 새겨져 있어 마력이 흐를 때마다 옅게 반짝인다. 낡은 지팡이보다 마력을 훨씬 안정적으로 모아 전달해준다.',
    type: 'weapon',
    slot: 'weapon',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 10,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 40,
  },
  {
    id: 64,
    name: '미스릴 지팡이',
    description: '은백색 미스릴로 뽑아낸 가늘고 우아한 지팡이로, 끝에는 투명에 가까운 수정이 무지갯빛을 은은히 반사하며 박혀 있다. 손에 쥐면 놀랍도록 가벼우면서도 마력이 손끝까지 선명하게 전해지는 감각이 느껴진다.',
    type: 'weapon',
    slot: 'weapon',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 18,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 65,
    name: '용의 지팡이',
    description: '용의 척추 뼈를 깎아 만든 지팡이로, 끝에 박힌 검붉은 수정에서 옅은 열기가 아지랑이처럼 피어오른다. 표면의 비늘 무늬 사이로 낮은 진동이 전해지며, 마력을 담을 때마다 낮은 포효 같은 울림이 손목을 타고 올라온다.',
    type: 'weapon',
    slot: 'weapon',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 30,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 200,
  },
  {
    id: 66,
    name: '전설의 대마도 지팡이',
    description: '고대 문자가 빼곡히 새겨진 거대한 지팡이로, 머리 부분에 박힌 짙은 자수정이 맥동하듯 붉은 균열무늬 빛을 뿜어낸다. 지팡이를 세워 놓으면 사람 키를 훌쩍 넘는 압도적인 크기를 자랑하며, 휘두를 때마다 공기가 마력으로 일렁인다.',
    type: 'weapon',
    slot: 'weapon',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 50,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 500,
  },
  {
    id: 67,
    name: '종말의 지팡이',
    description: '칠흑처럼 검은 지팡이에 붉은 균열이 번개처럼 뻗어 있으며, 머리에 박힌 수정에서 검은 안개가 스며 나온다. 마력을 담을 때마다 주변 공기가 일그러지는 듯한 압도적인 존재감을 뿜어내고, 낮은 울림이 맴돌아 보는 이를 위축시키는 불길한 기운을 풍긴다.',
    type: 'weapon',
    slot: 'weapon',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 80,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 1200,
  },
];

const ROOM_ITEMS: RoomItemSeed[] = [
  { roomId: 3, itemId: 1, quantity: 1 },
  { roomId: 4, itemId: 2, quantity: 1 },
  { roomId: 2, itemId: 3, quantity: 2 },
  { roomId: 4, itemId: 4, quantity: 1 },
  { roomId: 4, itemId: 5, quantity: 1 },
  { roomId: 4, itemId: 6, quantity: 1 },
  { roomId: 4, itemId: 7, quantity: 1 },
  { roomId: 4, itemId: 8, quantity: 1 },
  { roomId: 4, itemId: 9, quantity: 1 },
  { roomId: 4, itemId: 10, quantity: 1 },
  { roomId: 4, itemId: 11, quantity: 1 },
];

const MOB_TEMPLATES: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 8,
    strength: 2,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 15,
    strength: 4,
    dexterity: 2,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    goldReward: 5,
    level: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 10,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    goldReward: 2,
    level: 1,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 5,
    strength: 5,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 14,
    strength: 1,
    dexterity: 1,
    physicalDefense: 2,
    magicDefense: 1,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 7,
    strength: 4,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 12,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 8,
    name: '덩굴괴수',
    hp: 42,
    strength: 9,
    dexterity: 4,
    physicalDefense: 6,
    magicDefense: 2,
    element: 'wood',
    damageType: 'physical',
    expReward: 18,
    goldReward: 8,
    level: 5,
  },
  {
    id: 9,
    name: '불도마뱀',
    hp: 19,
    strength: 21,
    dexterity: 6,
    physicalDefense: 1,
    magicDefense: 2,
    element: 'fire',
    damageType: 'magic',
    expReward: 14,
    goldReward: 8,
    level: 5,
  },
  {
    id: 10,
    name: '바위골렘',
    hp: 60,
    strength: 5,
    dexterity: 4,
    physicalDefense: 7,
    magicDefense: 3,
    element: 'earth',
    damageType: 'physical',
    expReward: 22,
    goldReward: 8,
    level: 5,
  },
  {
    id: 11,
    name: '강철전갈',
    hp: 29,
    strength: 15,
    dexterity: 5,
    physicalDefense: 5,
    magicDefense: 2,
    element: 'metal',
    damageType: 'physical',
    expReward: 17,
    goldReward: 8,
    level: 5,
  },
  {
    id: 12,
    name: '늪지악어',
    hp: 48,
    strength: 10,
    dexterity: 5,
    physicalDefense: 6,
    magicDefense: 1,
    element: 'water',
    damageType: 'physical',
    expReward: 19,
    goldReward: 8,
    level: 5,
  },
  {
    id: 13,
    name: '덩굴괴수',
    hp: 81,
    strength: 17,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 5,
    element: 'wood',
    damageType: 'physical',
    expReward: 36,
    goldReward: 16,
    level: 10,
  },
  {
    id: 14,
    name: '불도마뱀',
    hp: 37,
    strength: 42,
    dexterity: 12,
    physicalDefense: 2,
    magicDefense: 5,
    element: 'fire',
    damageType: 'magic',
    expReward: 30,
    goldReward: 16,
    level: 10,
  },
  {
    id: 15,
    name: '바위골렘',
    hp: 117,
    strength: 10,
    dexterity: 8,
    physicalDefense: 13,
    magicDefense: 6,
    element: 'earth',
    damageType: 'physical',
    expReward: 43,
    goldReward: 16,
    level: 10,
  },
  {
    id: 16,
    name: '강철전갈',
    hp: 57,
    strength: 29,
    dexterity: 10,
    physicalDefense: 9,
    magicDefense: 3,
    element: 'metal',
    damageType: 'physical',
    expReward: 33,
    goldReward: 16,
    level: 10,
  },
  {
    id: 17,
    name: '늪지악어',
    hp: 94,
    strength: 19,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 3,
    element: 'water',
    damageType: 'physical',
    expReward: 38,
    goldReward: 16,
    level: 10,
  },
  {
    id: 18,
    name: '덩굴괴수',
    hp: 121,
    strength: 26,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 7,
    element: 'wood',
    damageType: 'physical',
    expReward: 55,
    goldReward: 24,
    level: 15,
  },
  {
    id: 19,
    name: '불도마뱀',
    hp: 55,
    strength: 62,
    dexterity: 18,
    physicalDefense: 3,
    magicDefense: 7,
    element: 'fire',
    damageType: 'magic',
    expReward: 45,
    goldReward: 24,
    level: 15,
  },
  {
    id: 20,
    name: '바위골렘',
    hp: 174,
    strength: 14,
    dexterity: 11,
    physicalDefense: 20,
    magicDefense: 9,
    element: 'earth',
    damageType: 'physical',
    expReward: 65,
    goldReward: 24,
    level: 15,
  },
  {
    id: 21,
    name: '강철전갈',
    hp: 85,
    strength: 44,
    dexterity: 16,
    physicalDefense: 13,
    magicDefense: 4,
    element: 'metal',
    damageType: 'physical',
    expReward: 49,
    goldReward: 24,
    level: 15,
  },
  {
    id: 22,
    name: '늪지악어',
    hp: 140,
    strength: 28,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 4,
    element: 'water',
    damageType: 'physical',
    expReward: 57,
    goldReward: 24,
    level: 15,
  },
  {
    id: 23,
    name: '덩굴괴수',
    hp: 160,
    strength: 34,
    dexterity: 17,
    physicalDefense: 22,
    magicDefense: 10,
    element: 'wood',
    damageType: 'physical',
    expReward: 73,
    goldReward: 32,
    level: 20,
  },
  {
    id: 24,
    name: '불도마뱀',
    hp: 73,
    strength: 82,
    dexterity: 24,
    physicalDefense: 4,
    magicDefense: 10,
    element: 'fire',
    damageType: 'magic',
    expReward: 60,
    goldReward: 32,
    level: 20,
  },
  {
    id: 25,
    name: '바위골렘',
    hp: 232,
    strength: 19,
    dexterity: 15,
    physicalDefense: 27,
    magicDefense: 11,
    element: 'earth',
    damageType: 'physical',
    expReward: 87,
    goldReward: 32,
    level: 20,
  },
  {
    id: 26,
    name: '강철전갈',
    hp: 113,
    strength: 58,
    dexterity: 21,
    physicalDefense: 18,
    magicDefense: 6,
    element: 'metal',
    damageType: 'physical',
    expReward: 67,
    goldReward: 32,
    level: 20,
  },
  {
    id: 27,
    name: '늪지악어',
    hp: 186,
    strength: 37,
    dexterity: 18,
    physicalDefense: 22,
    magicDefense: 6,
    element: 'water',
    damageType: 'physical',
    expReward: 77,
    goldReward: 32,
    level: 20,
  },
  {
    id: 28,
    name: '덩굴괴수',
    hp: 200,
    strength: 43,
    dexterity: 21,
    physicalDefense: 28,
    magicDefense: 12,
    element: 'wood',
    damageType: 'physical',
    expReward: 92,
    goldReward: 40,
    level: 25,
  },
  {
    id: 29,
    name: '불도마뱀',
    hp: 91,
    strength: 102,
    dexterity: 30,
    physicalDefense: 5,
    magicDefense: 12,
    element: 'fire',
    damageType: 'magic',
    expReward: 75,
    goldReward: 40,
    level: 25,
  },
  {
    id: 30,
    name: '바위골렘',
    hp: 289,
    strength: 24,
    dexterity: 19,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'earth',
    damageType: 'physical',
    expReward: 108,
    goldReward: 40,
    level: 25,
  },
  {
    id: 31,
    name: '강철전갈',
    hp: 141,
    strength: 72,
    dexterity: 26,
    physicalDefense: 22,
    magicDefense: 7,
    element: 'metal',
    damageType: 'physical',
    expReward: 83,
    goldReward: 40,
    level: 25,
  },
  {
    id: 32,
    name: '늪지악어',
    hp: 232,
    strength: 46,
    dexterity: 22,
    physicalDefense: 28,
    magicDefense: 7,
    element: 'water',
    damageType: 'physical',
    expReward: 96,
    goldReward: 40,
    level: 25,
  },
  {
    id: 33,
    name: '덩굴괴수',
    hp: 240,
    strength: 51,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'wood',
    damageType: 'physical',
    expReward: 110,
    goldReward: 48,
    level: 30,
  },
  {
    id: 34,
    name: '불도마뱀',
    hp: 109,
    strength: 123,
    dexterity: 36,
    physicalDefense: 6,
    magicDefense: 14,
    element: 'fire',
    damageType: 'magic',
    expReward: 90,
    goldReward: 48,
    level: 30,
  },
  {
    id: 35,
    name: '바위골렘',
    hp: 346,
    strength: 28,
    dexterity: 22,
    physicalDefense: 40,
    magicDefense: 17,
    element: 'earth',
    damageType: 'physical',
    expReward: 130,
    goldReward: 48,
    level: 30,
  },
  {
    id: 36,
    name: '강철전갈',
    hp: 169,
    strength: 87,
    dexterity: 31,
    physicalDefense: 27,
    magicDefense: 9,
    element: 'metal',
    damageType: 'physical',
    expReward: 101,
    goldReward: 48,
    level: 30,
  },
  {
    id: 37,
    name: '늪지악어',
    hp: 278,
    strength: 56,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 8,
    element: 'water',
    damageType: 'physical',
    expReward: 114,
    goldReward: 48,
    level: 30,
  },
  {
    id: 38,
    name: '덩굴괴수',
    hp: 279,
    strength: 60,
    dexterity: 30,
    physicalDefense: 39,
    magicDefense: 17,
    element: 'wood',
    damageType: 'physical',
    expReward: 129,
    goldReward: 56,
    level: 35,
  },
  {
    id: 39,
    name: '불도마뱀',
    hp: 127,
    strength: 143,
    dexterity: 42,
    physicalDefense: 7,
    magicDefense: 17,
    element: 'fire',
    damageType: 'magic',
    expReward: 105,
    goldReward: 56,
    level: 35,
  },
  {
    id: 40,
    name: '바위골렘',
    hp: 403,
    strength: 33,
    dexterity: 26,
    physicalDefense: 46,
    magicDefense: 20,
    element: 'earth',
    damageType: 'physical',
    expReward: 152,
    goldReward: 56,
    level: 35,
  },
  {
    id: 41,
    name: '강철전갈',
    hp: 197,
    strength: 101,
    dexterity: 36,
    physicalDefense: 31,
    magicDefense: 10,
    element: 'metal',
    damageType: 'physical',
    expReward: 116,
    goldReward: 56,
    level: 35,
  },
  {
    id: 42,
    name: '늪지악어',
    hp: 324,
    strength: 65,
    dexterity: 31,
    physicalDefense: 39,
    magicDefense: 10,
    element: 'water',
    damageType: 'physical',
    expReward: 134,
    goldReward: 56,
    level: 35,
  },
  {
    id: 43,
    name: '덩굴괴수',
    hp: 319,
    strength: 68,
    dexterity: 34,
    physicalDefense: 44,
    magicDefense: 19,
    element: 'wood',
    damageType: 'physical',
    expReward: 146,
    goldReward: 64,
    level: 40,
  },
  {
    id: 44,
    name: '불도마뱀',
    hp: 145,
    strength: 163,
    dexterity: 48,
    physicalDefense: 8,
    magicDefense: 19,
    element: 'fire',
    damageType: 'magic',
    expReward: 120,
    goldReward: 64,
    level: 40,
  },
  {
    id: 45,
    name: '바위골렘',
    hp: 460,
    strength: 38,
    dexterity: 30,
    physicalDefense: 53,
    magicDefense: 23,
    element: 'earth',
    damageType: 'physical',
    expReward: 174,
    goldReward: 64,
    level: 40,
  },
  {
    id: 46,
    name: '강철전갈',
    hp: 225,
    strength: 115,
    dexterity: 41,
    physicalDefense: 35,
    magicDefense: 12,
    element: 'metal',
    damageType: 'physical',
    expReward: 133,
    goldReward: 64,
    level: 40,
  },
  {
    id: 47,
    name: '늪지악어',
    hp: 370,
    strength: 74,
    dexterity: 35,
    physicalDefense: 44,
    magicDefense: 11,
    element: 'water',
    damageType: 'physical',
    expReward: 153,
    goldReward: 64,
    level: 40,
  },
  {
    id: 48,
    name: '덩굴괴수',
    hp: 358,
    strength: 77,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 21,
    element: 'wood',
    damageType: 'physical',
    expReward: 165,
    goldReward: 72,
    level: 45,
  },
  {
    id: 49,
    name: '불도마뱀',
    hp: 163,
    strength: 183,
    dexterity: 54,
    physicalDefense: 9,
    magicDefense: 21,
    element: 'fire',
    damageType: 'magic',
    expReward: 134,
    goldReward: 72,
    level: 45,
  },
  {
    id: 50,
    name: '바위골렘',
    hp: 518,
    strength: 42,
    dexterity: 33,
    physicalDefense: 59,
    magicDefense: 25,
    element: 'earth',
    damageType: 'physical',
    expReward: 194,
    goldReward: 72,
    level: 45,
  },
  {
    id: 51,
    name: '강철전갈',
    hp: 253,
    strength: 129,
    dexterity: 46,
    physicalDefense: 40,
    magicDefense: 13,
    element: 'metal',
    damageType: 'physical',
    expReward: 150,
    goldReward: 72,
    level: 45,
  },
  {
    id: 52,
    name: '늪지악어',
    hp: 416,
    strength: 83,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 12,
    element: 'water',
    damageType: 'physical',
    expReward: 172,
    goldReward: 72,
    level: 45,
  },
  {
    id: 53,
    name: '덩굴괴수',
    hp: 398,
    strength: 85,
    dexterity: 43,
    physicalDefense: 55,
    magicDefense: 24,
    element: 'wood',
    damageType: 'physical',
    expReward: 183,
    goldReward: 80,
    level: 50,
  },
  {
    id: 54,
    name: '불도마뱀',
    hp: 181,
    strength: 204,
    dexterity: 61,
    physicalDefense: 10,
    magicDefense: 24,
    element: 'fire',
    damageType: 'magic',
    expReward: 150,
    goldReward: 80,
    level: 50,
  },
  {
    id: 55,
    name: '바위골렘',
    hp: 575,
    strength: 47,
    dexterity: 37,
    physicalDefense: 66,
    magicDefense: 28,
    element: 'earth',
    damageType: 'physical',
    expReward: 217,
    goldReward: 80,
    level: 50,
  },
  {
    id: 56,
    name: '강철전갈',
    hp: 281,
    strength: 144,
    dexterity: 52,
    physicalDefense: 44,
    magicDefense: 15,
    element: 'metal',
    damageType: 'physical',
    expReward: 167,
    goldReward: 80,
    level: 50,
  },
  {
    id: 57,
    name: '늪지악어',
    hp: 462,
    strength: 92,
    dexterity: 44,
    physicalDefense: 55,
    magicDefense: 14,
    element: 'water',
    damageType: 'physical',
    expReward: 191,
    goldReward: 80,
    level: 50,
  },
];

const MOB_SPAWNS: MobSpawnSeed[] = [
  { roomId: 6, mobTemplateId: 1, respawnSeconds: 20 },
  { roomId: 7, mobTemplateId: 2, respawnSeconds: 30 },
  { roomId: 9, mobTemplateId: 1, respawnSeconds: 20 },
];

export function seed(db: Database.Database): void {
  const existing = db.prepare('SELECT id FROM rooms WHERE id = ?').get(STARTING_ROOM_ID);
  if (existing) return;

  const insertRoom = db.prepare('INSERT INTO rooms (id, name, description) VALUES (?, ?, ?)');
  const insertExit = db.prepare(
    'INSERT INTO room_exits (room_id, direction, target_room_id) VALUES (?, ?, ?)',
  );
  const insertItem = db.prepare(
    `INSERT INTO items (id, name, description, type, slot, level, grade, strength_bonus, dexterity_bonus, attack_power_bonus, intelligence_bonus, physical_defense_bonus, magic_defense_bonus, heal_amount, mana_amount, value)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  );
  const insertRoomItem = db.prepare(
    'INSERT INTO room_items (room_id, item_id, quantity) VALUES (?, ?, ?)',
  );
  const insertMobTemplate = db.prepare(
    `INSERT INTO mob_templates (id, name, hp, strength, dexterity, physical_defense, magic_defense, element, damage_type, exp_reward, gold_reward, level)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  );
  const insertMobSpawn = db.prepare(
    'INSERT INTO mob_spawns (room_id, mob_template_id, respawn_seconds) VALUES (?, ?, ?)',
  );
  const insertAdminAccount = db.prepare(
    'INSERT INTO accounts (username, password_hash, is_builder, is_admin) VALUES (?, ?, 1, 1)',
  );

  const seedTx = db.transaction(() => {
    insertAdminAccount.run(DEFAULT_ADMIN_USERNAME, bcrypt.hashSync(DEFAULT_ADMIN_PASSWORD, SALT_ROUNDS));
    for (const room of ROOMS) insertRoom.run(room.id, room.name, room.description);
    for (const exit of EXITS) insertExit.run(exit.roomId, exit.direction, exit.targetRoomId);
    for (const item of ITEMS) {
      insertItem.run(
        item.id,
        item.name,
        item.description,
        item.type,
        item.slot,
        item.level,
        item.grade,
        item.strengthBonus,
        item.dexterityBonus,
        item.attackPowerBonus,
        item.intelligenceBonus,
        item.physicalDefenseBonus,
        item.magicDefenseBonus,
        item.healAmount,
        item.manaAmount,
        item.value,
      );
    }
    for (const roomItem of ROOM_ITEMS) {
      insertRoomItem.run(roomItem.roomId, roomItem.itemId, roomItem.quantity);
    }
    for (const template of MOB_TEMPLATES) {
      insertMobTemplate.run(
        template.id,
        template.name,
        template.hp,
        template.strength,
        template.dexterity,
        template.physicalDefense,
        template.magicDefense,
        template.element,
        template.damageType,
        template.expReward,
        template.goldReward,
        template.level,
      );
    }
    for (const spawn of MOB_SPAWNS) {
      insertMobSpawn.run(spawn.roomId, spawn.mobTemplateId, spawn.respawnSeconds);
    }
  });
  seedTx();
}
