import type { MobTemplateSeed } from '../types.js';

/**
 * 쥐/고블린은 구대륙 튜토리얼용 고정 레벨 몹. 나머지 5종은 레벨링 존(늪지 정글~용의 둥지)에서
 * 쓰는 범위형 몹으로, 존에 배치될 때(mob_spawns.min_level/max_level)로 좁혀진 범위 안에서
 * 스폰마다 레벨을 굴리고 min~max 스탯 사이를 선형 보간한다. min/max 스탯은 예전에 앵커로
 * 손으로 만들었던 Lv1(min)과 Lv50(max) 스탯을 그대로 옮겨왔다.
 */
export const MOB_TEMPLATES_BASE: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 8,
    hpMax: 8,
    strength: 2,
    strengthMax: 2,
    dexterity: 1,
    dexterityMax: 1,
    physicalDefense: 0,
    physicalDefenseMax: 0,
    magicDefense: 0,
    magicDefenseMax: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 5,
    goldReward: 2,
    goldRewardMax: 2,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 15,
    hpMax: 15,
    strength: 4,
    strengthMax: 4,
    dexterity: 2,
    dexterityMax: 2,
    physicalDefense: 1,
    physicalDefenseMax: 1,
    magicDefense: 1,
    magicDefenseMax: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    expRewardMax: 12,
    goldReward: 5,
    goldRewardMax: 5,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 10,
    hpMax: 398,
    strength: 2,
    strengthMax: 85,
    dexterity: 1,
    dexterityMax: 43,
    physicalDefense: 1,
    physicalDefenseMax: 55,
    magicDefense: 1,
    magicDefenseMax: 24,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    expRewardMax: 183,
    goldReward: 2,
    goldRewardMax: 80,
    minLevel: 1,
    maxLevel: 50,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 5,
    hpMax: 181,
    strength: 5,
    strengthMax: 204,
    dexterity: 1,
    dexterityMax: 61,
    physicalDefense: 0,
    physicalDefenseMax: 10,
    magicDefense: 1,
    magicDefenseMax: 24,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    expRewardMax: 150,
    goldReward: 2,
    goldRewardMax: 80,
    minLevel: 1,
    maxLevel: 50,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 14,
    hpMax: 575,
    strength: 1,
    strengthMax: 47,
    dexterity: 1,
    dexterityMax: 37,
    physicalDefense: 2,
    physicalDefenseMax: 66,
    magicDefense: 1,
    magicDefenseMax: 28,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 217,
    goldReward: 2,
    goldRewardMax: 80,
    minLevel: 1,
    maxLevel: 50,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 7,
    hpMax: 281,
    strength: 4,
    strengthMax: 144,
    dexterity: 1,
    dexterityMax: 52,
    physicalDefense: 1,
    physicalDefenseMax: 44,
    magicDefense: 0,
    magicDefenseMax: 15,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 167,
    goldReward: 2,
    goldRewardMax: 80,
    minLevel: 1,
    maxLevel: 50,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 12,
    hpMax: 462,
    strength: 2,
    strengthMax: 92,
    dexterity: 1,
    dexterityMax: 44,
    physicalDefense: 1,
    physicalDefenseMax: 55,
    magicDefense: 0,
    magicDefenseMax: 14,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 191,
    goldReward: 2,
    goldRewardMax: 80,
    minLevel: 1,
    maxLevel: 50,
  },
];
