import type { MobTemplateSeed } from '../types.js';

/**
 * 쥐/고블린은 구대륙 튜토리얼용 고정 레벨 몹. 나머지는 레벨링 존(늪지 정글~용의 둥지)에서 쓰는
 * 5개 계열(덩굴괴수/불도마뱀/바위골렘/강철전갈/늪지악어) × 5단계 진화형이다. 각 몹의 min~max
 * 레벨 폭은 10 이하로 좁혀서 같은 이름이 너무 넓은 레벨대에 걸쳐 있지 않게 하고, 계열마다
 * 레벨 구간(1-10/11-20/21-30/31-40/41-50)에 맞는 이름으로 갈아입는다. min/max 스탯은 예전에
 * Lv1과 Lv50 앵커로 손으로 만들었던 값 사이를 선형 보간해 각 구간의 경계값을 그대로 옮겨왔다.
 */
export const MOB_TEMPLATES_BASE: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 36,
    hpMax: 36,
    strength: 4,
    strengthMax: 4,
    dexterity: 4,
    dexterityMax: 4,
    physicalDefense: 5,
    physicalDefenseMax: 5,
    magicDefense: 0,
    magicDefenseMax: 5,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 5,
    goldReward: 2,
    goldRewardMax: 2,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 43,
    hpMax: 43,
    strength: 4,
    strengthMax: 4,
    dexterity: 4,
    dexterityMax: 4,
    physicalDefense: 6,
    physicalDefenseMax: 6,
    magicDefense: 6,
    magicDefenseMax: 6,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    expRewardMax: 12,
    goldReward: 5,
    goldRewardMax: 5,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 41,
    hpMax: 272,
    strength: 5,
    strengthMax: 33,
    dexterity: 4,
    dexterityMax: 30,
    physicalDefense: 6,
    physicalDefenseMax: 31,
    magicDefense: 6,
    magicDefenseMax: 19,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    expRewardMax: 37,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 8,
    name: '가시덩굴괴수',
    hp: 300,
    hpMax: 531,
    strength: 38,
    strengthMax: 63,
    dexterity: 34,
    dexterityMax: 57,
    physicalDefense: 33,
    physicalDefenseMax: 50,
    magicDefense: 21,
    magicDefenseMax: 30,
    element: 'wood',
    damageType: 'physical',
    expReward: 41,
    expRewardMax: 73,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 9,
    name: '맹독가시괴수',
    hp: 559,
    hpMax: 791,
    strength: 67,
    strengthMax: 90,
    dexterity: 59,
    dexterityMax: 80,
    physicalDefense: 53,
    physicalDefenseMax: 65,
    magicDefense: 30,
    magicDefenseMax: 38,
    element: 'wood',
    damageType: 'physical',
    expReward: 77,
    expRewardMax: 110,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 10,
    name: '심연의 덩굴괴수',
    hp: 819,
    hpMax: 1050,
    strength: 94,
    strengthMax: 117,
    dexterity: 84,
    dexterityMax: 105,
    physicalDefense: 68,
    physicalDefenseMax: 79,
    magicDefense: 37,
    magicDefenseMax: 43,
    element: 'wood',
    damageType: 'physical',
    expReward: 114,
    expRewardMax: 146,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 11,
    name: '태고의 덩굴괴수',
    hp: 1078,
    hpMax: 1309,
    strength: 120,
    strengthMax: 144,
    dexterity: 108,
    dexterityMax: 128,
    physicalDefense: 81,
    physicalDefenseMax: 92,
    magicDefense: 44,
    magicDefenseMax: 47,
    element: 'wood',
    damageType: 'physical',
    expReward: 150,
    expRewardMax: 183,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 36,
    hpMax: 228,
    strength: 6,
    strengthMax: 41,
    dexterity: 4,
    dexterityMax: 28,
    physicalDefense: 5,
    physicalDefenseMax: 22,
    magicDefense: 6,
    magicDefenseMax: 19,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    expRewardMax: 30,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 12,
    name: '화염도마뱀',
    hp: 252,
    hpMax: 444,
    strength: 45,
    strengthMax: 78,
    dexterity: 31,
    dexterityMax: 53,
    physicalDefense: 23,
    physicalDefenseMax: 32,
    magicDefense: 21,
    magicDefenseMax: 30,
    element: 'fire',
    damageType: 'magic',
    expReward: 33,
    expRewardMax: 60,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 13,
    name: '작열도마뱀',
    hp: 468,
    hpMax: 660,
    strength: 82,
    strengthMax: 113,
    dexterity: 55,
    dexterityMax: 78,
    physicalDefense: 34,
    physicalDefenseMax: 38,
    magicDefense: 30,
    magicDefenseMax: 38,
    element: 'fire',
    damageType: 'magic',
    expReward: 63,
    expRewardMax: 90,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 14,
    name: '지옥불도마뱀',
    hp: 684,
    hpMax: 876,
    strength: 117,
    strengthMax: 148,
    dexterity: 80,
    dexterityMax: 103,
    physicalDefense: 40,
    physicalDefenseMax: 43,
    magicDefense: 37,
    magicDefenseMax: 43,
    element: 'fire',
    damageType: 'magic',
    expReward: 93,
    expRewardMax: 120,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 15,
    name: '태고의 불도마뱀',
    hp: 900,
    hpMax: 1092,
    strength: 152,
    strengthMax: 183,
    dexterity: 105,
    dexterityMax: 125,
    physicalDefense: 44,
    physicalDefenseMax: 47,
    magicDefense: 44,
    magicDefenseMax: 47,
    element: 'fire',
    damageType: 'magic',
    expReward: 123,
    expRewardMax: 150,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 45,
    hpMax: 308,
    strength: 4,
    strengthMax: 28,
    dexterity: 4,
    dexterityMax: 28,
    physicalDefense: 7,
    physicalDefenseMax: 34,
    magicDefense: 6,
    magicDefenseMax: 20,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 44,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 16,
    name: '강철골렘',
    hp: 339,
    hpMax: 603,
    strength: 31,
    strengthMax: 51,
    dexterity: 31,
    dexterityMax: 51,
    physicalDefense: 36,
    physicalDefenseMax: 55,
    magicDefense: 22,
    magicDefenseMax: 31,
    element: 'earth',
    damageType: 'physical',
    expReward: 48,
    expRewardMax: 87,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 17,
    name: '흑요석골렘',
    hp: 634,
    hpMax: 897,
    strength: 54,
    strengthMax: 72,
    dexterity: 54,
    dexterityMax: 72,
    physicalDefense: 58,
    physicalDefenseMax: 72,
    magicDefense: 32,
    magicDefenseMax: 40,
    element: 'earth',
    damageType: 'physical',
    expReward: 92,
    expRewardMax: 130,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 18,
    name: '심연의 골렘',
    hp: 928,
    hpMax: 1192,
    strength: 75,
    strengthMax: 93,
    dexterity: 75,
    dexterityMax: 93,
    physicalDefense: 75,
    physicalDefenseMax: 88,
    magicDefense: 40,
    magicDefenseMax: 46,
    element: 'earth',
    damageType: 'physical',
    expReward: 135,
    expRewardMax: 174,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 19,
    name: '태고의 골렘',
    hp: 1223,
    hpMax: 1486,
    strength: 95,
    strengthMax: 112,
    dexterity: 95,
    dexterityMax: 112,
    physicalDefense: 90,
    physicalDefenseMax: 103,
    magicDefense: 47,
    magicDefenseMax: 51,
    element: 'earth',
    damageType: 'physical',
    expReward: 178,
    expRewardMax: 217,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 38,
    hpMax: 248,
    strength: 6,
    strengthMax: 44,
    dexterity: 4,
    dexterityMax: 33,
    physicalDefense: 6,
    physicalDefenseMax: 29,
    magicDefense: 0,
    magicDefenseMax: 17,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 33,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 20,
    name: '독침전갈',
    hp: 274,
    hpMax: 484,
    strength: 49,
    strengthMax: 83,
    dexterity: 38,
    dexterityMax: 64,
    physicalDefense: 31,
    physicalDefenseMax: 46,
    magicDefense: 18,
    magicDefenseMax: 26,
    element: 'metal',
    damageType: 'physical',
    expReward: 36,
    expRewardMax: 67,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 21,
    name: '사혈전갈',
    hp: 510,
    hpMax: 720,
    strength: 88,
    strengthMax: 119,
    dexterity: 68,
    dexterityMax: 92,
    physicalDefense: 49,
    physicalDefenseMax: 58,
    magicDefense: 26,
    magicDefenseMax: 32,
    element: 'metal',
    damageType: 'physical',
    expReward: 70,
    expRewardMax: 100,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 22,
    name: '흑철전갈',
    hp: 746,
    hpMax: 956,
    strength: 124,
    strengthMax: 156,
    dexterity: 97,
    dexterityMax: 122,
    physicalDefense: 61,
    physicalDefenseMax: 70,
    magicDefense: 31,
    magicDefenseMax: 36,
    element: 'metal',
    damageType: 'physical',
    expReward: 103,
    expRewardMax: 134,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 23,
    name: '태고의 전갈',
    hp: 982,
    hpMax: 1192,
    strength: 160,
    strengthMax: 191,
    dexterity: 124,
    dexterityMax: 148,
    physicalDefense: 72,
    physicalDefenseMax: 81,
    magicDefense: 36,
    magicDefenseMax: 38,
    element: 'metal',
    damageType: 'physical',
    expReward: 137,
    expRewardMax: 167,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 43,
    hpMax: 286,
    strength: 5,
    strengthMax: 35,
    dexterity: 4,
    dexterityMax: 30,
    physicalDefense: 6,
    physicalDefenseMax: 31,
    magicDefense: 0,
    magicDefenseMax: 17,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 38,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 24,
    name: '심해악어',
    hp: 315,
    hpMax: 557,
    strength: 38,
    strengthMax: 65,
    dexterity: 34,
    dexterityMax: 57,
    physicalDefense: 33,
    physicalDefenseMax: 50,
    magicDefense: 18,
    magicDefenseMax: 25,
    element: 'water',
    damageType: 'physical',
    expReward: 41,
    expRewardMax: 76,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 25,
    name: '빙하악어',
    hp: 587,
    hpMax: 829,
    strength: 69,
    strengthMax: 94,
    dexterity: 61,
    dexterityMax: 82,
    physicalDefense: 53,
    physicalDefenseMax: 65,
    magicDefense: 26,
    magicDefenseMax: 31,
    element: 'water',
    damageType: 'physical',
    expReward: 80,
    expRewardMax: 114,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 26,
    name: '폭풍악어',
    hp: 859,
    hpMax: 1101,
    strength: 98,
    strengthMax: 123,
    dexterity: 86,
    dexterityMax: 107,
    physicalDefense: 68,
    physicalDefenseMax: 79,
    magicDefense: 31,
    magicDefenseMax: 35,
    element: 'water',
    damageType: 'physical',
    expReward: 118,
    expRewardMax: 153,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 27,
    name: '태고의 악어',
    hp: 1130,
    hpMax: 1373,
    strength: 124,
    strengthMax: 150,
    dexterity: 110,
    dexterityMax: 132,
    physicalDefense: 81,
    physicalDefenseMax: 92,
    magicDefense: 35,
    magicDefenseMax: 37,
    element: 'water',
    damageType: 'physical',
    expReward: 156,
    expRewardMax: 191,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
];
