import type { MobTemplateSeed } from '../types.js';

/**
 * 쥐/고블린은 구대륙 튜토리얼용 고정 레벨 몹. 나머지는 레벨링 존(늪지 정글~용의 둥지)에서 쓰는
 * 5개 계열(덩굴괴수/불도마뱀/바위골렘/강철전갈/늪지악어) × 5단계 진화형이다. 각 몹의 min~max
 * 레벨 폭은 10 이하로 좁혀서 같은 이름이 너무 넓은 레벨대에 걸쳐 있지 않게 하고, 계열마다
 * 레벨 구간(1-10/11-20/21-30/31-40/41-50)에 맞는 이름으로 갈아입는다. min/max 스탯은 예전에
 * Lv1과 Lv50 앵커로 손으로 만들었던 값 사이를 선형 보간해 각 구간의 경계값을 그대로 옮겨왔다.
 */
export const MOB_TEMPLATES_BASE: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 8,
    hpMax: 8,
    strength: 2,
    strengthMax: 2,
    dexterity: 1,
    dexterityMax: 1,
    physicalDefense: 0,
    physicalDefenseMax: 0,
    magicDefense: 0,
    magicDefenseMax: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 5,
    goldReward: 2,
    goldRewardMax: 2,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 15,
    hpMax: 15,
    strength: 4,
    strengthMax: 4,
    dexterity: 2,
    dexterityMax: 2,
    physicalDefense: 1,
    physicalDefenseMax: 1,
    magicDefense: 1,
    magicDefenseMax: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    expRewardMax: 12,
    goldReward: 5,
    goldRewardMax: 5,
    minLevel: 1,
    maxLevel: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 10,
    hpMax: 81,
    strength: 2,
    strengthMax: 17,
    dexterity: 1,
    dexterityMax: 9,
    physicalDefense: 1,
    physicalDefenseMax: 11,
    magicDefense: 1,
    magicDefenseMax: 5,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    expRewardMax: 37,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 8,
    name: '가시덩굴괴수',
    hp: 89,
    hpMax: 160,
    strength: 19,
    strengthMax: 34,
    dexterity: 10,
    dexterityMax: 17,
    physicalDefense: 12,
    physicalDefenseMax: 22,
    magicDefense: 6,
    magicDefenseMax: 10,
    element: 'wood',
    damageType: 'physical',
    expReward: 41,
    expRewardMax: 73,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 9,
    name: '맹독가시괴수',
    hp: 168,
    hpMax: 240,
    strength: 36,
    strengthMax: 51,
    dexterity: 18,
    dexterityMax: 26,
    physicalDefense: 23,
    physicalDefenseMax: 33,
    magicDefense: 10,
    magicDefenseMax: 15,
    element: 'wood',
    damageType: 'physical',
    expReward: 77,
    expRewardMax: 110,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 10,
    name: '심연의 덩굴괴수',
    hp: 248,
    hpMax: 319,
    strength: 53,
    strengthMax: 68,
    dexterity: 27,
    dexterityMax: 34,
    physicalDefense: 34,
    physicalDefenseMax: 44,
    magicDefense: 15,
    magicDefenseMax: 19,
    element: 'wood',
    damageType: 'physical',
    expReward: 114,
    expRewardMax: 146,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 11,
    name: '태고의 덩굴괴수',
    hp: 327,
    hpMax: 398,
    strength: 70,
    strengthMax: 85,
    dexterity: 35,
    dexterityMax: 43,
    physicalDefense: 45,
    physicalDefenseMax: 55,
    magicDefense: 20,
    magicDefenseMax: 24,
    element: 'wood',
    damageType: 'physical',
    expReward: 150,
    expRewardMax: 183,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 5,
    hpMax: 37,
    strength: 5,
    strengthMax: 42,
    dexterity: 1,
    dexterityMax: 12,
    physicalDefense: 0,
    physicalDefenseMax: 2,
    magicDefense: 1,
    magicDefenseMax: 5,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    expRewardMax: 30,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 12,
    name: '화염도마뱀',
    hp: 41,
    hpMax: 73,
    strength: 46,
    strengthMax: 82,
    dexterity: 13,
    dexterityMax: 24,
    physicalDefense: 2,
    physicalDefenseMax: 4,
    magicDefense: 6,
    magicDefenseMax: 10,
    element: 'fire',
    damageType: 'magic',
    expReward: 33,
    expRewardMax: 60,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 13,
    name: '작열도마뱀',
    hp: 77,
    hpMax: 109,
    strength: 86,
    strengthMax: 123,
    dexterity: 25,
    dexterityMax: 37,
    physicalDefense: 4,
    physicalDefenseMax: 6,
    magicDefense: 10,
    magicDefenseMax: 15,
    element: 'fire',
    damageType: 'magic',
    expReward: 63,
    expRewardMax: 90,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 14,
    name: '지옥불도마뱀',
    hp: 113,
    hpMax: 145,
    strength: 127,
    strengthMax: 163,
    dexterity: 38,
    dexterityMax: 49,
    physicalDefense: 6,
    physicalDefenseMax: 8,
    magicDefense: 15,
    magicDefenseMax: 19,
    element: 'fire',
    damageType: 'magic',
    expReward: 93,
    expRewardMax: 120,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 15,
    name: '태고의 불도마뱀',
    hp: 149,
    hpMax: 181,
    strength: 167,
    strengthMax: 204,
    dexterity: 50,
    dexterityMax: 61,
    physicalDefense: 8,
    physicalDefenseMax: 10,
    magicDefense: 20,
    magicDefenseMax: 24,
    element: 'fire',
    damageType: 'magic',
    expReward: 123,
    expRewardMax: 150,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 14,
    hpMax: 117,
    strength: 1,
    strengthMax: 9,
    dexterity: 1,
    dexterityMax: 8,
    physicalDefense: 2,
    physicalDefenseMax: 14,
    magicDefense: 1,
    magicDefenseMax: 6,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    expRewardMax: 44,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 16,
    name: '강철골렘',
    hp: 128,
    hpMax: 232,
    strength: 10,
    strengthMax: 19,
    dexterity: 8,
    dexterityMax: 15,
    physicalDefense: 15,
    physicalDefenseMax: 27,
    magicDefense: 7,
    magicDefenseMax: 11,
    element: 'earth',
    damageType: 'physical',
    expReward: 48,
    expRewardMax: 87,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 17,
    name: '흑요석골렘',
    hp: 243,
    hpMax: 346,
    strength: 20,
    strengthMax: 28,
    dexterity: 16,
    dexterityMax: 22,
    physicalDefense: 28,
    physicalDefenseMax: 40,
    magicDefense: 12,
    magicDefenseMax: 17,
    element: 'earth',
    damageType: 'physical',
    expReward: 92,
    expRewardMax: 130,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 18,
    name: '심연의 골렘',
    hp: 357,
    hpMax: 461,
    strength: 29,
    strengthMax: 38,
    dexterity: 23,
    dexterityMax: 30,
    physicalDefense: 41,
    physicalDefenseMax: 53,
    magicDefense: 18,
    magicDefenseMax: 22,
    element: 'earth',
    damageType: 'physical',
    expReward: 135,
    expRewardMax: 174,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 19,
    name: '태고의 골렘',
    hp: 472,
    hpMax: 575,
    strength: 39,
    strengthMax: 47,
    dexterity: 30,
    dexterityMax: 37,
    physicalDefense: 54,
    physicalDefenseMax: 66,
    magicDefense: 23,
    magicDefenseMax: 28,
    element: 'earth',
    damageType: 'physical',
    expReward: 178,
    expRewardMax: 217,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 7,
    hpMax: 57,
    strength: 4,
    strengthMax: 30,
    dexterity: 1,
    dexterityMax: 10,
    physicalDefense: 1,
    physicalDefenseMax: 9,
    magicDefense: 0,
    magicDefenseMax: 3,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 33,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 20,
    name: '독침전갈',
    hp: 63,
    hpMax: 113,
    strength: 33,
    strengthMax: 58,
    dexterity: 11,
    dexterityMax: 21,
    physicalDefense: 10,
    physicalDefenseMax: 18,
    magicDefense: 3,
    magicDefenseMax: 6,
    element: 'metal',
    damageType: 'physical',
    expReward: 36,
    expRewardMax: 67,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 21,
    name: '사혈전갈',
    hp: 119,
    hpMax: 169,
    strength: 61,
    strengthMax: 87,
    dexterity: 22,
    dexterityMax: 31,
    physicalDefense: 19,
    physicalDefenseMax: 26,
    magicDefense: 6,
    magicDefenseMax: 9,
    element: 'metal',
    damageType: 'physical',
    expReward: 70,
    expRewardMax: 100,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 22,
    name: '흑철전갈',
    hp: 175,
    hpMax: 225,
    strength: 90,
    strengthMax: 115,
    dexterity: 32,
    dexterityMax: 42,
    physicalDefense: 27,
    physicalDefenseMax: 35,
    magicDefense: 9,
    magicDefenseMax: 12,
    element: 'metal',
    damageType: 'physical',
    expReward: 103,
    expRewardMax: 134,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 23,
    name: '태고의 전갈',
    hp: 231,
    hpMax: 281,
    strength: 118,
    strengthMax: 144,
    dexterity: 43,
    dexterityMax: 52,
    physicalDefense: 36,
    physicalDefenseMax: 44,
    magicDefense: 12,
    magicDefenseMax: 15,
    element: 'metal',
    damageType: 'physical',
    expReward: 137,
    expRewardMax: 167,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 12,
    hpMax: 95,
    strength: 2,
    strengthMax: 19,
    dexterity: 1,
    dexterityMax: 9,
    physicalDefense: 1,
    physicalDefenseMax: 11,
    magicDefense: 0,
    magicDefenseMax: 3,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    expRewardMax: 38,
    goldReward: 2,
    goldRewardMax: 16,
    minLevel: 1,
    maxLevel: 10,
  },
  {
    id: 24,
    name: '심해악어',
    hp: 104,
    hpMax: 186,
    strength: 20,
    strengthMax: 37,
    dexterity: 10,
    dexterityMax: 18,
    physicalDefense: 12,
    physicalDefenseMax: 22,
    magicDefense: 3,
    magicDefenseMax: 5,
    element: 'water',
    damageType: 'physical',
    expReward: 41,
    expRewardMax: 76,
    goldReward: 18,
    goldRewardMax: 32,
    minLevel: 11,
    maxLevel: 20,
  },
  {
    id: 25,
    name: '빙하악어',
    hp: 196,
    hpMax: 278,
    strength: 39,
    strengthMax: 55,
    dexterity: 19,
    dexterityMax: 26,
    physicalDefense: 23,
    physicalDefenseMax: 33,
    magicDefense: 6,
    magicDefenseMax: 8,
    element: 'water',
    damageType: 'physical',
    expReward: 80,
    expRewardMax: 114,
    goldReward: 34,
    goldRewardMax: 48,
    minLevel: 21,
    maxLevel: 30,
  },
  {
    id: 26,
    name: '폭풍악어',
    hp: 288,
    hpMax: 370,
    strength: 57,
    strengthMax: 74,
    dexterity: 27,
    dexterityMax: 35,
    physicalDefense: 34,
    physicalDefenseMax: 44,
    magicDefense: 9,
    magicDefenseMax: 11,
    element: 'water',
    damageType: 'physical',
    expReward: 118,
    expRewardMax: 153,
    goldReward: 50,
    goldRewardMax: 64,
    minLevel: 31,
    maxLevel: 40,
  },
  {
    id: 27,
    name: '태고의 악어',
    hp: 379,
    hpMax: 462,
    strength: 75,
    strengthMax: 92,
    dexterity: 36,
    dexterityMax: 44,
    physicalDefense: 45,
    physicalDefenseMax: 55,
    magicDefense: 11,
    magicDefenseMax: 14,
    element: 'water',
    damageType: 'physical',
    expReward: 156,
    expRewardMax: 191,
    goldReward: 66,
    goldRewardMax: 80,
    minLevel: 41,
    maxLevel: 50,
  },
];
