import type { MobLootPoolSeed } from '../types.js';

export const MOB_LOOT_POOL_BASE: MobLootPoolSeed[] = [
  { mobTemplateId: 1, itemId: 1, weight: 100 },
  { mobTemplateId: 1, itemId: 2, weight: 100 },
  { mobTemplateId: 1, itemId: 3, weight: 100 },
  { mobTemplateId: 2, itemId: 8, weight: 100 },
  { mobTemplateId: 2, itemId: 9, weight: 100 },
  { mobTemplateId: 2, itemId: 10, weight: 100 },
  { mobTemplateId: 3, itemId: 3, weight: 100 },
  { mobTemplateId: 3, itemId: 4, weight: 100 },
  { mobTemplateId: 3, itemId: 5, weight: 100 },
  { mobTemplateId: 4, itemId: 10, weight: 100 },
  { mobTemplateId: 4, itemId: 11, weight: 100 },
  { mobTemplateId: 4, itemId: 62, weight: 100 },
  { mobTemplateId: 5, itemId: 5, weight: 100 },
  { mobTemplateId: 5, itemId: 6, weight: 100 },
  { mobTemplateId: 5, itemId: 7, weight: 100 },
  { mobTemplateId: 6, itemId: 62, weight: 100 },
  { mobTemplateId: 6, itemId: 1, weight: 100 },
  { mobTemplateId: 6, itemId: 2, weight: 100 },
  { mobTemplateId: 7, itemId: 7, weight: 100 },
  { mobTemplateId: 7, itemId: 8, weight: 100 },
  { mobTemplateId: 7, itemId: 9, weight: 100 },
];
