import type { MobLootPoolSeed } from '../types.js';

/**
 * weight는 "기본 등장확률(%)" — 몹이 지금 굴린 레벨이 자기 템플릿의 min~max 구간에서 몇 번째냐에
 * 따라 배수(최소=1배, 최대=10배)를 곱한 뒤 아이템마다 독립적으로 굴린다(MobManager.rollMobLoot).
 * 쥐/고블린은 항상 레벨1 고정이라 배수가 늘 1배로, 여기 적힌 값이 곧 실제 확률이다.
 */
export const MOB_LOOT_POOL_BASE: MobLootPoolSeed[] = [
  { mobTemplateId: 1, itemId: 1, weight: 5 },
  { mobTemplateId: 1, itemId: 2, weight: 5 },
  { mobTemplateId: 1, itemId: 3, weight: 5 },
  { mobTemplateId: 2, itemId: 8, weight: 5 },
  { mobTemplateId: 2, itemId: 9, weight: 5 },
  { mobTemplateId: 2, itemId: 10, weight: 5 },
  { mobTemplateId: 2, itemId: 100, weight: 5 },
  // 아래는 레벨링 존 5계열 × 5단계 진화형(base.ts) 몹의 루팅 풀. 계열별로 겹치지 않는 장비 2종씩,
  // 진화 단계가 올라갈수록 그 단계에 맞는 등급 아이템으로 바뀐다(1-10→하급, 11-20→상급, ...).
  { mobTemplateId: 3, itemId: 1, weight: 3 },
  { mobTemplateId: 3, itemId: 6, weight: 2 },
  { mobTemplateId: 4, itemId: 2, weight: 3 },
  { mobTemplateId: 4, itemId: 62, weight: 2 },
  { mobTemplateId: 5, itemId: 3, weight: 3 },
  { mobTemplateId: 5, itemId: 7, weight: 2 },
  { mobTemplateId: 6, itemId: 4, weight: 3 },
  { mobTemplateId: 6, itemId: 8, weight: 2 },
  { mobTemplateId: 7, itemId: 5, weight: 3 },
  { mobTemplateId: 7, itemId: 9, weight: 2 },
  { mobTemplateId: 8, itemId: 16, weight: 3 },
  { mobTemplateId: 8, itemId: 39, weight: 2 },
  { mobTemplateId: 9, itemId: 20, weight: 3 },
  { mobTemplateId: 9, itemId: 45, weight: 2 },
  { mobTemplateId: 10, itemId: 24, weight: 3 },
  { mobTemplateId: 10, itemId: 51, weight: 2 },
  { mobTemplateId: 11, itemId: 28, weight: 3 },
  { mobTemplateId: 11, itemId: 57, weight: 2 },
  { mobTemplateId: 12, itemId: 17, weight: 3 },
  { mobTemplateId: 12, itemId: 64, weight: 2 },
  { mobTemplateId: 13, itemId: 21, weight: 3 },
  { mobTemplateId: 13, itemId: 65, weight: 2 },
  { mobTemplateId: 14, itemId: 25, weight: 3 },
  { mobTemplateId: 14, itemId: 66, weight: 2 },
  { mobTemplateId: 15, itemId: 29, weight: 3 },
  { mobTemplateId: 15, itemId: 67, weight: 2 },
  { mobTemplateId: 16, itemId: 18, weight: 3 },
  { mobTemplateId: 16, itemId: 40, weight: 2 },
  { mobTemplateId: 17, itemId: 22, weight: 3 },
  { mobTemplateId: 17, itemId: 46, weight: 2 },
  { mobTemplateId: 18, itemId: 26, weight: 3 },
  { mobTemplateId: 18, itemId: 52, weight: 2 },
  { mobTemplateId: 19, itemId: 30, weight: 3 },
  { mobTemplateId: 19, itemId: 58, weight: 2 },
  { mobTemplateId: 20, itemId: 19, weight: 3 },
  { mobTemplateId: 20, itemId: 41, weight: 2 },
  { mobTemplateId: 21, itemId: 23, weight: 3 },
  { mobTemplateId: 21, itemId: 47, weight: 2 },
  { mobTemplateId: 22, itemId: 27, weight: 3 },
  { mobTemplateId: 22, itemId: 53, weight: 2 },
  { mobTemplateId: 23, itemId: 31, weight: 3 },
  { mobTemplateId: 23, itemId: 59, weight: 2 },
  { mobTemplateId: 24, itemId: 38, weight: 3 },
  { mobTemplateId: 24, itemId: 42, weight: 2 },
  { mobTemplateId: 25, itemId: 44, weight: 3 },
  { mobTemplateId: 25, itemId: 48, weight: 2 },
  { mobTemplateId: 26, itemId: 50, weight: 3 },
  { mobTemplateId: 26, itemId: 54, weight: 2 },
  { mobTemplateId: 27, itemId: 56, weight: 3 },
  { mobTemplateId: 27, itemId: 60, weight: 2 },
];
