import type { MobTemplateSeed } from '../types.js';

export const MOB_TEMPLATES_TIER3: MobTemplateSeed[] = [
  {
    id: 38,
    name: '덩굴괴수',
    hp: 279,
    strength: 60,
    dexterity: 30,
    physicalDefense: 39,
    magicDefense: 17,
    element: 'wood',
    damageType: 'physical',
    expReward: 129,
    goldReward: 56,
    level: 35,
  },
  {
    id: 39,
    name: '불도마뱀',
    hp: 127,
    strength: 143,
    dexterity: 42,
    physicalDefense: 7,
    magicDefense: 17,
    element: 'fire',
    damageType: 'magic',
    expReward: 105,
    goldReward: 56,
    level: 35,
  },
  {
    id: 40,
    name: '바위골렘',
    hp: 403,
    strength: 33,
    dexterity: 26,
    physicalDefense: 46,
    magicDefense: 20,
    element: 'earth',
    damageType: 'physical',
    expReward: 152,
    goldReward: 56,
    level: 35,
  },
  {
    id: 41,
    name: '강철전갈',
    hp: 197,
    strength: 101,
    dexterity: 36,
    physicalDefense: 31,
    magicDefense: 10,
    element: 'metal',
    damageType: 'physical',
    expReward: 116,
    goldReward: 56,
    level: 35,
  },
  {
    id: 42,
    name: '늪지악어',
    hp: 324,
    strength: 65,
    dexterity: 31,
    physicalDefense: 39,
    magicDefense: 10,
    element: 'water',
    damageType: 'physical',
    expReward: 134,
    goldReward: 56,
    level: 35,
  },
  {
    id: 43,
    name: '덩굴괴수',
    hp: 319,
    strength: 68,
    dexterity: 34,
    physicalDefense: 44,
    magicDefense: 19,
    element: 'wood',
    damageType: 'physical',
    expReward: 146,
    goldReward: 64,
    level: 40,
  },
  {
    id: 44,
    name: '불도마뱀',
    hp: 145,
    strength: 163,
    dexterity: 48,
    physicalDefense: 8,
    magicDefense: 19,
    element: 'fire',
    damageType: 'magic',
    expReward: 120,
    goldReward: 64,
    level: 40,
  },
  {
    id: 45,
    name: '바위골렘',
    hp: 460,
    strength: 38,
    dexterity: 30,
    physicalDefense: 53,
    magicDefense: 23,
    element: 'earth',
    damageType: 'physical',
    expReward: 174,
    goldReward: 64,
    level: 40,
  },
  {
    id: 46,
    name: '강철전갈',
    hp: 225,
    strength: 115,
    dexterity: 41,
    physicalDefense: 35,
    magicDefense: 12,
    element: 'metal',
    damageType: 'physical',
    expReward: 133,
    goldReward: 64,
    level: 40,
  },
  {
    id: 47,
    name: '늪지악어',
    hp: 370,
    strength: 74,
    dexterity: 35,
    physicalDefense: 44,
    magicDefense: 11,
    element: 'water',
    damageType: 'physical',
    expReward: 153,
    goldReward: 64,
    level: 40,
  },
  {
    id: 48,
    name: '덩굴괴수',
    hp: 358,
    strength: 77,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 21,
    element: 'wood',
    damageType: 'physical',
    expReward: 165,
    goldReward: 72,
    level: 45,
  },
  {
    id: 49,
    name: '불도마뱀',
    hp: 163,
    strength: 183,
    dexterity: 54,
    physicalDefense: 9,
    magicDefense: 21,
    element: 'fire',
    damageType: 'magic',
    expReward: 134,
    goldReward: 72,
    level: 45,
  },
  {
    id: 50,
    name: '바위골렘',
    hp: 518,
    strength: 42,
    dexterity: 33,
    physicalDefense: 59,
    magicDefense: 25,
    element: 'earth',
    damageType: 'physical',
    expReward: 194,
    goldReward: 72,
    level: 45,
  },
  {
    id: 51,
    name: '강철전갈',
    hp: 253,
    strength: 129,
    dexterity: 46,
    physicalDefense: 40,
    magicDefense: 13,
    element: 'metal',
    damageType: 'physical',
    expReward: 150,
    goldReward: 72,
    level: 45,
  },
  {
    id: 52,
    name: '늪지악어',
    hp: 416,
    strength: 83,
    dexterity: 39,
    physicalDefense: 50,
    magicDefense: 12,
    element: 'water',
    damageType: 'physical',
    expReward: 172,
    goldReward: 72,
    level: 45,
  },
  {
    id: 53,
    name: '덩굴괴수',
    hp: 398,
    strength: 85,
    dexterity: 43,
    physicalDefense: 55,
    magicDefense: 24,
    element: 'wood',
    damageType: 'physical',
    expReward: 183,
    goldReward: 80,
    level: 50,
  },
  {
    id: 54,
    name: '불도마뱀',
    hp: 181,
    strength: 204,
    dexterity: 61,
    physicalDefense: 10,
    magicDefense: 24,
    element: 'fire',
    damageType: 'magic',
    expReward: 150,
    goldReward: 80,
    level: 50,
  },
  {
    id: 55,
    name: '바위골렘',
    hp: 575,
    strength: 47,
    dexterity: 37,
    physicalDefense: 66,
    magicDefense: 28,
    element: 'earth',
    damageType: 'physical',
    expReward: 217,
    goldReward: 80,
    level: 50,
  },
  {
    id: 56,
    name: '강철전갈',
    hp: 281,
    strength: 144,
    dexterity: 52,
    physicalDefense: 44,
    magicDefense: 15,
    element: 'metal',
    damageType: 'physical',
    expReward: 167,
    goldReward: 80,
    level: 50,
  },
  {
    id: 57,
    name: '늪지악어',
    hp: 462,
    strength: 92,
    dexterity: 44,
    physicalDefense: 55,
    magicDefense: 14,
    element: 'water',
    damageType: 'physical',
    expReward: 191,
    goldReward: 80,
    level: 50,
  },
];
