import type { MobTemplateSeed } from '../types.js';

export const MOB_TEMPLATES_TIER1: MobTemplateSeed[] = [
  {
    id: 1,
    name: '쥐',
    hp: 8,
    strength: 2,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 2,
    name: '고블린',
    hp: 15,
    strength: 4,
    dexterity: 2,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 12,
    goldReward: 5,
    level: 1,
  },
  {
    id: 3,
    name: '덩굴괴수',
    hp: 10,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 1,
    element: 'wood',
    damageType: 'physical',
    expReward: 4,
    goldReward: 2,
    level: 1,
  },
  {
    id: 4,
    name: '불도마뱀',
    hp: 5,
    strength: 5,
    dexterity: 1,
    physicalDefense: 0,
    magicDefense: 1,
    element: 'fire',
    damageType: 'magic',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 5,
    name: '바위골렘',
    hp: 14,
    strength: 1,
    dexterity: 1,
    physicalDefense: 2,
    magicDefense: 1,
    element: 'earth',
    damageType: 'physical',
    expReward: 5,
    goldReward: 2,
    level: 1,
  },
  {
    id: 6,
    name: '강철전갈',
    hp: 7,
    strength: 4,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'metal',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 7,
    name: '늪지악어',
    hp: 12,
    strength: 2,
    dexterity: 1,
    physicalDefense: 1,
    magicDefense: 0,
    element: 'water',
    damageType: 'physical',
    expReward: 3,
    goldReward: 2,
    level: 1,
  },
  {
    id: 8,
    name: '덩굴괴수',
    hp: 42,
    strength: 9,
    dexterity: 4,
    physicalDefense: 6,
    magicDefense: 2,
    element: 'wood',
    damageType: 'physical',
    expReward: 18,
    goldReward: 8,
    level: 5,
  },
  {
    id: 9,
    name: '불도마뱀',
    hp: 19,
    strength: 21,
    dexterity: 6,
    physicalDefense: 1,
    magicDefense: 2,
    element: 'fire',
    damageType: 'magic',
    expReward: 14,
    goldReward: 8,
    level: 5,
  },
  {
    id: 10,
    name: '바위골렘',
    hp: 60,
    strength: 5,
    dexterity: 4,
    physicalDefense: 7,
    magicDefense: 3,
    element: 'earth',
    damageType: 'physical',
    expReward: 22,
    goldReward: 8,
    level: 5,
  },
  {
    id: 11,
    name: '강철전갈',
    hp: 29,
    strength: 15,
    dexterity: 5,
    physicalDefense: 5,
    magicDefense: 2,
    element: 'metal',
    damageType: 'physical',
    expReward: 17,
    goldReward: 8,
    level: 5,
  },
  {
    id: 12,
    name: '늪지악어',
    hp: 48,
    strength: 10,
    dexterity: 5,
    physicalDefense: 6,
    magicDefense: 1,
    element: 'water',
    damageType: 'physical',
    expReward: 19,
    goldReward: 8,
    level: 5,
  },
  {
    id: 13,
    name: '덩굴괴수',
    hp: 81,
    strength: 17,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 5,
    element: 'wood',
    damageType: 'physical',
    expReward: 36,
    goldReward: 16,
    level: 10,
  },
  {
    id: 14,
    name: '불도마뱀',
    hp: 37,
    strength: 42,
    dexterity: 12,
    physicalDefense: 2,
    magicDefense: 5,
    element: 'fire',
    damageType: 'magic',
    expReward: 30,
    goldReward: 16,
    level: 10,
  },
  {
    id: 15,
    name: '바위골렘',
    hp: 117,
    strength: 10,
    dexterity: 8,
    physicalDefense: 13,
    magicDefense: 6,
    element: 'earth',
    damageType: 'physical',
    expReward: 43,
    goldReward: 16,
    level: 10,
  },
  {
    id: 16,
    name: '강철전갈',
    hp: 57,
    strength: 29,
    dexterity: 10,
    physicalDefense: 9,
    magicDefense: 3,
    element: 'metal',
    damageType: 'physical',
    expReward: 33,
    goldReward: 16,
    level: 10,
  },
  {
    id: 17,
    name: '늪지악어',
    hp: 94,
    strength: 19,
    dexterity: 9,
    physicalDefense: 11,
    magicDefense: 3,
    element: 'water',
    damageType: 'physical',
    expReward: 38,
    goldReward: 16,
    level: 10,
  },
  {
    id: 18,
    name: '덩굴괴수',
    hp: 121,
    strength: 26,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 7,
    element: 'wood',
    damageType: 'physical',
    expReward: 55,
    goldReward: 24,
    level: 15,
  },
  {
    id: 19,
    name: '불도마뱀',
    hp: 55,
    strength: 62,
    dexterity: 18,
    physicalDefense: 3,
    magicDefense: 7,
    element: 'fire',
    damageType: 'magic',
    expReward: 45,
    goldReward: 24,
    level: 15,
  },
  {
    id: 20,
    name: '바위골렘',
    hp: 174,
    strength: 14,
    dexterity: 11,
    physicalDefense: 20,
    magicDefense: 9,
    element: 'earth',
    damageType: 'physical',
    expReward: 65,
    goldReward: 24,
    level: 15,
  },
  {
    id: 21,
    name: '강철전갈',
    hp: 85,
    strength: 44,
    dexterity: 16,
    physicalDefense: 13,
    magicDefense: 4,
    element: 'metal',
    damageType: 'physical',
    expReward: 49,
    goldReward: 24,
    level: 15,
  },
  {
    id: 22,
    name: '늪지악어',
    hp: 140,
    strength: 28,
    dexterity: 13,
    physicalDefense: 17,
    magicDefense: 4,
    element: 'water',
    damageType: 'physical',
    expReward: 57,
    goldReward: 24,
    level: 15,
  },
];
