import type { MobTemplateSeed } from '../types.js';

export const MOB_TEMPLATES_TIER2: MobTemplateSeed[] = [
  {
    id: 23,
    name: '덩굴괴수',
    hp: 160,
    strength: 34,
    dexterity: 17,
    physicalDefense: 22,
    magicDefense: 10,
    element: 'wood',
    damageType: 'physical',
    expReward: 73,
    goldReward: 32,
    level: 20,
  },
  {
    id: 24,
    name: '불도마뱀',
    hp: 73,
    strength: 82,
    dexterity: 24,
    physicalDefense: 4,
    magicDefense: 10,
    element: 'fire',
    damageType: 'magic',
    expReward: 60,
    goldReward: 32,
    level: 20,
  },
  {
    id: 25,
    name: '바위골렘',
    hp: 232,
    strength: 19,
    dexterity: 15,
    physicalDefense: 27,
    magicDefense: 11,
    element: 'earth',
    damageType: 'physical',
    expReward: 87,
    goldReward: 32,
    level: 20,
  },
  {
    id: 26,
    name: '강철전갈',
    hp: 113,
    strength: 58,
    dexterity: 21,
    physicalDefense: 18,
    magicDefense: 6,
    element: 'metal',
    damageType: 'physical',
    expReward: 67,
    goldReward: 32,
    level: 20,
  },
  {
    id: 27,
    name: '늪지악어',
    hp: 186,
    strength: 37,
    dexterity: 18,
    physicalDefense: 22,
    magicDefense: 6,
    element: 'water',
    damageType: 'physical',
    expReward: 77,
    goldReward: 32,
    level: 20,
  },
  {
    id: 28,
    name: '덩굴괴수',
    hp: 200,
    strength: 43,
    dexterity: 21,
    physicalDefense: 28,
    magicDefense: 12,
    element: 'wood',
    damageType: 'physical',
    expReward: 92,
    goldReward: 40,
    level: 25,
  },
  {
    id: 29,
    name: '불도마뱀',
    hp: 91,
    strength: 102,
    dexterity: 30,
    physicalDefense: 5,
    magicDefense: 12,
    element: 'fire',
    damageType: 'magic',
    expReward: 75,
    goldReward: 40,
    level: 25,
  },
  {
    id: 30,
    name: '바위골렘',
    hp: 289,
    strength: 24,
    dexterity: 19,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'earth',
    damageType: 'physical',
    expReward: 108,
    goldReward: 40,
    level: 25,
  },
  {
    id: 31,
    name: '강철전갈',
    hp: 141,
    strength: 72,
    dexterity: 26,
    physicalDefense: 22,
    magicDefense: 7,
    element: 'metal',
    damageType: 'physical',
    expReward: 83,
    goldReward: 40,
    level: 25,
  },
  {
    id: 32,
    name: '늪지악어',
    hp: 232,
    strength: 46,
    dexterity: 22,
    physicalDefense: 28,
    magicDefense: 7,
    element: 'water',
    damageType: 'physical',
    expReward: 96,
    goldReward: 40,
    level: 25,
  },
  {
    id: 33,
    name: '덩굴괴수',
    hp: 240,
    strength: 51,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 14,
    element: 'wood',
    damageType: 'physical',
    expReward: 110,
    goldReward: 48,
    level: 30,
  },
  {
    id: 34,
    name: '불도마뱀',
    hp: 109,
    strength: 123,
    dexterity: 36,
    physicalDefense: 6,
    magicDefense: 14,
    element: 'fire',
    damageType: 'magic',
    expReward: 90,
    goldReward: 48,
    level: 30,
  },
  {
    id: 35,
    name: '바위골렘',
    hp: 346,
    strength: 28,
    dexterity: 22,
    physicalDefense: 40,
    magicDefense: 17,
    element: 'earth',
    damageType: 'physical',
    expReward: 130,
    goldReward: 48,
    level: 30,
  },
  {
    id: 36,
    name: '강철전갈',
    hp: 169,
    strength: 87,
    dexterity: 31,
    physicalDefense: 27,
    magicDefense: 9,
    element: 'metal',
    damageType: 'physical',
    expReward: 101,
    goldReward: 48,
    level: 30,
  },
  {
    id: 37,
    name: '늪지악어',
    hp: 278,
    strength: 56,
    dexterity: 26,
    physicalDefense: 33,
    magicDefense: 8,
    element: 'water',
    damageType: 'physical',
    expReward: 114,
    goldReward: 48,
    level: 30,
  },
];
