import type { SkillDefinition } from './types.js';

export const MAGE_SKILLS: SkillDefinition[] = [
  // 마법사 — 원거리 마법 딜
  {
    id: 'mage_firebolt',
    job: 'mage',
    name: '파이어볼',
    description: '불꽃 구체를 쏘아 보냅니다. (마법 피해 2.0배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 6,
    power: 2.0,
    damageType: 'magic',
    cooldownMs: 4000,
  },
  {
    id: 'mage_mana_flow',
    job: 'mage',
    name: '마나 순환',
    description: '마나 회로를 확장합니다. (최대 MP 영구 +10)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxMp',
  },
  {
    id: 'mage_ice_lance',
    job: 'mage',
    name: '얼음창',
    description: '얼음 창을 꿰뚫듯 발사합니다. (마법 피해 2.6배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 10,
    power: 2.6,
    damageType: 'magic',
    cooldownMs: 8000,
  },
  {
    id: 'mage_arcane_mastery',
    job: 'mage',
    name: '대마법',
    description: '마법 이해도가 극에 달합니다. (지능 영구 +8)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_lightning_arrow',
    job: 'mage',
    name: '번개화살',
    description: '번개를 화살처럼 압축해 발사합니다. (마법 피해 3.2배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 14,
    power: 3.2,
    damageType: 'magic',
    cooldownMs: 9500,
  },
  {
    id: 'mage_mind_discipline',
    job: 'mage',
    name: '정신 수양',
    description: '정신을 수양해 마법에 대한 이해를 넓힙니다. (지혜 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
  },
  {
    id: 'mage_earth_spikes',
    job: 'mage',
    name: '대지가시',
    description: '땅에서 날카로운 가시를 솟구치게 합니다. (마법 피해 3.8배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 18,
    power: 3.8,
    damageType: 'magic',
    cooldownMs: 11000,
  },
  {
    id: 'mage_mana_engraving',
    job: 'mage',
    name: '마력 각인',
    description: '마법 회로를 몸에 각인시킵니다. (지능 영구 +10)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_firestorm',
    job: 'mage',
    name: '화염폭풍',
    description: '불의 폭풍을 일으켜 광범위하게 태웁니다. (마법 피해 4.6배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 24,
    power: 4.6,
    damageType: 'magic',
    cooldownMs: 13500,
  },
  {
    id: 'mage_abyssal_wisdom',
    job: 'mage',
    name: '심연의 지혜',
    description: '심연의 지혜를 받아들여 마력이 깊어집니다. (지혜 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'wisdom',
  },
  {
    id: 'mage_absolute_zero',
    job: 'mage',
    name: '절대영도',
    description: '주변을 절대영도까지 얼려버립니다. (마법 피해 5.4배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 30,
    power: 5.4,
    damageType: 'magic',
    cooldownMs: 16000,
  },
  {
    id: 'mage_mana_well',
    job: 'mage',
    name: '마나의 샘',
    description: '끝없이 샘솟는 마나의 우물을 엽니다. (최대 MP 영구 +40)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 40,
    passiveStat: 'maxMp',
  },
  {
    id: 'mage_meteor_fall',
    job: 'mage',
    name: '운석낙하',
    description: '하늘에서 운석을 불러 떨어뜨립니다. (마법 피해 6.2배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 38,
    power: 6.2,
    damageType: 'magic',
    cooldownMs: 19000,
  },
  {
    id: 'mage_archsage_insight',
    job: 'mage',
    name: '대현자의 통찰',
    description: '대현자의 통찰을 얻어 마법이 정교해집니다. (지능 영구 +16)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 16,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_annihilation',
    job: 'mage',
    name: '멸계의 마법',
    description: '세상을 소멸시킬 듯한 궁극의 마법을 시전합니다. (마법 피해 7.2배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 48,
    power: 7.2,
    damageType: 'magic',
    cooldownMs: 23000,
  },
  {
    id: 'mage_world_tree_blessing',
    job: 'mage',
    name: '세계수의 가호',
    description: '세계수의 가호를 받아 마나의 그릇이 무한히 커집니다. (최대 MP 영구 +70)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 70,
    passiveStat: 'maxMp',
  },

];
