import { buildElementBranches } from './branches.js';
import type { SkillDefinition } from './types.js';

const MAGE_TRUNK: SkillDefinition[] = [
  // 마법사 — 원거리 마법 딜. 공통 트리(원소 무관, 순차 선행).
  {
    id: 'mage_firebolt',
    job: 'mage',
    name: '파이어볼',
    description: '불꽃 구체를 쏘아 보냅니다. (마법 피해 2.0배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 6,
    power: 2.0,
    damageType: 'magic',
    targeting: 'single',
    cooldownMs: 4000,
  },
  {
    id: 'mage_mana_flow',
    job: 'mage',
    name: '마나 순환',
    description: '마나 회로를 확장합니다. (최대 MP 영구 증가)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxMp',
    requires: 'mage_firebolt',
  },
  {
    id: 'mage_ice_lance',
    job: 'mage',
    name: '얼음창',
    description: '얼음 창을 꿰뚫듯 발사합니다. (마법 피해 2.6배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 10,
    power: 2.6,
    damageType: 'magic',
    targeting: 'single',
    cooldownMs: 8000,
    requires: 'mage_mana_flow',
  },
  {
    id: 'mage_arcane_mastery',
    job: 'mage',
    name: '대마법',
    description: '마법 이해도가 극에 달합니다. (지능 영구 증가)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'intelligence',
    requires: 'mage_ice_lance',
  },
  {
    id: 'mage_lightning_arrow',
    job: 'mage',
    name: '번개화살',
    description: '번개를 화살처럼 압축해 발사합니다. (마법 피해 3.2배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 14,
    power: 3.2,
    damageType: 'magic',
    targeting: 'single',
    cooldownMs: 9500,
    requires: 'mage_arcane_mastery',
  },
  {
    id: 'mage_mind_discipline',
    job: 'mage',
    name: '정신 수양',
    description: '정신을 수양해 마법에 대한 이해를 넓힙니다. (지혜 영구 증가)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
    requires: 'mage_lightning_arrow',
  },
  {
    id: 'mage_earth_spikes',
    job: 'mage',
    name: '대지가시',
    description: '땅에서 날카로운 가시를 솟구치게 합니다. (마법 피해 3.8배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 18,
    power: 3.8,
    damageType: 'magic',
    targeting: 'single',
    cooldownMs: 11000,
    requires: 'mage_mind_discipline',
  },
  {
    id: 'mage_mana_engraving',
    job: 'mage',
    name: '마력 각인',
    description: '마법 회로를 몸에 각인시킵니다. (지능 영구 증가)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'intelligence',
    requires: 'mage_earth_spikes',
  },
  {
    id: 'mage_firestorm',
    job: 'mage',
    name: '화염폭풍',
    description: '불의 폭풍을 일으켜 광범위하게 태웁니다. (마법 피해 4.6배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 24,
    power: 4.6,
    damageType: 'magic',
    targeting: 'single',
    cooldownMs: 13500,
    requires: 'mage_mana_engraving',
  },
];

const MAGE_BRANCHES = buildElementBranches({
  job: 'mage',
  idPrefix: 'mage',
  tier1Kind: 'damage',
  damageType: 'magic',
  trunkFinalSkillId: 'mage_firestorm',
  themes: {
    wood: {
      tier1Name: '가시넝쿨 폭발',
      tier1Description: '가시 덩굴을 폭발시켜 주변 적 전체에게 마법 피해를 입힙니다. (마법 피해, 광역)',
      tier2Name: '심록의 활력',
      tier2Description: '목 기운이 생명력을 북돋아 육체가 강해집니다. (체력 영구 증가)',
      passiveStat: 'vitality',
    },
    fire: {
      tier1Name: '인페르노',
      tier1Description: '거대한 화염을 일으켜 주변 적 전체를 불태웁니다. (마법 피해, 광역)',
      tier2Name: '타오르는 지성',
      tier2Description: '화 기운이 사고를 예리하게 다듬어 마법 이해가 깊어집니다. (지능 영구 증가)',
      passiveStat: 'intelligence',
    },
    earth: {
      tier1Name: '지각붕괴',
      tier1Description: '대지를 뒤흔들어 주변 적 전체에게 마법 피해를 입힙니다. (마법 피해, 광역)',
      tier2Name: '대지의 결계',
      tier2Description: '토 기운이 몸을 감싸 마법 방벽을 두릅니다. (마법방어 영구 증가)',
      passiveStat: 'magicDefense',
    },
    metal: {
      tier1Name: '금속폭풍',
      tier1Description: '금속 파편을 폭풍처럼 퍼부어 주변 적 전체를 가격합니다. (마법 피해, 광역)',
      tier2Name: '마나의 광맥',
      tier2Description: '금 기운이 몸속에 마나의 광맥을 새겨 넣습니다. (최대 MP 영구 증가)',
      passiveStat: 'maxMp',
    },
    water: {
      tier1Name: '해빙폭발',
      tier1Description: '얼음을 일제히 터뜨려 주변 적 전체에게 냉기 피해를 입힙니다. (마법 피해, 광역)',
      tier2Name: '심연의 통찰',
      tier2Description: '수 기운이 마음을 가라앉혀 깊은 통찰을 얻습니다. (지혜 영구 증가)',
      passiveStat: 'wisdom',
    },
  },
});

export const MAGE_SKILLS: SkillDefinition[] = [...MAGE_TRUNK, ...MAGE_BRANCHES];
