import type { SkillDefinition } from './types.js';

export const PRIEST_SKILLS: SkillDefinition[] = [
  // 사제 — 회복/지원
  {
    id: 'priest_heal',
    job: 'priest',
    name: '소생의 손길',
    description: '따뜻한 빛으로 상처를 치유합니다. (HP 12 회복)',
    requiredLevel: 1,
    kind: 'heal',
    mpCost: 6,
    power: 12,
    cooldownMs: 3000,
  },
  {
    id: 'priest_blessing',
    job: 'priest',
    name: '축복',
    description: '몸에 성스러운 가호를 두릅니다. (마법방어 영구 +5)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_greater_heal',
    job: 'priest',
    name: '신성한 빛',
    description: '강한 빛으로 큰 상처를 치유합니다. (HP 25 회복)',
    requiredLevel: 5,
    kind: 'heal',
    mpCost: 12,
    power: 25,
    cooldownMs: 6000,
  },
  {
    id: 'priest_endurance',
    job: 'priest',
    name: '인내',
    description: '고통을 견디는 법을 체득합니다. (최대 HP 영구 +10)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxHp',
  },
  {
    id: 'priest_healing_prayer',
    job: 'priest',
    name: '치유의 기도',
    description: '간절한 기도로 상처를 어루만집니다. (HP 38 회복)',
    requiredLevel: 11,
    kind: 'heal',
    mpCost: 18,
    power: 38,
    cooldownMs: 8000,
  },
  {
    id: 'priest_holy_patience',
    job: 'priest',
    name: '신성한 인내',
    description: '신성한 힘으로 마법 공격을 견뎌냅니다. (마법방어 영구 +8)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_wave_of_recovery',
    job: 'priest',
    name: '회복의 파동',
    description: '회복의 파동을 일으켜 상처를 씻어냅니다. (HP 52 회복)',
    requiredLevel: 17,
    kind: 'heal',
    mpCost: 24,
    power: 52,
    cooldownMs: 9500,
  },
  {
    id: 'priest_mental_fortitude',
    job: 'priest',
    name: '정신력 강화',
    description: '정신력을 단련해 지혜가 깊어집니다. (지혜 영구 +6)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
  },
  {
    id: 'priest_divine_grace',
    job: 'priest',
    name: '성스러운 은총',
    description: '성스러운 은총이 온몸을 감싸며 치유합니다. (HP 68 회복)',
    requiredLevel: 24,
    kind: 'heal',
    mpCost: 30,
    power: 68,
    cooldownMs: 11000,
  },
  {
    id: 'priest_guardian_light',
    job: 'priest',
    name: '수호의 빛',
    description: '수호의 빛이 마법 피해로부터 지켜줍니다. (마법방어 영구 +12)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 12,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_blessing_of_life',
    job: 'priest',
    name: '생명의 축복',
    description: '생명의 축복으로 큰 상처마저 아물게 합니다. (HP 85 회복)',
    requiredLevel: 32,
    kind: 'heal',
    mpCost: 38,
    power: 85,
    cooldownMs: 13000,
  },
  {
    id: 'priest_undying_will',
    job: 'priest',
    name: '불멸의 의지',
    description: '불멸의 의지로 육체가 강인해집니다. (최대 HP 영구 +40)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 40,
    passiveStat: 'maxHp',
  },
  {
    id: 'priest_light_of_resurrection',
    job: 'priest',
    name: '부활의 빛',
    description: '부활의 빛으로 죽음 직전의 상처도 되돌립니다. (HP 105 회복)',
    requiredLevel: 40,
    kind: 'heal',
    mpCost: 46,
    power: 105,
    cooldownMs: 15000,
  },
  {
    id: 'priest_gods_grace',
    job: 'priest',
    name: '신의 가호',
    description: '신의 가호를 받아 지혜가 더욱 깊어집니다. (지혜 영구 +12)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 12,
    passiveStat: 'wisdom',
  },
  {
    id: 'priest_heavenly_healing',
    job: 'priest',
    name: '천상의 치유',
    description: '천상의 빛으로 모든 상처를 치유합니다. (HP 130 회복)',
    requiredLevel: 47,
    kind: 'heal',
    mpCost: 56,
    power: 130,
    cooldownMs: 18000,
  },
  {
    id: 'priest_archangels_blessing',
    job: 'priest',
    name: '대천사의 축복',
    description: '대천사의 축복으로 육체의 한계를 넘어섭니다. (최대 HP 영구 +70)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 70,
    passiveStat: 'maxHp',
  },
];
