import { buildElementBranches } from './branches.js';
import type { SkillDefinition } from './types.js';

const PRIEST_TRUNK: SkillDefinition[] = [
  // 사제 — 회복/지원. 공통 트리(원소 무관, 순차 선행).
  {
    id: 'priest_heal',
    job: 'priest',
    name: '소생의 손길',
    description: '따뜻한 빛으로 상처를 치유합니다. (HP 12 회복)',
    requiredLevel: 1,
    kind: 'heal',
    mpCost: 6,
    power: 12,
    cooldownMs: 3000,
  },
  {
    id: 'priest_blessing',
    job: 'priest',
    name: '축복',
    description: '몸에 성스러운 가호를 두릅니다. (마법방어 영구 증가)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'magicDefense',
    requires: 'priest_heal',
  },
  {
    id: 'priest_greater_heal',
    job: 'priest',
    name: '신성한 빛',
    description: '강한 빛으로 큰 상처를 치유합니다. (HP 25 회복)',
    requiredLevel: 5,
    kind: 'heal',
    mpCost: 12,
    power: 25,
    cooldownMs: 6000,
    requires: 'priest_blessing',
  },
  {
    id: 'priest_endurance',
    job: 'priest',
    name: '인내',
    description: '고통을 견디는 법을 체득합니다. (최대 HP 영구 증가)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxHp',
    requires: 'priest_greater_heal',
  },
  {
    id: 'priest_healing_prayer',
    job: 'priest',
    name: '치유의 기도',
    description: '간절한 기도로 상처를 어루만집니다. (HP 38 회복)',
    requiredLevel: 11,
    kind: 'heal',
    mpCost: 18,
    power: 38,
    cooldownMs: 8000,
    requires: 'priest_endurance',
  },
  {
    id: 'priest_holy_patience',
    job: 'priest',
    name: '신성한 인내',
    description: '신성한 힘으로 마법 공격을 견뎌냅니다. (마법방어 영구 증가)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'magicDefense',
    requires: 'priest_healing_prayer',
  },
  {
    id: 'priest_wave_of_recovery',
    job: 'priest',
    name: '회복의 파동',
    description: '회복의 파동을 일으켜 상처를 씻어냅니다. (HP 52 회복)',
    requiredLevel: 17,
    kind: 'heal',
    mpCost: 24,
    power: 52,
    cooldownMs: 9500,
    requires: 'priest_holy_patience',
  },
  {
    id: 'priest_mental_fortitude',
    job: 'priest',
    name: '정신력 강화',
    description: '정신력을 단련해 지혜가 깊어집니다. (지혜 영구 증가)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
    requires: 'priest_wave_of_recovery',
  },
  {
    id: 'priest_divine_grace',
    job: 'priest',
    name: '성스러운 은총',
    description: '성스러운 은총이 온몸을 감싸며 치유합니다. (HP 68 회복)',
    requiredLevel: 24,
    kind: 'heal',
    mpCost: 30,
    power: 68,
    cooldownMs: 11000,
    requires: 'priest_mental_fortitude',
  },
];

const PRIEST_BRANCHES = buildElementBranches({
  job: 'priest',
  idPrefix: 'priest',
  tier1Kind: 'heal',
  trunkFinalSkillId: 'priest_divine_grace',
  themes: {
    wood: {
      tier1Name: '생명의 축복',
      tier1Description: '목 기운의 생명력을 담아 큰 상처를 치유합니다. (HP 회복)',
      tier2Name: '만물의 생명력',
      tier2Description: '목 기운이 육체 깊이 뿌리내려 생명력이 강해집니다. (체력 영구 증가)',
      passiveStat: 'vitality',
    },
    fire: {
      tier1Name: '불사조의 빛',
      tier1Description: '불사조의 온기를 담은 빛으로 큰 상처를 치유합니다. (HP 회복)',
      tier2Name: '타오르는 신앙',
      tier2Description: '화 기운이 신앙심을 밝혀 마법의 이해가 깊어집니다. (지능 영구 증가)',
      passiveStat: 'intelligence',
    },
    earth: {
      tier1Name: '대지의 치유',
      tier1Description: '대지의 기운을 빌려 큰 상처를 치유합니다. (HP 회복)',
      tier2Name: '대지의 축복',
      tier2Description: '토 기운이 몸을 감싸 마법 방벽을 두릅니다. (마법방어 영구 증가)',
      passiveStat: 'magicDefense',
    },
    metal: {
      tier1Name: '은빛 치유',
      tier1Description: '은빛으로 빛나는 신성한 힘으로 큰 상처를 치유합니다. (HP 회복)',
      tier2Name: '성스러운 갑주',
      tier2Description: '금 기운이 갑주처럼 몸을 감싸 육체가 튼튼해집니다. (최대 HP 영구 증가)',
      passiveStat: 'maxHp',
    },
    water: {
      tier1Name: '생명의 샘물',
      tier1Description: '맑은 샘물의 기운을 담아 큰 상처를 치유합니다. (HP 회복)',
      tier2Name: '심연의 자비',
      tier2Description: '수 기운이 마음을 가라앉혀 깊은 지혜를 얻습니다. (지혜 영구 증가)',
      passiveStat: 'wisdom',
    },
  },
});

export const PRIEST_SKILLS: SkillDefinition[] = [...PRIEST_TRUNK, ...PRIEST_BRANCHES];
