import { buildElementBranches } from './branches.js';
import type { SkillDefinition } from './types.js';

const ROGUE_TRUNK: SkillDefinition[] = [
  // 도적 — 민첩 물리 딜. 공통 트리(원소 무관, 순차 선행).
  {
    id: 'rogue_backstab',
    job: 'rogue',
    name: '급소 찌르기',
    description: '적의 급소를 정확히 노립니다. (물리 피해 1.8배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 5,
    power: 1.8,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 3500,
  },
  {
    id: 'rogue_shadow_step',
    job: 'rogue',
    name: '그림자 걸음',
    description: '그림자처럼 가볍게 움직입니다. (민첩 영구 증가)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 3,
    passiveStat: 'dexterity',
    requires: 'rogue_backstab',
  },
  {
    id: 'rogue_poison_strike',
    job: 'rogue',
    name: '맹독 일격',
    description: '맹독을 바른 무기로 적을 찌릅니다. (물리 피해 2.0배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 9,
    power: 2.0,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 7000,
    requires: 'rogue_shadow_step',
  },
  {
    id: 'rogue_deadly_precision',
    job: 'rogue',
    name: '백발백중',
    description: '치명적인 순간을 놓치지 않습니다. (행운 영구 증가)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'luck',
    requires: 'rogue_poison_strike',
  },
  {
    id: 'rogue_dagger_flurry',
    job: 'rogue',
    name: '연속 단검질',
    description: '양손의 단검으로 빠르게 연속해서 찌릅니다. (물리 피해 2.6배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 13,
    power: 2.6,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 9000,
    requires: 'rogue_deadly_precision',
  },
  {
    id: 'rogue_swift_feet',
    job: 'rogue',
    name: '쾌속 이동',
    description: '발걸음이 바람처럼 가벼워집니다. (민첩 영구 증가)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'dexterity',
    requires: 'rogue_dagger_flurry',
  },
  {
    id: 'rogue_shadow_raid',
    job: 'rogue',
    name: '그림자 습격',
    description: '그림자에 숨어 있다가 기습적으로 덮칩니다. (물리 피해 3.2배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 17,
    power: 3.2,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 11000,
    requires: 'rogue_swift_feet',
  },
  {
    id: 'rogue_beast_sense',
    job: 'rogue',
    name: '야수의 감각',
    description: '야수와 같은 감각으로 약점을 간파합니다. (행운 영구 증가)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'luck',
    requires: 'rogue_shadow_raid',
  },
  {
    id: 'rogue_stealth_ambush',
    job: 'rogue',
    name: '은신 기습',
    description: '완전히 몸을 숨겼다가 급습합니다. (물리 피해 3.8배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 22,
    power: 3.8,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 13000,
    requires: 'rogue_beast_sense',
  },
];

const ROGUE_BRANCHES = buildElementBranches({
  job: 'rogue',
  idPrefix: 'rogue',
  tier1Kind: 'damage',
  damageType: 'physical',
  trunkFinalSkillId: 'rogue_stealth_ambush',
  themes: {
    wood: {
      tier1Name: '가시덫 난사',
      tier1Description: '가시 덫을 사방에 뿌려 주변 적 전체에게 피해를 입힙니다. (물리 피해, 광역)',
      tier2Name: '은밀한 생명력',
      tier2Description: '목 기운이 은밀하게 몸에 스며들어 생명력이 강해집니다. (체력 영구 증가)',
      passiveStat: 'vitality',
    },
    fire: {
      tier1Name: '화염 표창',
      tier1Description: '불타는 표창을 흩뿌려 주변 적 전체를 가격합니다. (물리 피해, 광역)',
      tier2Name: '불타는 본능',
      tier2Description: '화 기운이 근력에 타올라 완력이 강해집니다. (힘 영구 증가)',
      passiveStat: 'strength',
    },
    earth: {
      tier1Name: '함정 폭발',
      tier1Description: '숨겨둔 함정을 일제히 터뜨려 주변 적 전체에게 피해를 입힙니다. (물리 피해, 광역)',
      tier2Name: '그림자 갑주',
      tier2Description: '토 기운이 그림자처럼 몸을 감싸 방어가 단단해집니다. (물리방어 영구 증가)',
      passiveStat: 'physicalDefense',
    },
    metal: {
      tier1Name: '칼날폭풍',
      tier1Description: '단검을 폭풍처럼 흩뿌려 주변 적 전체를 베어냅니다. (물리 피해, 광역)',
      tier2Name: '은신자의 육체',
      tier2Description: '금 기운이 뼈마디에 스며들어 육체가 단단해집니다. (최대 HP 영구 증가)',
      passiveStat: 'maxHp',
    },
    water: {
      tier1Name: '급류난도',
      tier1Description: '급류처럼 빠른 연속 베기로 주변 적 전체를 휩씁니다. (물리 피해, 광역)',
      tier2Name: '물처럼 유연함',
      tier2Description: '수 기운이 몸놀림에 스며들어 움직임이 물처럼 유연해집니다. (민첩 영구 증가)',
      passiveStat: 'dexterity',
    },
  },
});

export const ROGUE_SKILLS: SkillDefinition[] = [...ROGUE_TRUNK, ...ROGUE_BRANCHES];
