import type { SkillDefinition } from './types.js';

export const ROGUE_SKILLS: SkillDefinition[] = [
  // 도적 — 민첩 물리 딜
  {
    id: 'rogue_backstab',
    job: 'rogue',
    name: '급소 찌르기',
    description: '적의 급소를 정확히 노립니다. (물리 피해 1.8배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 5,
    power: 1.8,
    damageType: 'physical',
    cooldownMs: 3500,
  },
  {
    id: 'rogue_shadow_step',
    job: 'rogue',
    name: '그림자 걸음',
    description: '그림자처럼 가볍게 움직입니다. (민첩 영구 +3)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 3,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_poison_strike',
    job: 'rogue',
    name: '맹독 일격',
    description: '맹독을 바른 무기로 적을 찌릅니다. (물리 피해 2.0배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 9,
    power: 2.0,
    damageType: 'physical',
    cooldownMs: 7000,
  },
  {
    id: 'rogue_deadly_precision',
    job: 'rogue',
    name: '백발백중',
    description: '치명적인 순간을 놓치지 않습니다. (행운 영구 +5)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_dagger_flurry',
    job: 'rogue',
    name: '연속 단검질',
    description: '양손의 단검으로 빠르게 연속해서 찌릅니다. (물리 피해 2.6배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 13,
    power: 2.6,
    damageType: 'physical',
    cooldownMs: 9000,
  },
  {
    id: 'rogue_swift_feet',
    job: 'rogue',
    name: '쾌속 이동',
    description: '발걸음이 바람처럼 가벼워집니다. (민첩 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_shadow_raid',
    job: 'rogue',
    name: '그림자 습격',
    description: '그림자에 숨어 있다가 기습적으로 덮칩니다. (물리 피해 3.2배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 17,
    power: 3.2,
    damageType: 'physical',
    cooldownMs: 11000,
  },
  {
    id: 'rogue_beast_sense',
    job: 'rogue',
    name: '야수의 감각',
    description: '야수와 같은 감각으로 약점을 간파합니다. (행운 영구 +6)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_stealth_ambush',
    job: 'rogue',
    name: '은신 기습',
    description: '완전히 몸을 숨겼다가 급습합니다. (물리 피해 3.8배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 22,
    power: 3.8,
    damageType: 'physical',
    cooldownMs: 13000,
  },
  {
    id: 'rogue_assassins_instinct',
    job: 'rogue',
    name: '암살자의 본능',
    description: '암살자의 본능이 눈을 떠 움직임이 예리해집니다. (민첩 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_deadly_dance',
    job: 'rogue',
    name: '필살의 검무',
    description: '죽음의 춤을 추듯 연속 공격을 퍼붓습니다. (물리 피해 4.4배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 28,
    power: 4.4,
    damageType: 'physical',
    cooldownMs: 15000,
  },
  {
    id: 'rogue_coldblooded',
    job: 'rogue',
    name: '냉혹함',
    description: '냉혹한 판단력으로 치명적인 순간을 놓치지 않습니다. (행운 영구 +10)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_final_strike',
    job: 'rogue',
    name: '절명의 일격',
    description: '숨통을 끊는 결정적인 일격을 가합니다. (물리 피해 5.0배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 34,
    power: 5.0,
    damageType: 'physical',
    cooldownMs: 17000,
  },
  {
    id: 'rogue_shadow_pact',
    job: 'rogue',
    name: '그림자와의 계약',
    description: '그림자와 계약해 신체 능력이 한계를 넘어섭니다. (민첩 영구 +14)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 14,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_shadow_execution',
    job: 'rogue',
    name: '그림자 처형',
    description: '그림자 속에서 나타나 적을 처형합니다. (물리 피해 5.8배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 42,
    power: 5.8,
    damageType: 'physical',
    cooldownMs: 20000,
  },
  {
    id: 'rogue_lord_of_darkness',
    job: 'rogue',
    name: '어둠의 지배자',
    description: '어둠을 지배하는 존재로 거듭납니다. (행운 영구 +18)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 18,
    passiveStat: 'luck',
  },

];
