import { buildElementBranches } from './branches.js';
import type { SkillDefinition } from './types.js';

const WARRIOR_TRUNK: SkillDefinition[] = [
  // 전사 — 근접 물리 딜/탱. 공통 트리(원소 무관, 순차 선행).
  {
    id: 'warrior_power_strike',
    job: 'warrior',
    name: '강타',
    description: '힘을 실어 적을 강하게 내려칩니다. (물리 피해 1.6배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 4,
    power: 1.6,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 4000,
  },
  {
    id: 'warrior_iron_skin',
    job: 'warrior',
    name: '강철 피부',
    description: '피부를 강철처럼 단련합니다. (물리방어 영구 증가)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 4,
    passiveStat: 'physicalDefense',
    requires: 'warrior_power_strike',
  },
  {
    id: 'warrior_fury_slash',
    job: 'warrior',
    name: '맹공',
    description: '분노에 휩싸여 적을 연속으로 베어냅니다. (물리 피해 2.2배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 8,
    power: 2.2,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 8000,
    requires: 'warrior_iron_skin',
  },
  {
    id: 'warrior_vigor',
    job: 'warrior',
    name: '불굴',
    description: '강인한 육체로 버텨냅니다. (최대 HP 영구 증가)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 15,
    passiveStat: 'maxHp',
    requires: 'warrior_fury_slash',
  },
  {
    id: 'warrior_whirlwind_slash',
    job: 'warrior',
    name: '회전베기',
    description: '몸을 회전시켜 주변 적을 모두 베어냅니다. (물리 피해 2.8배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 12,
    power: 2.8,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 10000,
    requires: 'warrior_vigor',
  },
  {
    id: 'warrior_brute_force',
    job: 'warrior',
    name: '완력 강화',
    description: '근력을 극한까지 단련합니다. (힘 영구 증가)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'strength',
    requires: 'warrior_whirlwind_slash',
  },
  {
    id: 'warrior_shield_breaker',
    job: 'warrior',
    name: '파쇄격',
    description: '방패째로 부숴버리는 강력한 일격을 가합니다. (물리 피해 3.4배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 16,
    power: 3.4,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 12000,
    requires: 'warrior_brute_force',
  },
  {
    id: 'warrior_combat_instinct',
    job: 'warrior',
    name: '전투 본능',
    description: '수많은 전투로 몸이 반응 속도를 기억합니다. (민첩 영구 증가)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'dexterity',
    requires: 'warrior_shield_breaker',
  },
  {
    id: 'warrior_earth_crush',
    job: 'warrior',
    name: '대지분쇄',
    description: '대지를 내려찍어 충격파를 일으킵니다. (물리 피해 4.0배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 20,
    power: 4.0,
    damageType: 'physical',
    targeting: 'single',
    cooldownMs: 14000,
    requires: 'warrior_combat_instinct',
  },
];

const WARRIOR_BRANCHES = buildElementBranches({
  job: 'warrior',
  idPrefix: 'warrior',
  tier1Kind: 'damage',
  damageType: 'physical',
  trunkFinalSkillId: 'warrior_earth_crush',
  themes: {
    wood: {
      tier1Name: '덩굴 강타',
      tier1Description: '무기에 덩굴의 생명력을 둘러 주변 적을 모두 내려칩니다. (물리 피해, 광역)',
      tier2Name: '생명의 나무',
      tier2Description: '목 기운이 육체에 뿌리내려 생명력이 깊어집니다. (체력 영구 증가)',
      passiveStat: 'vitality',
    },
    fire: {
      tier1Name: '화염 난무',
      tier1Description: '검에 불꽃을 둘러 주변 적을 모두 베어냅니다. (물리 피해, 광역)',
      tier2Name: '투혼의 불꽃',
      tier2Description: '화 기운이 근육에 타올라 힘이 폭증합니다. (힘 영구 증가)',
      passiveStat: 'strength',
    },
    earth: {
      tier1Name: '지진 강타',
      tier1Description: '대지의 기운을 담아 내려쳐 주변 적을 모두 뒤흔듭니다. (물리 피해, 광역)',
      tier2Name: '철벽의 의지',
      tier2Description: '토 기운이 몸을 감싸 방어가 굳건해집니다. (물리방어 영구 증가)',
      passiveStat: 'physicalDefense',
    },
    metal: {
      tier1Name: '강철 폭풍',
      tier1Description: '강철 조각을 흩뿌리며 주변 적을 모두 베어냅니다. (물리 피해, 광역)',
      tier2Name: '무쇠의 육체',
      tier2Description: '금 기운이 뼈와 살에 스며들어 육체가 무쇠처럼 단단해집니다. (최대 HP 영구 증가)',
      passiveStat: 'maxHp',
    },
    water: {
      tier1Name: '해일 베기',
      tier1Description: '파도처럼 밀려드는 연속 베기로 주변 적을 모두 휩씁니다. (물리 피해, 광역)',
      tier2Name: '유수의 흐름',
      tier2Description: '수 기운이 몸놀림에 스며들어 움직임이 물처럼 유연해집니다. (민첩 영구 증가)',
      passiveStat: 'dexterity',
    },
  },
});

export const WARRIOR_SKILLS: SkillDefinition[] = [...WARRIOR_TRUNK, ...WARRIOR_BRANCHES];
