import type { SkillDefinition } from './types.js';

export const WARRIOR_SKILLS: SkillDefinition[] = [
  // 전사 — 근접 물리 딜/탱
  {
    id: 'warrior_power_strike',
    job: 'warrior',
    name: '강타',
    description: '힘을 실어 적을 강하게 내려칩니다. (물리 피해 1.6배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 4,
    power: 1.6,
    damageType: 'physical',
    cooldownMs: 4000,
  },
  {
    id: 'warrior_iron_skin',
    job: 'warrior',
    name: '강철 피부',
    description: '피부를 강철처럼 단련합니다. (물리방어 영구 +4)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 4,
    passiveStat: 'physicalDefense',
  },
  {
    id: 'warrior_fury_slash',
    job: 'warrior',
    name: '맹공',
    description: '분노에 휩싸여 적을 연속으로 베어냅니다. (물리 피해 2.2배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 8,
    power: 2.2,
    damageType: 'physical',
    cooldownMs: 8000,
  },
  {
    id: 'warrior_vigor',
    job: 'warrior',
    name: '불굴',
    description: '강인한 육체로 버텨냅니다. (최대 HP 영구 +15)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 15,
    passiveStat: 'maxHp',
  },
  {
    id: 'warrior_whirlwind_slash',
    job: 'warrior',
    name: '회전베기',
    description: '몸을 회전시켜 주변 적을 모두 베어냅니다. (물리 피해 2.8배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 12,
    power: 2.8,
    damageType: 'physical',
    cooldownMs: 10000,
  },
  {
    id: 'warrior_brute_force',
    job: 'warrior',
    name: '완력 강화',
    description: '근력을 극한까지 단련합니다. (힘 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'strength',
  },
  {
    id: 'warrior_shield_breaker',
    job: 'warrior',
    name: '파쇄격',
    description: '방패째로 부숴버리는 강력한 일격을 가합니다. (물리 피해 3.4배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 16,
    power: 3.4,
    damageType: 'physical',
    cooldownMs: 12000,
  },
  {
    id: 'warrior_combat_instinct',
    job: 'warrior',
    name: '전투 본능',
    description: '수많은 전투로 몸이 반응 속도를 기억합니다. (민첩 영구 +5)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'dexterity',
  },
  {
    id: 'warrior_earth_crush',
    job: 'warrior',
    name: '대지분쇄',
    description: '대지를 내려찍어 충격파를 일으킵니다. (물리 피해 4.0배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 20,
    power: 4.0,
    damageType: 'physical',
    cooldownMs: 14000,
  },
  {
    id: 'warrior_valor',
    job: 'warrior',
    name: '용맹',
    description: '용맹함이 몸을 감싸 방어력을 높입니다. (물리방어 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'physicalDefense',
  },
  {
    id: 'warrior_berserker_strike',
    job: 'warrior',
    name: '광전사의 일격',
    description: '이성을 내려놓고 광전사의 힘으로 내려칩니다. (물리 피해 4.6배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 26,
    power: 4.6,
    damageType: 'physical',
    cooldownMs: 16000,
  },
  {
    id: 'warrior_undying',
    job: 'warrior',
    name: '불사신',
    description: '죽음조차 두려워하지 않는 육체를 얻습니다. (최대 HP 영구 +35)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 35,
    passiveStat: 'maxHp',
  },
  {
    id: 'warrior_sword_of_ruin',
    job: 'warrior',
    name: '파멸의 검',
    description: '파멸을 부르는 검격을 내리꽂습니다. (물리 피해 5.2배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 32,
    power: 5.2,
    damageType: 'physical',
    cooldownMs: 18000,
  },
  {
    id: 'warrior_destructive_instinct',
    job: 'warrior',
    name: '파괴본능',
    description: '파괴 본능이 극에 달해 힘이 폭증합니다. (힘 영구 +14)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 14,
    passiveStat: 'strength',
  },
  {
    id: 'warrior_final_blow',
    job: 'warrior',
    name: '종언의 일격',
    description: '모든 힘을 쏟아부어 최후의 일격을 가합니다. (물리 피해 6.0배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 40,
    power: 6.0,
    damageType: 'physical',
    cooldownMs: 22000,
  },
  {
    id: 'warrior_battlefield_ruler',
    job: 'warrior',
    name: '전장의 지배자',
    description: '전장을 지배하는 존재감으로 육체가 완성됩니다. (최대 HP 영구 +60)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 60,
    passiveStat: 'maxHp',
  },

];
