import { JOB_VALUES, type JobType } from './jobs.js';

export type SkillKind = 'damage' | 'heal' | 'passive';
export type SkillDamageType = 'physical' | 'magic';

export type PassiveStat =
  | 'maxHp'
  | 'maxMp'
  | 'physicalDefense'
  | 'magicDefense'
  | 'strength'
  | 'dexterity'
  | 'intelligence'
  | 'vitality'
  | 'wisdom'
  | 'luck';

export interface SkillDefinition {
  id: string;
  job: JobType;
  name: string;
  description: string;
  requiredLevel: number;
  kind: SkillKind;
  /** damage/heal 스킬에 필요한 MP. passive 스킬은 습득 즉시 적용되며 MP를 소모하지 않는다. */
  mpCost: number;
  /** damage: 공격 스탯(힘/지능) 배율. heal: 고정 회복량. passive: 스탯 고정 증가량. */
  power: number;
  /** kind가 'damage'일 때 어떤 공격 스탯/방어 스탯을 사용할지 결정. */
  damageType?: SkillDamageType;
  /** kind가 'passive'일 때 어떤 스탯에 영구 적용할지. */
  passiveStat?: PassiveStat;
  /** damage/heal 스킬의 재사용 대기시간(ms). */
  cooldownMs?: number;
}

export const SKILLS: SkillDefinition[] = [
  // 전사 — 근접 물리 딜/탱
  {
    id: 'warrior_power_strike',
    job: 'warrior',
    name: '강타',
    description: '힘을 실어 적을 강하게 내려칩니다. (물리 피해 1.6배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 4,
    power: 1.6,
    damageType: 'physical',
    cooldownMs: 4000,
  },
  {
    id: 'warrior_iron_skin',
    job: 'warrior',
    name: '강철 피부',
    description: '피부를 강철처럼 단련합니다. (물리방어 영구 +4)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 4,
    passiveStat: 'physicalDefense',
  },
  {
    id: 'warrior_fury_slash',
    job: 'warrior',
    name: '맹공',
    description: '분노에 휩싸여 적을 연속으로 베어냅니다. (물리 피해 2.2배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 8,
    power: 2.2,
    damageType: 'physical',
    cooldownMs: 8000,
  },
  {
    id: 'warrior_vigor',
    job: 'warrior',
    name: '불굴',
    description: '강인한 육체로 버텨냅니다. (최대 HP 영구 +15)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 15,
    passiveStat: 'maxHp',
  },
  {
    id: 'warrior_whirlwind_slash',
    job: 'warrior',
    name: '회전베기',
    description: '몸을 회전시켜 주변 적을 모두 베어냅니다. (물리 피해 2.8배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 12,
    power: 2.8,
    damageType: 'physical',
    cooldownMs: 10000,
  },
  {
    id: 'warrior_brute_force',
    job: 'warrior',
    name: '완력 강화',
    description: '근력을 극한까지 단련합니다. (힘 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'strength',
  },
  {
    id: 'warrior_shield_breaker',
    job: 'warrior',
    name: '파쇄격',
    description: '방패째로 부숴버리는 강력한 일격을 가합니다. (물리 피해 3.4배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 16,
    power: 3.4,
    damageType: 'physical',
    cooldownMs: 12000,
  },
  {
    id: 'warrior_combat_instinct',
    job: 'warrior',
    name: '전투 본능',
    description: '수많은 전투로 몸이 반응 속도를 기억합니다. (민첩 영구 +5)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'dexterity',
  },
  {
    id: 'warrior_earth_crush',
    job: 'warrior',
    name: '대지분쇄',
    description: '대지를 내려찍어 충격파를 일으킵니다. (물리 피해 4.0배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 20,
    power: 4.0,
    damageType: 'physical',
    cooldownMs: 14000,
  },
  {
    id: 'warrior_valor',
    job: 'warrior',
    name: '용맹',
    description: '용맹함이 몸을 감싸 방어력을 높입니다. (물리방어 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'physicalDefense',
  },
  {
    id: 'warrior_berserker_strike',
    job: 'warrior',
    name: '광전사의 일격',
    description: '이성을 내려놓고 광전사의 힘으로 내려칩니다. (물리 피해 4.6배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 26,
    power: 4.6,
    damageType: 'physical',
    cooldownMs: 16000,
  },
  {
    id: 'warrior_undying',
    job: 'warrior',
    name: '불사신',
    description: '죽음조차 두려워하지 않는 육체를 얻습니다. (최대 HP 영구 +35)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 35,
    passiveStat: 'maxHp',
  },
  {
    id: 'warrior_sword_of_ruin',
    job: 'warrior',
    name: '파멸의 검',
    description: '파멸을 부르는 검격을 내리꽂습니다. (물리 피해 5.2배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 32,
    power: 5.2,
    damageType: 'physical',
    cooldownMs: 18000,
  },
  {
    id: 'warrior_destructive_instinct',
    job: 'warrior',
    name: '파괴본능',
    description: '파괴 본능이 극에 달해 힘이 폭증합니다. (힘 영구 +14)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 14,
    passiveStat: 'strength',
  },
  {
    id: 'warrior_final_blow',
    job: 'warrior',
    name: '종언의 일격',
    description: '모든 힘을 쏟아부어 최후의 일격을 가합니다. (물리 피해 6.0배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 40,
    power: 6.0,
    damageType: 'physical',
    cooldownMs: 22000,
  },
  {
    id: 'warrior_battlefield_ruler',
    job: 'warrior',
    name: '전장의 지배자',
    description: '전장을 지배하는 존재감으로 육체가 완성됩니다. (최대 HP 영구 +60)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 60,
    passiveStat: 'maxHp',
  },

  // 도적 — 민첩 물리 딜
  {
    id: 'rogue_backstab',
    job: 'rogue',
    name: '급소 찌르기',
    description: '적의 급소를 정확히 노립니다. (물리 피해 1.8배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 5,
    power: 1.8,
    damageType: 'physical',
    cooldownMs: 3500,
  },
  {
    id: 'rogue_shadow_step',
    job: 'rogue',
    name: '그림자 걸음',
    description: '그림자처럼 가볍게 움직입니다. (민첩 영구 +3)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 3,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_poison_strike',
    job: 'rogue',
    name: '맹독 일격',
    description: '맹독을 바른 무기로 적을 찌릅니다. (물리 피해 2.0배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 9,
    power: 2.0,
    damageType: 'physical',
    cooldownMs: 7000,
  },
  {
    id: 'rogue_deadly_precision',
    job: 'rogue',
    name: '백발백중',
    description: '치명적인 순간을 놓치지 않습니다. (행운 영구 +5)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_dagger_flurry',
    job: 'rogue',
    name: '연속 단검질',
    description: '양손의 단검으로 빠르게 연속해서 찌릅니다. (물리 피해 2.6배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 13,
    power: 2.6,
    damageType: 'physical',
    cooldownMs: 9000,
  },
  {
    id: 'rogue_swift_feet',
    job: 'rogue',
    name: '쾌속 이동',
    description: '발걸음이 바람처럼 가벼워집니다. (민첩 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_shadow_raid',
    job: 'rogue',
    name: '그림자 습격',
    description: '그림자에 숨어 있다가 기습적으로 덮칩니다. (물리 피해 3.2배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 17,
    power: 3.2,
    damageType: 'physical',
    cooldownMs: 11000,
  },
  {
    id: 'rogue_beast_sense',
    job: 'rogue',
    name: '야수의 감각',
    description: '야수와 같은 감각으로 약점을 간파합니다. (행운 영구 +6)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_stealth_ambush',
    job: 'rogue',
    name: '은신 기습',
    description: '완전히 몸을 숨겼다가 급습합니다. (물리 피해 3.8배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 22,
    power: 3.8,
    damageType: 'physical',
    cooldownMs: 13000,
  },
  {
    id: 'rogue_assassins_instinct',
    job: 'rogue',
    name: '암살자의 본능',
    description: '암살자의 본능이 눈을 떠 움직임이 예리해집니다. (민첩 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_deadly_dance',
    job: 'rogue',
    name: '필살의 검무',
    description: '죽음의 춤을 추듯 연속 공격을 퍼붓습니다. (물리 피해 4.4배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 28,
    power: 4.4,
    damageType: 'physical',
    cooldownMs: 15000,
  },
  {
    id: 'rogue_coldblooded',
    job: 'rogue',
    name: '냉혹함',
    description: '냉혹한 판단력으로 치명적인 순간을 놓치지 않습니다. (행운 영구 +10)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'luck',
  },
  {
    id: 'rogue_final_strike',
    job: 'rogue',
    name: '절명의 일격',
    description: '숨통을 끊는 결정적인 일격을 가합니다. (물리 피해 5.0배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 34,
    power: 5.0,
    damageType: 'physical',
    cooldownMs: 17000,
  },
  {
    id: 'rogue_shadow_pact',
    job: 'rogue',
    name: '그림자와의 계약',
    description: '그림자와 계약해 신체 능력이 한계를 넘어섭니다. (민첩 영구 +14)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 14,
    passiveStat: 'dexterity',
  },
  {
    id: 'rogue_shadow_execution',
    job: 'rogue',
    name: '그림자 처형',
    description: '그림자 속에서 나타나 적을 처형합니다. (물리 피해 5.8배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 42,
    power: 5.8,
    damageType: 'physical',
    cooldownMs: 20000,
  },
  {
    id: 'rogue_lord_of_darkness',
    job: 'rogue',
    name: '어둠의 지배자',
    description: '어둠을 지배하는 존재로 거듭납니다. (행운 영구 +18)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 18,
    passiveStat: 'luck',
  },

  // 마법사 — 원거리 마법 딜
  {
    id: 'mage_firebolt',
    job: 'mage',
    name: '파이어볼',
    description: '불꽃 구체를 쏘아 보냅니다. (마법 피해 2.0배)',
    requiredLevel: 1,
    kind: 'damage',
    mpCost: 6,
    power: 2.0,
    damageType: 'magic',
    cooldownMs: 4000,
  },
  {
    id: 'mage_mana_flow',
    job: 'mage',
    name: '마나 순환',
    description: '마나 회로를 확장합니다. (최대 MP 영구 +10)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxMp',
  },
  {
    id: 'mage_ice_lance',
    job: 'mage',
    name: '얼음창',
    description: '얼음 창을 꿰뚫듯 발사합니다. (마법 피해 2.6배)',
    requiredLevel: 5,
    kind: 'damage',
    mpCost: 10,
    power: 2.6,
    damageType: 'magic',
    cooldownMs: 8000,
  },
  {
    id: 'mage_arcane_mastery',
    job: 'mage',
    name: '대마법',
    description: '마법 이해도가 극에 달합니다. (지능 영구 +8)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_lightning_arrow',
    job: 'mage',
    name: '번개화살',
    description: '번개를 화살처럼 압축해 발사합니다. (마법 피해 3.2배)',
    requiredLevel: 11,
    kind: 'damage',
    mpCost: 14,
    power: 3.2,
    damageType: 'magic',
    cooldownMs: 9500,
  },
  {
    id: 'mage_mind_discipline',
    job: 'mage',
    name: '정신 수양',
    description: '정신을 수양해 마법에 대한 이해를 넓힙니다. (지혜 영구 +6)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
  },
  {
    id: 'mage_earth_spikes',
    job: 'mage',
    name: '대지가시',
    description: '땅에서 날카로운 가시를 솟구치게 합니다. (마법 피해 3.8배)',
    requiredLevel: 17,
    kind: 'damage',
    mpCost: 18,
    power: 3.8,
    damageType: 'magic',
    cooldownMs: 11000,
  },
  {
    id: 'mage_mana_engraving',
    job: 'mage',
    name: '마력 각인',
    description: '마법 회로를 몸에 각인시킵니다. (지능 영구 +10)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_firestorm',
    job: 'mage',
    name: '화염폭풍',
    description: '불의 폭풍을 일으켜 광범위하게 태웁니다. (마법 피해 4.6배)',
    requiredLevel: 24,
    kind: 'damage',
    mpCost: 24,
    power: 4.6,
    damageType: 'magic',
    cooldownMs: 13500,
  },
  {
    id: 'mage_abyssal_wisdom',
    job: 'mage',
    name: '심연의 지혜',
    description: '심연의 지혜를 받아들여 마력이 깊어집니다. (지혜 영구 +10)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'wisdom',
  },
  {
    id: 'mage_absolute_zero',
    job: 'mage',
    name: '절대영도',
    description: '주변을 절대영도까지 얼려버립니다. (마법 피해 5.4배)',
    requiredLevel: 32,
    kind: 'damage',
    mpCost: 30,
    power: 5.4,
    damageType: 'magic',
    cooldownMs: 16000,
  },
  {
    id: 'mage_mana_well',
    job: 'mage',
    name: '마나의 샘',
    description: '끝없이 샘솟는 마나의 우물을 엽니다. (최대 MP 영구 +40)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 40,
    passiveStat: 'maxMp',
  },
  {
    id: 'mage_meteor_fall',
    job: 'mage',
    name: '운석낙하',
    description: '하늘에서 운석을 불러 떨어뜨립니다. (마법 피해 6.2배)',
    requiredLevel: 40,
    kind: 'damage',
    mpCost: 38,
    power: 6.2,
    damageType: 'magic',
    cooldownMs: 19000,
  },
  {
    id: 'mage_archsage_insight',
    job: 'mage',
    name: '대현자의 통찰',
    description: '대현자의 통찰을 얻어 마법이 정교해집니다. (지능 영구 +16)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 16,
    passiveStat: 'intelligence',
  },
  {
    id: 'mage_annihilation',
    job: 'mage',
    name: '멸계의 마법',
    description: '세상을 소멸시킬 듯한 궁극의 마법을 시전합니다. (마법 피해 7.2배)',
    requiredLevel: 47,
    kind: 'damage',
    mpCost: 48,
    power: 7.2,
    damageType: 'magic',
    cooldownMs: 23000,
  },
  {
    id: 'mage_world_tree_blessing',
    job: 'mage',
    name: '세계수의 가호',
    description: '세계수의 가호를 받아 마나의 그릇이 무한히 커집니다. (최대 MP 영구 +70)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 70,
    passiveStat: 'maxMp',
  },

  // 사제 — 회복/지원
  {
    id: 'priest_heal',
    job: 'priest',
    name: '소생의 손길',
    description: '따뜻한 빛으로 상처를 치유합니다. (HP 12 회복)',
    requiredLevel: 1,
    kind: 'heal',
    mpCost: 6,
    power: 12,
    cooldownMs: 3000,
  },
  {
    id: 'priest_blessing',
    job: 'priest',
    name: '축복',
    description: '몸에 성스러운 가호를 두릅니다. (마법방어 영구 +5)',
    requiredLevel: 3,
    kind: 'passive',
    mpCost: 0,
    power: 5,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_greater_heal',
    job: 'priest',
    name: '신성한 빛',
    description: '강한 빛으로 큰 상처를 치유합니다. (HP 25 회복)',
    requiredLevel: 5,
    kind: 'heal',
    mpCost: 12,
    power: 25,
    cooldownMs: 6000,
  },
  {
    id: 'priest_endurance',
    job: 'priest',
    name: '인내',
    description: '고통을 견디는 법을 체득합니다. (최대 HP 영구 +10)',
    requiredLevel: 8,
    kind: 'passive',
    mpCost: 0,
    power: 10,
    passiveStat: 'maxHp',
  },
  {
    id: 'priest_healing_prayer',
    job: 'priest',
    name: '치유의 기도',
    description: '간절한 기도로 상처를 어루만집니다. (HP 38 회복)',
    requiredLevel: 11,
    kind: 'heal',
    mpCost: 18,
    power: 38,
    cooldownMs: 8000,
  },
  {
    id: 'priest_holy_patience',
    job: 'priest',
    name: '신성한 인내',
    description: '신성한 힘으로 마법 공격을 견뎌냅니다. (마법방어 영구 +8)',
    requiredLevel: 14,
    kind: 'passive',
    mpCost: 0,
    power: 8,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_wave_of_recovery',
    job: 'priest',
    name: '회복의 파동',
    description: '회복의 파동을 일으켜 상처를 씻어냅니다. (HP 52 회복)',
    requiredLevel: 17,
    kind: 'heal',
    mpCost: 24,
    power: 52,
    cooldownMs: 9500,
  },
  {
    id: 'priest_mental_fortitude',
    job: 'priest',
    name: '정신력 강화',
    description: '정신력을 단련해 지혜가 깊어집니다. (지혜 영구 +6)',
    requiredLevel: 20,
    kind: 'passive',
    mpCost: 0,
    power: 6,
    passiveStat: 'wisdom',
  },
  {
    id: 'priest_divine_grace',
    job: 'priest',
    name: '성스러운 은총',
    description: '성스러운 은총이 온몸을 감싸며 치유합니다. (HP 68 회복)',
    requiredLevel: 24,
    kind: 'heal',
    mpCost: 30,
    power: 68,
    cooldownMs: 11000,
  },
  {
    id: 'priest_guardian_light',
    job: 'priest',
    name: '수호의 빛',
    description: '수호의 빛이 마법 피해로부터 지켜줍니다. (마법방어 영구 +12)',
    requiredLevel: 28,
    kind: 'passive',
    mpCost: 0,
    power: 12,
    passiveStat: 'magicDefense',
  },
  {
    id: 'priest_blessing_of_life',
    job: 'priest',
    name: '생명의 축복',
    description: '생명의 축복으로 큰 상처마저 아물게 합니다. (HP 85 회복)',
    requiredLevel: 32,
    kind: 'heal',
    mpCost: 38,
    power: 85,
    cooldownMs: 13000,
  },
  {
    id: 'priest_undying_will',
    job: 'priest',
    name: '불멸의 의지',
    description: '불멸의 의지로 육체가 강인해집니다. (최대 HP 영구 +40)',
    requiredLevel: 36,
    kind: 'passive',
    mpCost: 0,
    power: 40,
    passiveStat: 'maxHp',
  },
  {
    id: 'priest_light_of_resurrection',
    job: 'priest',
    name: '부활의 빛',
    description: '부활의 빛으로 죽음 직전의 상처도 되돌립니다. (HP 105 회복)',
    requiredLevel: 40,
    kind: 'heal',
    mpCost: 46,
    power: 105,
    cooldownMs: 15000,
  },
  {
    id: 'priest_gods_grace',
    job: 'priest',
    name: '신의 가호',
    description: '신의 가호를 받아 지혜가 더욱 깊어집니다. (지혜 영구 +12)',
    requiredLevel: 44,
    kind: 'passive',
    mpCost: 0,
    power: 12,
    passiveStat: 'wisdom',
  },
  {
    id: 'priest_heavenly_healing',
    job: 'priest',
    name: '천상의 치유',
    description: '천상의 빛으로 모든 상처를 치유합니다. (HP 130 회복)',
    requiredLevel: 47,
    kind: 'heal',
    mpCost: 56,
    power: 130,
    cooldownMs: 18000,
  },
  {
    id: 'priest_archangels_blessing',
    job: 'priest',
    name: '대천사의 축복',
    description: '대천사의 축복으로 육체의 한계를 넘어섭니다. (최대 HP 영구 +70)',
    requiredLevel: 50,
    kind: 'passive',
    mpCost: 0,
    power: 70,
    passiveStat: 'maxHp',
  },
];

export const SKILLS_BY_JOB: Record<JobType, SkillDefinition[]> = Object.fromEntries(
  JOB_VALUES.map((job) => [job, SKILLS.filter((skill) => skill.job === job)]),
) as Record<JobType, SkillDefinition[]>;

export function getSkillById(id: string): SkillDefinition | undefined {
  return SKILLS.find((skill) => skill.id === id);
}
