import type { ItemSeed } from '../types.js';

export const EPIC_ITEMS: ItemSeed[] = [
  {
    id: 28,
    name: '종말의 검',
    description: '칠흑처럼 검은 칼날에 붉은 균열이 번개처럼 뻗어 있는 거대한 검이다. 칼끝에서 옅은 검은 안개가 스며 나오고, 손잡이에는 해골 모양의 장식이 새겨져 있다. 휘두를 때마다 주변 공기가 일그러지는 듯한 압도적인 존재감을 뿜어내며, 검신 전체에서 낮은 울림이 맴돌아 보는 이를 위축시키는 불길한 기운을 풍긴다.',
    type: 'weapon',
    slot: 'weapon',
    level: 50,
    grade: 'epic',
    strengthBonus: 30,
    attackPowerBonus: 80,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 1200,
  },
  {
    id: 29,
    name: '창세의 방패',
    description: '세상의 시작을 목격했다는 전설의 방패로, 표면에 우주를 닮은 짙은 남색과 별빛 같은 반점이 흩뿌려져 있다. 가장자리는 황금빛으로 둘러져 있고, 중앙에는 거대한 눈 모양 문양이 새겨져 은은한 빛을 내뿜는다. 방패를 들면 주위 공간이 미세하게 일그러지는 듯한 신비로움이 감돌며, 별들이 표면 위를 천천히 흐른다.',
    type: 'armor',
    slot: 'shield',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 20,
    magicDefenseBonus: 15,
    healAmount: 0,
    manaAmount: 0,
    value: 1100,
  },
  {
    id: 30,
    name: '신들의 축복 물약',
    description: '황금빛 액체가 성스러운 광채를 내뿜으며 담긴 화려한 유리병이다. 병 전체가 순금으로 세공된 테두리로 감싸여 있고, 마개에는 작은 날개 장식이 달려 있다. 액체 표면 위로 빛의 입자가 끊임없이 솟아오르며, 병을 든 손끝까지 신성한 온기가 스며드는 듯한 기운을 흩뿌려 주위를 은은한 광채로 물들인다.',
    type: 'consumable',
    slot: null,
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 300,
    manaAmount: 0,
    value: 600,
  },
  {
    id: 31,
    name: '무한의 반지',
    description: '끊임없이 색이 변하는 신비로운 보석이 박힌 반지로, 반지 표면에는 무한을 상징하는 뫼비우스 문양이 새겨져 있다. 착용하면 손끝에서 옅은 빛의 소용돌이가 일렁이며, 보석 속에서 은하수처럼 작은 별들이 흐른다. 우주의 힘이 응축된 듯한 압도적인 존재감을 풍기며, 보는 각도에 따라 빛깔이 끊임없이 변화한다.',
    type: 'armor',
    slot: 'ring',
    level: 50,
    grade: 'epic',
    strengthBonus: 10,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 56,
    name: '창세의 투구',
    description: '세상이 창조될 때부터 존재했다는 투구로, 표면에 우주의 별자리를 닮은 무늬가 새겨져 있다. 이마 부분에는 황금빛 뿔이 솟아 있고, 눈구멍에서 은은한 백색 빛이 새어 나온다. 정수리를 따라 흐르는 문양이 은하수처럼 반짝이며 신성하고 압도적인 존재감을 풍기고, 착용자 주위로 옅은 빛무리가 감돈다.',
    type: 'armor',
    slot: 'hat',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 25,
    magicDefenseBonus: 18,
    healAmount: 0,
    manaAmount: 0,
    value: 950,
  },
  {
    id: 57,
    name: '태초의 귀걸이',
    description: '태초의 힘이 깃든 귀걸이로, 투명한 보석 속에서 작은 은하가 소용돌이치듯 빛난다. 걸이 부분은 순금으로 세공되어 있으며, 보석 주위로 옅은 빛의 파동이 끊임없이 퍼져나간다. 가까이 다가서면 시공이 일렁이는 듯한 신비롭고 압도적인 존재감을 풍기며, 태초의 정적을 담은 듯 고요히 빛난다.',
    type: 'armor',
    slot: 'earring',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 22,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 58,
    name: '영원의 목걸이',
    description: '영원히 빛바래지 않는다는 목걸이로, 중앙의 보석이 무지갯빛으로 끊임없이 일렁인다. 목걸이 줄은 순금과 은이 교차하며 엮여 있고, 보석 표면에는 시간을 상징하는 나선 문양이 새겨져 있다. 보석 속 빛이 과거와 미래를 넘나들 듯 천천히 흐르며 시대를 초월한 신비로움을 자아내고, 착용자의 숨결에 맞춰 은은히 맥동한다.',
    type: 'armor',
    slot: 'necklace',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 28,
    healAmount: 0,
    manaAmount: 0,
    value: 980,
  },
  {
    id: 59,
    name: '창세의 갑옷',
    description: '세상이 창조될 때부터 존재했다는 갑옷으로, 표면 전체에 별자리와 은하수 같은 무늬가 흐른다. 가슴판 중앙에는 거대한 황금빛 문장이 새겨져 있고, 갑옷 전체에서 은은한 백색 광채가 뿜어져 나온다. 어깨와 팔 관절마다 정교한 별무늬 장식이 이어져 압도적인 존재감을 드러내며, 갑옷 자락이 별빛처럼 흩날린다.',
    type: 'armor',
    slot: 'top',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 30,
    magicDefenseBonus: 22,
    healAmount: 0,
    manaAmount: 0,
    value: 1150,
  },
  {
    id: 60,
    name: '창세의 각반',
    description: '세상이 창조될 때부터 존재했다는 각반으로, 표면에 별빛처럼 반짝이는 미세한 입자들이 흩뿌려져 있다. 무릎 보호대 부분에는 황금빛 문양이 돋을새김되어 있고, 움직일 때마다 옅은 빛의 잔상이 발걸음을 따라온다. 발목 부분은 은하수처럼 흐르는 무늬로 마감되어 있으며, 걸을 때마다 별가루가 흩날리는 듯하다.',
    type: 'armor',
    slot: 'bottom',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 920,
  },
  {
    id: 61,
    name: '파멸의 장갑',
    description: '닿는 모든 것을 파멸로 이끈다는 장갑으로, 손등 전체가 검붉은 균열무늬로 뒤덮여 있다. 손가락 끝에서는 옅은 검은 안개가 스며 나오고, 주먹을 쥘 때마다 균열 사이로 붉은 빛이 번쩍인다. 손목 부분에는 파멸을 상징하는 뒤틀린 문양이 새겨져 압도적이고 불길한 존재감을 풍기며, 가까이 다가서면 뼈가 시릴 듯한 냉기가 감돈다.',
    type: 'armor',
    slot: 'gloves',
    level: 50,
    grade: 'epic',
    strengthBonus: 22,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 900,
  },
  {
    id: 67,
    name: '종말의 지팡이',
    description: '칠흑처럼 검은 지팡이에 붉은 균열이 번개처럼 뻗어 있으며, 머리에 박힌 수정에서 검은 안개가 스며 나온다. 마력을 담을 때마다 주변 공기가 일그러지는 듯한 압도적인 존재감을 뿜어내고, 낮은 울림이 맴돌아 보는 이를 위축시키는 불길한 기운을 풍긴다.',
    type: 'weapon',
    slot: 'weapon',
    level: 50,
    grade: 'epic',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 80,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 1200,
  },
];
