import type { ItemSeed } from '../types.js';

export const HIGH_ITEMS: ItemSeed[] = [
  {
    id: 16,
    name: '미스릴 검',
    description: '은백색으로 빛나는 미스릴로 벼려낸 얇고 가벼운 검이다. 칼날은 거의 투명에 가까운 광택을 띠며, 빛을 받으면 무지갯빛으로 은은하게 반사된다. 칼자루에는 정교한 덩굴무늬가 새겨져 있고, 손잡이 끝에는 작은 푸른 보석이 박혀 있어 휘두를 때마다 옅은 빛의 궤적을 남긴다. 손에 쥐면 놀랍도록 가볍고 균형이 완벽하게 잡혀 있다.',
    type: 'weapon',
    slot: 'weapon',
    level: 10,
    grade: 'high',
    strengthBonus: 8,
    attackPowerBonus: 18,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 17,
    name: '기사의 갑옷',
    description: '정교하게 세공된 은빛 판금 갑옷으로, 가슴판 중앙에 왕실 문장이 돋을새김되어 있다. 어깨 부분은 굴곡진 곡선으로 다듬어졌고, 이음새마다 가는 금빛 테두리가 둘러져 있다. 전체적으로 매끈하게 광이 나며 관절 부위마다 정교한 힌지 구조가 드러나 기사단의 위엄이 느껴지는 디자인이다. 갑옷 전체가 은은한 백색 빛을 머금은 듯 청결하다.',
    type: 'armor',
    slot: 'top',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 6,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 80,
  },
  {
    id: 18,
    name: '상급 회복 물약',
    description: '짙은 붉은빛 액체가 소용돌이치듯 담긴 유리병으로, 병 표면에는 작은 십자 문양이 돋을새김되어 있다. 마개는 금색 금속으로 만들어졌고, 병을 기울이면 액체가 걸쭉하게 흘러내리며 은은한 빛의 잔상을 남긴다. 병목에는 성직자의 문양이 새겨진 작은 태그가 매달려 있어 신성한 축복이 담긴 듯한 정갈한 인상을 준다.',
    type: 'consumable',
    slot: null,
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 40,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 19,
    name: '은빛 반지',
    description: '얇은 은빛 밴드에 작은 보석이 촘촘히 박힌 반지다. 반지 표면을 따라 물결무늬가 새겨져 있고, 보석들은 움직일 때마다 옅은 은빛 잔광을 남긴다. 세공이 매우 정교해 착용자의 민첩함을 상징하듯 가벼운 인상을 주며, 반지 안쪽에는 작은 별자리 문양이 숨겨져 있어 손을 뒤집을 때마다 은밀하게 반짝인다.',
    type: 'armor',
    slot: 'ring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 70,
  },
  {
    id: 38,
    name: '기사의 방패',
    description: '왕실 기사단의 문장이 새겨진 정교한 강철 방패로, 표면은 은빛으로 매끄럽게 광이 난다. 가장자리를 따라 가는 금빛 테두리가 둘러져 있고, 중앙의 문장 부분은 살짝 돋을새김되어 있어 빛을 받으면 입체적으로 도드라진다. 뒷면에는 팔뚝 전체를 감싸는 가죽 벨트가 달려 있어 견고한 착용감을 더한다.',
    type: 'armor',
    slot: 'shield',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 75,
  },
  {
    id: 39,
    name: '기사의 투구',
    description: '왕실 기사단이 착용하던 투구로, 이마 부분에 작은 깃털 장식이 달려 있다. 표면은 은빛으로 매끄럽게 다듬어졌고, 얼굴을 가리는 부분에는 가는 창살무늬가 새겨져 있다. 정수리에서 뒷목까지 이어지는 곡선이 유려하며, 절제되고 기품 있는 디자인이 돋보이는 지휘관급 장비다.',
    type: 'armor',
    slot: 'hat',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 5,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 65,
  },
  {
    id: 40,
    name: '사파이어 귀걸이',
    description: '짙은 푸른빛 사파이어가 박힌 귀걸이로, 보석 주위를 은사가 섬세하게 감싸고 있다. 보석 표면은 매끄럽게 연마되어 빛을 받으면 깊은 청색 광채를 내뿜는다. 걸이 부분에는 작은 별 모양 장식이 함께 달려 있어 걸을 때마다 은은하게 반짝이며, 보석 속에서 옅은 빛줄기가 소용돌이친다.',
    type: 'armor',
    slot: 'earring',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 5,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  {
    id: 41,
    name: '마법사의 목걸이',
    description: '은사슬에 옅은 남색 마법석이 매달린 목걸이로, 돌 표면에 정교한 마법진이 새겨져 있다. 착용하면 돌 주위로 옅은 마력의 빛이 원을 그리며 감돌고, 목걸이 줄은 가늘고 촘촘하게 엮여 우아한 느낌을 준다. 돌 안쪽에서 별자리처럼 작은 빛 점이 반짝이며 은은한 지성의 기운을 드러낸다.',
    type: 'armor',
    slot: 'necklace',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 7,
    healAmount: 0,
    manaAmount: 0,
    value: 68,
  },
  {
    id: 42,
    name: '기사의 각반',
    description: '왕실 기사단이 착용하던 견고한 각반으로, 무릎과 정강이 부분이 이중 강철판으로 보강되어 있다. 표면은 은빛으로 광이 나며 가장자리에 가는 금빛 선이 둘러져 있다. 다리 움직임에 맞춰 유연하게 접히는 관절부가 특징이며 발목 부분은 가죽으로 마감되어 있어 기품과 실용성을 동시에 갖췄다.',
    type: 'armor',
    slot: 'bottom',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 62,
  },
  {
    id: 43,
    name: '사냥꾼의 장갑',
    description: '가벼운 갈색 가죽에 강철 조각을 덧댄 사냥꾼용 장갑이다. 손가락 끝부분은 활시위를 다루기 쉽도록 얇게 재단되어 있고, 손등에는 작은 매 문양이 새겨져 있다. 손목 부분은 끈으로 조이게 되어 있으며 전체적으로 실용성과 민첩함을 강조한 디자인이다. 손바닥 부분은 미끄럼 방지 가공이 되어 있다.',
    type: 'armor',
    slot: 'gloves',
    level: 10,
    grade: 'high',
    strengthBonus: 4,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 60,
  },
  {
    id: 64,
    name: '미스릴 지팡이',
    description: '은백색 미스릴로 뽑아낸 가늘고 우아한 지팡이로, 끝에는 투명에 가까운 수정이 무지갯빛을 은은히 반사하며 박혀 있다. 손에 쥐면 놀랍도록 가벼우면서도 마력이 손끝까지 선명하게 전해지는 감각이 느껴진다.',
    type: 'weapon',
    slot: 'weapon',
    level: 10,
    grade: 'high',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 18,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 90,
  },
];
