import type { ItemSeed } from '../types.js';

export const LEGEND_ITEMS: ItemSeed[] = [
  {
    id: 24,
    name: '전설의 대검',
    description: '거대하고 육중한 검신에 고대 문자가 빼곡히 새겨진 전설의 대검이다. 칼날은 짙은 강철빛을 띠며 칼등을 따라 붉은 균열 같은 문양이 맥동하듯 흐른다. 손잡이는 검은 가죽과 금속으로 감싸여 있고, 검을 휘두를 때마다 공기를 가르며 희미한 잔상이 뒤따른다. 세워 놓으면 사람 키를 훌쩍 넘는 압도적인 크기를 자랑한다.',
    type: 'weapon',
    slot: 'weapon',
    level: 35,
    grade: 'legend',
    strengthBonus: 20,
    attackPowerBonus: 50,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 500,
  },
  {
    id: 25,
    name: '드래곤 스케일 갑옷',
    description: '용의 비늘을 이어 붙여 만든 갑옷으로, 표면이 짙은 청록빛으로 번들거린다. 비늘 하나하나가 미세하게 겹쳐져 있어 움직일 때마다 물결치듯 반짝이고, 어깨 부분에는 작은 뿔 장식이 솟아 있다. 가슴팍에는 용의 심장을 상징하는 붉은 보석이 박혀 마치 살아있는 용의 가죽을 두른 듯한 위압감을 준다. 갑옷 전체에서 옅은 열기가 감돈다.',
    type: 'armor',
    slot: 'top',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 15,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 450,
  },
  {
    id: 26,
    name: '천상의 물약',
    description: '하늘빛으로 빛나는 액체가 담긴 크리스털 병으로, 병 표면에 새의 깃털 문양이 정교하게 새겨져 있다. 액체 속에서 작은 빛의 깃털들이 둥둥 떠다니며, 병을 감싼 은빛 사슬 장식이 신성한 기운을 더한다. 병뚜껑을 열면 은은한 향과 함께 빛이 새어 나오며, 주위 공기마저 맑아지는 듯한 청량감을 남긴다.',
    type: 'consumable',
    slot: null,
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 150,
    manaAmount: 0,
    value: 220,
  },
  {
    id: 27,
    name: '불사조 깃털 목걸이',
    description: '불사조의 깃털을 엮어 만든 목걸이로, 깃털 끝이 타오르는 듯한 주황빛으로 물들어 있다. 목걸이 줄은 금빛 실로 짜여 있고, 중앙의 깃털이 은은하게 빛나며 열기를 뿜는 듯한 잔상을 남긴다. 착용자가 움직일 때마다 깃털이 살짝 흔들리며 불티가 흩날리는 듯한 착시를 일으키고, 은은한 온기가 목덜미에 감돈다.',
    type: 'armor',
    slot: 'necklace',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 12,
    healAmount: 0,
    manaAmount: 0,
    value: 400,
  },
  {
    id: 50,
    name: '용의 방패',
    description: '용의 뼈와 비늘을 엮어 만든 거대한 방패로, 표면이 짙은 청록빛 비늘무늬로 뒤덮여 있다. 방패 가장자리에는 날카로운 뼈 조각이 돌출되어 있고, 중앙에는 용의 눈을 형상화한 붉은 보석이 박혀 있다. 들고 있으면 낮게 울리는 용의 숨결 같은 기운이 느껴지며, 표면 전체가 살아있는 것처럼 미세하게 맥동한다.',
    type: 'armor',
    slot: 'shield',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 22,
    magicDefenseBonus: 10,
    healAmount: 0,
    manaAmount: 0,
    value: 420,
  },
  {
    id: 51,
    name: '용의 투구',
    description: '용의 머리뼈를 본떠 만든 투구로, 양옆에 날카로운 뿔이 솟아 있다. 표면은 짙은 청록빛 비늘로 뒤덮여 있고, 눈구멍 부분에서 옅은 붉은 빛이 새어 나온다. 턱뼈 형상의 장식이 관자놀이까지 이어져 있어 착용자를 마치 용처럼 보이게 하는 위압적인 디자인이며, 뿔 끝은 날카롭게 벼려져 있다.',
    type: 'armor',
    slot: 'hat',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 16,
    magicDefenseBonus: 8,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 52,
    name: '별빛 귀걸이',
    description: '밤하늘의 별빛을 담은 귀걸이로, 투명한 보석 속에 작은 별가루가 흩뿌려진 듯한 무늬가 떠 있다. 걸이 부분은 은백색 금속으로 섬세하게 세공되어 있으며, 움직일 때마다 반짝이는 잔광이 흩날린다. 보석 중심에서 옅은 빛줄기가 별똥별처럼 흘러내리며, 밤하늘 아래서 유독 신비롭게 빛난다.',
    type: 'armor',
    slot: 'earring',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 14,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 360,
  },
  {
    id: 53,
    name: '용의 각반',
    description: '용의 가죽으로 만든 튼튼한 각반으로, 표면에 짙은 비늘 무늬가 도드라져 있다. 무릎 부분에는 작은 발톱 장식이 달려 있고, 다리 옆선을 따라 옅은 붉은 줄무늬가 맥동하듯 흐른다. 강인하면서도 유연한 움직임을 보장하는 관절 구조를 지녔으며, 만지면 뜨거운 체온이 느껴지는 듯하다.',
    type: 'armor',
    slot: 'bottom',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 14,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 380,
  },
  {
    id: 54,
    name: '용의 장갑',
    description: '용의 발톱을 엮어 만든 장갑으로, 손가락 끝에 날카로운 발톱 모양 장식이 달려 있다. 손등은 짙은 비늘무늬 가죽으로 덮여 있으며, 주먹을 쥐면 발톱들이 맞물리듯 정렬되어 위협적인 실루엣을 만든다. 손목 부분에는 붉은 힘줄 문양이 새겨져 있어 마치 살아있는 짐승의 손을 낀 듯한 인상을 준다.',
    type: 'armor',
    slot: 'gloves',
    level: 35,
    grade: 'legend',
    strengthBonus: 14,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 10,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 370,
  },
  {
    id: 55,
    name: '질풍의 신발',
    description: '바람보다 빠르다는 전설의 신발로, 발목 부분에 깃털 같은 은빛 장식이 넓게 펼쳐져 있다. 밑창은 거의 투명에 가까운 소재로 만들어졌고, 걸을 때마다 옅은 바람의 잔상이 소용돌이치며 뒤따른다. 뒤꿈치에는 작은 날개 모양 장식이 달려 있으며, 신는 순간 몸이 깃털처럼 가벼워지는 듯하다.',
    type: 'armor',
    slot: 'shoes',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 18,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 390,
  },
  {
    id: 66,
    name: '전설의 대마도 지팡이',
    description: '고대 문자가 빼곡히 새겨진 거대한 지팡이로, 머리 부분에 박힌 짙은 자수정이 맥동하듯 붉은 균열무늬 빛을 뿜어낸다. 지팡이를 세워 놓으면 사람 키를 훌쩍 넘는 압도적인 크기를 자랑하며, 휘두를 때마다 공기가 마력으로 일렁인다.',
    type: 'weapon',
    slot: 'weapon',
    level: 35,
    grade: 'legend',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 50,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 500,
  },
];
