import type { ItemSeed } from '../types.js';

export const LOW_ITEMS: ItemSeed[] = [
  {
    id: 1,
    name: '낡은 검',
    description: '손잡이 가죽이 해지고 칼날 곳곳에 붉은 녹이 슨 낡은 철검이다. 무딘 회색 날에는 작은 이가 빠진 흠집이 여러 군데 나 있고, 자루 끝엔 색이 바랜 갈색 가죽끈이 느슨하게 감겨 있다. 칼등을 따라 희미하게 남은 대장간 각인이 오랜 세월을 짐작하게 하며, 손에 쥐면 묵직하고 투박한 무게감이 느껴지는 초보자용 무기다. 무광의 어두운 회색 톤이 전체를 감싼다.',
    type: 'weapon',
    slot: 'weapon',
    level: 1,
    grade: 'low',
    strengthBonus: 3,
    attackPowerBonus: 4,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 2,
    name: '나무 방패',
    description: '판자를 덧대어 만든 투박한 원형 나무 방패로, 표면은 옅은 갈색 나무결이 그대로 드러난다. 가장자리를 따라 낡은 철테가 둘러져 있고 중앙에는 간단한 방패 문양이 새겨져 있다. 여러 번의 타격으로 생긴 긁힘과 패임 자국이 곳곳에 남아 있으며, 뒷면 손잡이는 낡은 가죽끈으로 고정되어 있다. 시골 대장간에서 급히 짜맞춘 듯 투박하지만 정겨운 분위기를 풍긴다.',
    type: 'armor',
    slot: 'shield',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 3,
    name: '체력 물약',
    description: '투명한 유리병에 담긴 진한 붉은 액체로, 병 입구는 코르크 마개로 막혀 있고 목 부분에는 붉은 리본이 매듭지어 묶여 있다. 살짝 흔들면 은은하게 반짝이는 작은 입자들이 소용돌이치듯 떠오르며, 병 표면에는 방금 만든 듯 신선한 물방울이 맺혀 있다. 안에서 따뜻한 붉은빛이 은은히 감돌며, 촛불 아래 놓아두면 은은한 붉은 잔광이 주변을 물들인다.',
    type: 'consumable',
    slot: null,
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 10,
    manaAmount: 0,
    value: 5,
  },
  {
    id: 100,
    name: '작은 마나 물약',
    description: '작은 유리병에 담긴 옅은 하늘색 액체로, 병 입구는 낡은 코르크 마개로 막혀 있다. 살짝 흔들면 희미한 청백색 입자가 천천히 소용돌이치듯 떠오르고, 손에 쥐면 미약하지만 서늘한 마력의 기운이 스며든다. 초보 마법사들이 흔히 지니고 다니는 저렴하고 소박한 물약이다.',
    type: 'consumable',
    slot: null,
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 8,
    value: 5,
  },
  {
    id: 4,
    name: '가죽 모자',
    description: '부드러운 갈색 가죽을 여러 겹 덧대 만든 챙 없는 가죽 모자로, 이마 부분에 작은 놋쇠 버클 장식이 달려 있다. 안감은 짙은 색 천으로 마감되어 있고 표면에는 잔주름과 손때 묻은 사용감이 남아 있다. 튼튼하게 바느질된 이음매가 눈에 띄며, 모험가의 첫 방어구다운 소박하고 투박한 실루엣을 지녔다. 낡았지만 정성껏 손질된 흔적이 곳곳에 배어 있다.',
    type: 'armor',
    slot: 'hat',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 6,
  },
  {
    id: 5,
    name: '은귀걸이',
    description: '가늘게 세공된 은사슬에 작은 초승달 모양 장식이 매달린 귀걸이다. 표면은 은은한 광택이 돌며 달빛을 받으면 옅은 푸른빛을 반사한다. 장식 끝에는 좁쌀만 한 보석 알갱이가 박혀 있어 걸을 때마다 희미하게 짤랑거리고, 사슬 마디마다 아주 작은 별 모양 각인이 새겨져 있다. 소박하지만 세심하게 다듬어진 손끝의 정성이 느껴지는 장신구다.',
    type: 'armor',
    slot: 'earring',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 6,
    name: '수호의 목걸이',
    description: '은사슬 목걸이 중앙에 옅은 청록빛으로 은은히 빛나는 작은 마법석이 박혀 있다. 돌 표면에는 가느다란 룬 문양이 소용돌이 모양으로 새겨져 있고, 은은한 마력의 안개가 돌 주위를 감싸듯 피어오른다. 목걸이 줄은 촘촘하게 엮여 있어 단단하면서도 우아한 인상을 주며 착용자의 목선을 따라 자연스럽게 흘러내려 은은한 마력의 기운을 은근히 드러낸다.',
    type: 'armor',
    slot: 'necklace',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 9,
  },
  {
    id: 7,
    name: '가죽 갑옷',
    description: '무두질한 갈색 가죽을 겹겹이 덧대 만든 상체 갑옷으로, 어깨와 가슴 부분에 두꺼운 가죽판이 덧대어져 있다. 옆구리는 여러 개의 끈으로 조여 몸에 맞추는 구조이며, 표면에는 크고 작은 스크래치와 긁힘 자국이 나 있다. 전체적으로 투박하지만 견고한 초보자용 방어구의 느낌을 풍기며, 어깨선을 따라 실용적인 이중 재봉선이 도드라진다.',
    type: 'armor',
    slot: 'top',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 1,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
  {
    id: 8,
    name: '가죽 각반',
    description: '무릎까지 오는 갈색 가죽 각반으로, 다리 바깥쪽에 세로로 긴 가죽 보강대가 덧대어져 있다. 버클 두 개로 종아리에 단단히 고정하며, 가죽 표면에는 걸을 때마다 생긴 자잘한 접힘 주름이 선명하게 보인다. 실용적이고 활동성을 중시한 투박한 디자인이 특징이며, 무릎 아래로 자연스럽게 각이 잡혀 있다.',
    type: 'armor',
    slot: 'bottom',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 1,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 8,
  },
  {
    id: 9,
    name: '가죽 장갑',
    description: '손등을 덮는 짧은 갈색 가죽 장갑으로, 손가락 마디 부분이 살짝 두툼하게 보강되어 있다. 손목 부분은 가는 가죽 끈으로 조이게 되어 있으며, 표면에는 오래 착용한 흔적인 옅은 얼룩과 손때로 길들여진 은은한 광택이 남아 있다. 손끝 마감이 세밀하게 재봉되어 있어 투박함 속에서도 정교함이 느껴진다.',
    type: 'armor',
    slot: 'gloves',
    level: 1,
    grade: 'low',
    strengthBonus: 1,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 1,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 10,
    name: '가죽 신발',
    description: '발등을 감싸는 갈색 가죽 신발로, 밑창은 두꺼운 가죽을 덧대 튼튼하게 마감했다. 발목 부분은 끈으로 교차해 묶게 되어 있고, 표면에는 흙먼지가 묻은 자국과 오랜 걸음걸이로 생긴 자연스러운 주름이 남아 있다. 뒤축은 살짝 닳아 있어 오래 신은 듯한 정겨운 느낌을 주며, 발끝 쪽으로 갈수록 완만하게 둥글다.',
    type: 'armor',
    slot: 'shoes',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 7,
  },
  {
    id: 11,
    name: '힘의 반지',
    description: '가는 은반지 위에 작은 붉은 보석이 박혀 있는 소박한 반지다. 반지 안쪽에는 희미하게 빛나는 각인이 새겨져 있어 착용자의 힘을 북돋아준다고 전해진다. 표면은 은은한 광택을 띠며 오래된 대장간에서 손수 만든 듯한 투박한 세공이 돋보이고, 보석 주변에는 미세한 긁힘 자국이 남아 있어 손때 묻은 정겨움이 배어난다.',
    type: 'armor',
    slot: 'ring',
    level: 1,
    grade: 'low',
    strengthBonus: 2,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 12,
  },
  {
    id: 62,
    name: '낡은 지팡이',
    description: '옹이가 그대로 남은 나뭇가지를 다듬어 만든 투박한 지팡이로, 끝부분에 작고 흐릿한 수정 조각이 실로 동여매어 있다. 표면에는 얕은 흠집이 여러 군데 나 있고, 손잡이 부분은 오래 쥐어 반들반들해졌다. 수정에 마력을 흘려보내면 미약하게나마 옅은 빛이 깜빡이는, 초보 마법사용 지팡이다.',
    type: 'weapon',
    slot: 'weapon',
    level: 1,
    grade: 'low',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 4,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 10,
  },
];
