import type { ItemSeed } from '../types.js';

export const MID_ITEMS: ItemSeed[] = [
  {
    id: 12,
    name: '강철 검',
    description: '잘 벼려진 은회색 강철 검으로, 날이 곧고 예리하게 서 있어 빛을 받으면 매끄럽게 반사된다. 칼자루는 짙은 청색 가죽으로 감싸여 있고, 손잡이 끝에는 작은 철제 장식이 달려 있다. 칼날 근처에 새겨진 가는 덩굴무늬가 은은하게 반짝이며, 낡은 검보다 한층 정교하고 균형 잡힌 인상을 준다. 대장간에서 갓 벼려낸 듯한 청량한 금속 광택이 돋보인다.',
    type: 'weapon',
    slot: 'weapon',
    level: 5,
    grade: 'mid',
    strengthBonus: 5,
    attackPowerBonus: 10,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 40,
  },
  {
    id: 13,
    name: '사슬 갑옷',
    description: '촘촘히 엮인 강철 사슬로 만들어진 상체 갑옷으로, 사슬 고리들이 빼곡히 겹쳐져 은빛으로 반짝인다. 목과 어깨 부분은 부드러운 가죽으로 덧대 마감했으며, 착용하면 몸의 움직임에 따라 사슬이 부드럽게 찰랑거리는 소리를 낸다. 견고하면서도 유연한 인상을 주는 중급 방어구로, 허리춤까지 촘촘히 이어진 고리들이 은은한 파동처럼 빛난다.',
    type: 'armor',
    slot: 'top',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 2,
    healAmount: 0,
    manaAmount: 0,
    value: 35,
  },
  {
    id: 14,
    name: '마나 물약',
    description: '푸르게 빛나는 액체가 담긴 유리병으로, 병 속에서 작은 마력 입자가 별처럼 반짝이며 떠다닌다. 병 입구는 은색 마개로 밀봉되어 있고, 목 부분에는 파란 리본이 나비 모양으로 묶여 있다. 병을 살짝 흔들면 옅은 청백색 빛이 소용돌이치듯 일렁이며 병 표면까지 은은하게 번지고, 손에 쥐면 서늘하고 상쾌한 냉기가 전해진다.',
    type: 'consumable',
    slot: null,
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 20,
    value: 15,
  },
  {
    id: 15,
    name: '강철 방패',
    description: '두꺼운 강철판을 둥글게 두드려 만든 방패로, 표면 중앙에 볼록한 돌기가 솟아 있다. 가장자리는 이중으로 리벳 처리되어 있으며, 짙은 회색 금속 광택이 묵직한 존재감을 준다. 방패 안쪽에는 팔을 고정하는 두꺼운 가죽 손잡이가 달려 있고, 곳곳에 실전에서 생긴 자잘한 흠집이 남아 있어 노련한 방어구의 풍모가 느껴진다.',
    type: 'armor',
    slot: 'shield',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 4,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 30,
  },
  {
    id: 32,
    name: '강철 투구',
    description: '강철판을 둥글게 두드려 만든 투구로, 이마 부분에 가로로 긴 홈이 파여 있다. 표면은 은회색 광택을 띠며 관자놀이 부분에 작은 통풍구가 뚫려 있다. 턱끈은 두꺼운 가죽으로 되어 있고, 정수리 부분에는 짧은 술 장식이 달려 단순하지만 견고한 병사용 투구의 느낌을 준다. 표면에는 실전에서 생긴 작은 찍힘 자국이 남아 있다.',
    type: 'armor',
    slot: 'hat',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 3,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 25,
  },
  {
    id: 33,
    name: '흑요석 귀걸이',
    description: '매끈하게 연마된 검은 흑요석 조각이 매달린 귀걸이다. 표면은 유리처럼 광택이 흐르며 빛을 받으면 자주빛으로 은은하게 반사된다. 걸이 부분은 가는 은사로 만들어져 있어 검은 보석과 대비되는 우아함을 더하고, 조각 안쪽에는 미세한 기포 무늬가 비쳐 보인다. 어두운 조명 아래서도 은은한 존재감을 드러낸다.',
    type: 'armor',
    slot: 'earring',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 3,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 22,
  },
  {
    id: 34,
    name: '마력 목걸이',
    description: '은사슬에 옅은 보랏빛으로 빛나는 마력석이 매달린 목걸이다. 돌 표면에는 소용돌이 형태의 룬이 새겨져 있고, 목걸이를 착용하면 돌 주위로 희미한 안개 같은 마력이 피어오른다. 세공이 정교해 마법사들이 선호할 법한 절제된 디자인을 지녔으며, 사슬 마디마다 옅은 보랏빛 잔광이 스며 있다.',
    type: 'armor',
    slot: 'necklace',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 3,
    healAmount: 0,
    manaAmount: 0,
    value: 28,
  },
  {
    id: 35,
    name: '강철 각반',
    description: '정강이를 감싸는 강철판 각반으로, 무릎 부분에 둥근 보호대가 덧대어져 있다. 표면은 은회색으로 빛나며 이음새마다 작은 리벳이 촘촘히 박혀 있다. 다리 옆면에는 세로로 긴 홈이 파여 있어 움직임을 방해하지 않는 실용적인 구조가 돋보이며, 정강이뼈를 따라 매끄러운 곡선을 그린다.',
    type: 'armor',
    slot: 'bottom',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 2,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  {
    id: 36,
    name: '강철 장갑',
    description: '손등을 덮는 강철 장갑으로, 손가락 마디마다 얇은 금속판이 겹겹이 이어져 있다. 손목 부분은 가죽 끈으로 조이게 되어 있으며, 표면은 은회색 광택을 띤다. 주먹을 쥐면 금속판들이 자연스럽게 맞물리며 접히는 정교한 관절 구조가 돋보이며, 손끝까지 세밀하게 마감되어 있다.',
    type: 'armor',
    slot: 'gloves',
    level: 5,
    grade: 'mid',
    strengthBonus: 2,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 2,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 24,
  },
  {
    id: 37,
    name: '은빛 부츠',
    description: '은빛으로 반짝이는 가죽 부츠로, 발목 부분에 가는 금속 버클이 달려 있다. 밑창 가장자리를 따라 옅은 은색 실선이 둘러져 있고, 걸을 때마다 희미한 은빛 잔광이 발자국을 따라 남는다. 앞코 부분이 살짝 뾰족하게 마감되어 가볍고 날렵한 인상을 주며, 전체적으로 매끈한 은빛 윤기가 흐른다.',
    type: 'armor',
    slot: 'shoes',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 26,
  },
  {
    id: 63,
    name: '강철 테 지팡이',
    description: '매끄러운 목재 지팡이 끝을 은회색 강철 테가 감싸고 있으며, 그 안에 맑은 푸른 수정이 단단히 고정되어 있다. 강철 테에는 가는 덩굴무늬가 새겨져 있어 마력이 흐를 때마다 옅게 반짝인다. 낡은 지팡이보다 마력을 훨씬 안정적으로 모아 전달해준다.',
    type: 'weapon',
    slot: 'weapon',
    level: 5,
    grade: 'mid',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 10,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 40,
  },
];
