import type { ItemSeed } from '../types.js';

export const RARE_ITEMS: ItemSeed[] = [
  {
    id: 20,
    name: '용의 발톱',
    description: '검은 비늘로 뒤덮인 용의 발톱을 그대로 벼려낸 곡도다. 날은 짙은 검붉은빛을 띠며 표면에 미세한 균열무늬가 있어 마치 살아있는 듯한 질감을 준다. 손잡이는 용의 힘줄을 꼬아 만들었고, 칼날 밑동에서 옅은 열기가 아지랑이처럼 피어올라 손에 쥐면 뜨거운 기운이 전해진다. 휘두르면 낮은 포효 같은 진동이 손목을 타고 올라온다.',
    type: 'weapon',
    slot: 'weapon',
    level: 20,
    grade: 'rare',
    strengthBonus: 12,
    attackPowerBonus: 30,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 200,
  },
  {
    id: 21,
    name: '수호자의 방패',
    description: '고대 수호자의 문장이 새겨진 육중한 강철 방패로, 표면은 짙은 청동빛으로 산화되어 있다. 가장자리에는 룬 문자가 원을 그리며 새겨져 있고, 방패 중앙의 보석이 은은한 푸른빛을 내뿜는다. 곳곳에 패인 전투의 흔적이 남아 있어 오랜 세월을 버텨온 위엄이 느껴지며, 들고 있으면 묵직한 안정감이 팔 전체에 퍼진다.',
    type: 'armor',
    slot: 'shield',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 10,
    magicDefenseBonus: 5,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  {
    id: 22,
    name: '엘릭서',
    description: '황금빛으로 일렁이는 액체가 담긴 정교한 유리병으로, 병 자체가 나선형으로 꼬여 있고 마개는 작은 보석으로 장식되어 있다. 액체 속에서 빛의 알갱이들이 끊임없이 소용돌이치며 떠오르고, 병 전체가 손에 쥐면 은은한 온기를 발산해 마치 살아 숨쉬는 듯한 느낌을 준다. 희귀한 재료의 향긋한 잔향이 병 주위를 맴돈다.',
    type: 'consumable',
    slot: null,
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 80,
    manaAmount: 0,
    value: 90,
  },
  {
    id: 23,
    name: '바람의 신발',
    description: '가벼운 은빛 가죽으로 만들어진 신발로, 발등 부분에 작은 날개 문양이 새겨져 있다. 밑창 가장자리를 따라 옅은 청록빛 깃털 무늬가 둘러져 있으며, 신발 전체에서 산들바람이 스치는 듯한 가벼운 잔광이 흩날린다. 신는 순간 발걸음이 한결 가벼워지는 듯한 인상을 주며, 걸을 때마다 옅은 바람 소리가 함께한다.',
    type: 'armor',
    slot: 'shoes',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 160,
  },
  {
    id: 44,
    name: '용비늘 투구',
    description: '용의 비늘 조각을 이어 붙여 만든 투구로, 이마 부분에 작은 뿔 장식이 솟아 있다. 표면은 짙은 초록빛으로 광택이 흐르며 비늘 무늬가 그대로 살아 있어 마치 용의 머리를 형상화한 듯한 위압감을 준다. 눈가리개 부분에는 가는 틈이 뚫려 있으며, 빛을 받으면 비늘 하나하나가 미세하게 반짝인다.',
    type: 'armor',
    slot: 'hat',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 9,
    magicDefenseBonus: 4,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 45,
    name: '심연의 귀걸이',
    description: '칠흑같이 검은 보석이 매달린 귀걸이로, 보석 표면에서 옅은 보랏빛 안개가 스며 나온다. 걸이 부분은 어두운 금속으로 만들어져 있으며, 보석 안쪽에서 소용돌이치는 듯한 문양이 은은하게 비쳐 보인다. 착용하면 서늘한 기운이 귓가에 감도는 듯하며, 어둠 속에서도 은은히 존재를 드러낸다.',
    type: 'armor',
    slot: 'earring',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 8,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 46,
    name: '대현자의 목걸이',
    description: '은사슬에 커다란 지혜의 보석이 매달린 목걸이로, 보석 표면에 고대 문자가 촘촘히 새겨져 있다. 보석 안쪽에서 옅은 남색 빛이 맥동하듯 일렁이며, 목걸이를 착용하면 사색에 잠긴 듯한 신비로운 기운이 감돈다. 줄은 두 겹으로 꼬아 만들어져 있으며 보석의 무게감이 손끝에 묵직하게 전해진다.',
    type: 'armor',
    slot: 'necklace',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 14,
    healAmount: 0,
    manaAmount: 0,
    value: 170,
  },
  {
    id: 47,
    name: '수호자의 갑옷',
    description: '고대 수호자가 두르던 갑옷으로, 표면이 짙은 청동빛으로 산화되어 있다. 가슴판에는 커다란 방패 문양이 돋을새김되어 있고, 이음새마다 룬 문자가 새겨져 있다. 어깨와 팔꿈치 부분은 두툼하게 보강되어 있어 오랜 세월을 견뎌온 묵직하고 위엄 있는 존재감을 풍기며, 표면 곳곳에 청록빛 녹이 배어 있다.',
    type: 'armor',
    slot: 'top',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 0,
    physicalDefenseBonus: 12,
    magicDefenseBonus: 6,
    healAmount: 0,
    manaAmount: 0,
    value: 190,
  },
  {
    id: 48,
    name: '수호자의 각반',
    description: '고대 수호자가 두르던 각반으로, 정강이 부분에 두꺼운 청동빛 강판이 덧대어져 있다. 표면에는 방어의 룬 문자가 새겨져 있고, 무릎 보호대 부분이 둥글게 돌출되어 있다. 발목 이음새는 촘촘한 사슬로 마감되어 튼튼하고 신뢰감 있는 인상을 주며, 오랜 풍파를 겪은 듯한 짙은 색조를 띤다.',
    type: 'armor',
    slot: 'bottom',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 4,
    physicalDefenseBonus: 8,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 150,
  },
  {
    id: 49,
    name: '폭풍의 반지',
    description: '짙은 회색 구름무늬가 소용돌이치는 반지로, 표면에서 작은 번개 문양이 번쩍인다. 반지를 착용하면 손끝에서 미세한 정전기 같은 빛이 튀며, 반지 안쪽 테두리를 따라 가는 전류 문양이 흐른다. 폭풍의 힘이 응축된 듯한 역동적인 존재감을 풍기며, 낮게 우르릉거리는 소리가 희미하게 들리는 듯하다.',
    type: 'armor',
    slot: 'ring',
    level: 20,
    grade: 'rare',
    strengthBonus: 6,
    attackPowerBonus: 0,
    intelligenceBonus: 0,
    dexterityBonus: 6,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 180,
  },
  {
    id: 65,
    name: '용의 지팡이',
    description: '용의 척추 뼈를 깎아 만든 지팡이로, 끝에 박힌 검붉은 수정에서 옅은 열기가 아지랑이처럼 피어오른다. 표면의 비늘 무늬 사이로 낮은 진동이 전해지며, 마력을 담을 때마다 낮은 포효 같은 울림이 손목을 타고 올라온다.',
    type: 'weapon',
    slot: 'weapon',
    level: 20,
    grade: 'rare',
    strengthBonus: 0,
    attackPowerBonus: 0,
    intelligenceBonus: 30,
    dexterityBonus: 4,
    physicalDefenseBonus: 0,
    magicDefenseBonus: 0,
    healAmount: 0,
    manaAmount: 0,
    value: 200,
  },
];
